Repository smartcontractkit/chainlink, pull requests merged in 2020-06, with the labels that each got.

#2994 add logging to eth client RPC wrapper functions
  core/eth/client.go
Labels: accepted

#3013 Use geth's built-in Header type
  core/eth/client.go
  core/eth/types.go
  core/eth/types_test.go
  core/internal/cltest/client.go
  core/internal/cltest/client_test.go
  core/internal/cltest/cltest.go
  core/internal/cltest/factories.go
  core/internal/cltest/mocks.go
  core/internal/features_test.go
  core/internal/mocks/client.go
  core/internal/mocks/tx_manager.go
  core/services/head_tracker.go
  core/services/head_tracker_test.go
  core/store/models/eth.go
  core/store/models/eth_test.go
Labels: ready for review

#2997 BulletproofTxManager
  .circleci/config.yml
  CHANGELOG-core.md
  core/adapters/eth_tx.go
  core/adapters/eth_tx_test.go
  core/assets/currencies.go
  core/cmd/app.go
  core/cmd/local_client.go
  core/cmd/local_client_test.go
  core/eth/client.go
  core/internal/cltest/client.go
  core/internal/cltest/cltest.go
  core/internal/cltest/factories.go
  core/internal/cltest/mocks.go
  core/internal/cltest/postgres.go
  core/internal/mocks/caller_subscriber.go
  core/internal/mocks/client.go
  core/internal/mocks/geth_client.go
  core/internal/mocks/key_store_interface.go
  core/internal/mocks/notify_new_eth_tx.go
  core/internal/mocks/tx_manager.go
  core/services/bulletprooftxmanager/bulletprooftxmanager.go
  core/services/bulletprooftxmanager/bulletprooftxmanager_test.go
  core/services/bulletprooftxmanager/errors.go
  core/services/bulletprooftxmanager/errors_test.go
  core/services/bulletprooftxmanager/eth_broadcaster.go
  core/services/bulletprooftxmanager/eth_broadcaster_test.go
  core/services/bulletprooftxmanager/eth_confirmer.go
  core/services/bulletprooftxmanager/eth_confirmer_test.go
  core/services/chainlink/application.go
  core/services/gas_updater.go
  core/services/head_tracker.go
  core/services/head_tracker_test.go
  core/services/testdata/runlog_ethtx_w_missing_fromAddress_job.json
  core/services/validators.go
  core/services/validators_test.go
  core/store/key_store.go
  core/store/key_store_test.go
  core/store/migrations/migrate.go
  core/store/migrations/migration0/migrate.go
  core/store/migrations/migration1589206996/migrate.go
  core/store/migrations/migration1589462363/migrate.go
  core/store/models/eth.go
  core/store/models/eth_test.go
  core/store/models/id.go
  core/store/models/key.go
  core/store/orm/config.go
  core/store/orm/config_reader.go
  core/store/orm/orm.go
  core/store/orm/orm_test.go
  core/store/orm/schema.go
  core/store/store.go
  core/store/testdata/fixtures.sql
  core/store/tx_manager.go
  core/store/tx_manager_test.go
  core/utils/big.go
  core/utils/big_test.go
  core/web/job_specs_controller_test.go
  go.mod
  go.sum
Labels: ready for review

#3060 Remove 'withdraw' functionality and convert SendEther to work with BPTXM
  CHANGELOG-core.md
  core/adapters/eth_tx.go
  core/adapters/eth_tx_test.go
  core/assets/currencies.go
  core/cmd/app.go
  core/cmd/local_client.go
  core/cmd/remote_client.go
  core/cmd/remote_client_test.go
  core/internal/features_test.go
  core/services/bulletprooftxmanager/bulletprooftxmanager.go
  core/services/bulletprooftxmanager/doc/BulletproofTxManager Architecture Overview.md
  core/services/bulletprooftxmanager/eth_confirmer.go
  core/services/chainlink/application.go
  core/store/models/common.go
  core/store/models/eth.go
  core/store/orm/config.go
  core/store/orm/config_reader.go
  core/store/orm/config_test.go
  core/store/orm/schema.go
  core/store/presenters/presenters.go
  core/store/tx_manager.go
  core/store/tx_manager_test.go
  core/web/config_controller_test.go
  core/web/router.go
  core/web/transfer_controller.go
  core/web/transfer_controller_test.go
  core/web/withdrawals_controller.go
  core/web/withdrawals_controller_test.go
  go.mod
  go.sum
Labels: ready for review

#3012 Update fluxmonitor logs to include payment amount in ethTX tasks
  core/internal/features_test.go
  core/services/fluxmonitor/flux_monitor.go
  core/services/fluxmonitor/helpers_test.go
Labels: ready for review

#3064 Enable rebroadcast-transactions to work with BPTXM
  core/cmd/app.go
  core/cmd/local_client.go
  core/cmd/local_client_test.go
  core/internal/cltest/factories.go
  core/services/bulletprooftxmanager/bulletprooftxmanager.go
  core/services/bulletprooftxmanager/eth_confirmer.go
  core/services/bulletprooftxmanager/eth_confirmer_test.go
Labels: ready for review

#3084 HeadTracker backfills missing heads up to EthFinalityDepth
  CHANGELOG-core.md
  core/internal/mocks/geth_client.go
  core/services/eth/client.go
  core/services/head_tracker.go
  core/services/head_tracker_test.go
  core/store/models/eth.go
  core/store/models/eth_test.go
  core/store/orm/orm.go
  core/store/orm/orm_test.go
Labels: ready for review

#3102 Add flux monitor ORM tests, fix flux monitor ORM methods
  core/store/orm/orm.go
  core/store/orm/orm_test.go
Labels: ready for acceptance

#3110 Upgrade mockery
  core/internal/mocks/after_nower.go
  core/internal/mocks/caller_subscriber.go
  core/internal/mocks/client.go
  core/internal/mocks/deviation_checker.go
  core/internal/mocks/deviation_checker_factory.go
  core/internal/mocks/fetcher.go
  core/internal/mocks/flux_aggregator.go
  core/internal/mocks/geth_client.go
  core/internal/mocks/head_trackable.go
  core/internal/mocks/job_subscriber.go
  core/internal/mocks/key_store_interface.go
  core/internal/mocks/log_broadcast.go
  core/internal/mocks/log_broadcaster.go
  core/internal/mocks/log_listener.go
  core/internal/mocks/notify_new_eth_tx.go
  core/internal/mocks/run_executor.go
  core/internal/mocks/run_manager.go
  core/internal/mocks/run_queue.go
  core/internal/mocks/service.go
  core/internal/mocks/stats_pusher.go
  core/internal/mocks/subscription.go
  core/internal/mocks/tx_manager.go
  core/services/chainlink/application.go
  core/services/eth/client.go
  core/services/eth/contracts/FluxAggregator.go
  core/services/eth/log_broadcaster.go
  core/services/fluxmonitor/fetchers.go
  core/services/fluxmonitor/flux_monitor.go
  core/services/internal/mocks/application.go
  core/services/job_subscriber.go
  core/services/run_executor.go
  core/services/run_manager.go
  core/services/run_queue.go
  core/services/synchronization/stats_pusher.go
  core/store/key_store.go
  core/store/store.go
  core/store/tx_manager.go
  core/store/types.go
  core/utils/interfaces.go
Labels: dependencies, ready for review

#3113 Refactor job show presenter to include PollTimer and IdleTimer fields
  core/store/presenters/presenters.go
  core/web/job_specs_controller_test.go
Labels: ready for review
