Repository smartcontractkit/chainlink, pull requests merged in 2020-05, with the labels that each got.

#2947 refactor: cleanup the orm.Connection type and orm.go orgnanization
  core/services/run_executor.go
  core/store/orm/locking_strategies.go
  core/store/orm/locking_strategies_test.go
  core/store/orm/orm.go
  core/store/orm/orm_test.go
Labels: accepted

#2961 Make log broadcaster backfill depth configurable
  core/cmd/local_client_test.go
  core/services/eth/log_broadcaster.go
  core/services/eth/log_broadcaster_test.go
  core/services/fluxmonitor/flux_monitor.go
  core/store/orm/config.go
  core/store/orm/config_reader.go
  core/store/orm/config_test.go
  core/store/orm/schema.go
  core/store/presenters/presenters.go
  core/web/config_controller_test.go
  operator_ui/@types/core/store/presenters.d.ts
Labels: ready for acceptance

#2964 Update Core Changelog
  CHANGELOG-core.md
Labels: do-not-merge-yet, ready for review

#2968 Add response read size limit to bridge adapter
  core/adapters/bridge.go
  core/adapters/bridge_test.go
  core/adapters/http_test.go
  core/store/orm/config.go
Labels: accepted

#2986 Make FM polling requests include arbitrary id field
  core/services/fluxmonitor/fetchers.go
  core/services/fluxmonitor/fetchers_test.go
  core/services/fluxmonitor/helpers_test.go
Labels: ready for acceptance

#2963 Auto-apply strict file permissions requirements to all sensitive files
  CHANGELOG-core.md
  core/cmd/local_client.go
  core/store/models/key.go
  core/store/models/vrfkey/serialization.go
  core/store/orm/config.go
  core/store/orm/orm.go
  core/store/store.go
  core/utils/files.go
Labels: accepted
