Repository smartcontractkit/chainlink, pull requests merged in 2020-07, with the labels that each got.

#2936 Add benchmark for VRF off-chain proof validation
  core/services/vrf/benchmark_vrf_validation_test.go
Labels: ready for review

#3111 Gas bumper should bump on current gasprice not original gasprice
  CHANGELOG-core.md
  core/services/bulletprooftxmanager/bulletprooftxmanager_test.go
  core/services/bulletprooftxmanager/eth_confirmer_test.go
  core/store/tx_manager.go
Labels: ready for acceptance

#3104 add check for file ownership on sensitive files
  core/cmd/local_client.go
  core/utils/files.go
Labels: accepted

#3014 VRFConsumerBase rejects fulfilment attempts from non-VRFCoordinator
  core/adapters/random_test.go
  core/internal/gethwrappers/generated/solidity_vrf_consumer_interface/solidity_vrf_consumer_interface.go
  core/internal/gethwrappers/generated/solidity_vrf_coordinator_interface/solidity_vrf_coordinator_interface.go
  core/internal/gethwrappers/generated/solidity_vrf_request_id/solidity_vrf_request_id.go
  core/internal/gethwrappers/generated/solidity_vrf_verifier_wrapper/solidity_vrf_verifier_wrapper.go
  core/internal/gethwrappers/generation/fastgen.py
  core/internal/gethwrappers/generation/generated-wrapper-dependency-versions-do-not-edit.txt
  core/internal/gethwrappers/go_generate.go
  core/services/vrf/vrf_consumer_base_test.go
  core/services/vrf/vrf_coordinator_solidity_crosscheck_test.go
  core/services/vrf/vrf_hash_to_curve_cost_test.go
  core/services/vrf/vrf_solidity_crosscheck_test.go
  core/store/models/vrf_coordinator_interface_test.go
  core/store/models/vrfkey/private_key_test.go
  core/store/vrf_key_store_test.go
  evm-contracts/src/v0.6/VRFConsumerBase.sol
  evm-contracts/src/v0.6/VRFCoordinator.sol
  evm-contracts/src/v0.6/tests/VRFConsumer.sol
Labels: ready for review

#2969 Incorporate block hash into VRF seed
  core/adapters/random.go
  core/adapters/random_test.go
  core/cmd/key_store_authenticator.go
  core/cmd/local_client_vrf.go
  core/internal/cltest/vrf/vrf.go
  core/internal/features_test.go
  core/internal/gethwrappers/generated/solidity_vrf_coordinator_interface/solidity_vrf_coordinator_interface.go
  core/internal/gethwrappers/generated/solidity_vrf_verifier_wrapper/solidity_vrf_verifier_wrapper.go
  core/internal/gethwrappers/generation/generate/wrap.go
  core/internal/gethwrappers/generation/generate_link/wrap_link.go
  core/internal/gethwrappers/generation/generated-wrapper-dependency-versions-do-not-edit.txt
  core/services/vrf/benchmark_vrf_validation_test.go
  core/services/vrf/helpers_test.go
  core/services/vrf/proof_response.go
  core/services/vrf/seed.go
  core/services/vrf/vrf.go
  core/services/vrf/vrf_coordinator_solidity_crosscheck_test.go
  core/services/vrf/vrf_fulfillment_cost_test.go
  core/services/vrf/vrf_request_cost_test.go
  core/services/vrf/vrf_test.go
  core/store/models/parse_randomness_request.go
  core/store/models/vrfkey/private_key.go
  core/store/models/vrfkey/private_key_test.go
  core/store/models/vrfkey/public_key.go
  core/store/vrf_key_store.go
  core/store/vrf_key_store_db.go
  core/store/vrf_key_store_test.go
  evm-contracts/src/v0.6/VRF.sol
  evm-contracts/src/v0.6/VRFCoordinator.sol
  evm-contracts/src/v0.6/interfaces/BlockHashStoreInterface.sol
Labels: ready for review

#3037 Show/track node build info
  CHANGELOG-core.md
  CHANGELOG-explorer.md
  core/services/synchronization/web_socket_client.go
  core/services/synchronization/web_socket_client_test.go
  explorer/README.md
  explorer/client/@types/explorer.d.ts
  explorer/client/src/components/Admin/Operators/List.tsx
  explorer/client/src/components/Admin/Operators/Operator.tsx
  explorer/client/src/reducers/adminOperatorsShow.ts
  explorer/src/__tests__/server/realtime.test.ts
  explorer/src/__tests__/sessions.test.ts
  explorer/src/controllers/admin/nodes.ts
  explorer/src/entity/ChainlinkNode.ts
  explorer/src/migration/1591302940949-AddVersionAndShaToNode.ts
  explorer/src/serializers/chainlinkNodeSerializer.ts
  explorer/src/serializers/chainlinkNodeShowSerializer.ts
  explorer/src/server/realtime.ts
  explorer/src/sessions.ts
  explorer/src/support/client.ts
  explorer/src/utils/constants.ts
Labels: ready for review
