Repository smartcontractkit/chainlink, pull requests merged in 2021-03, with the labels that each got.

#3968 OperatorForwarder deployment with CREATE2 (& bonus removing bytecode metadata! 🚀)
  core/internal/gethwrappers/extract_contract_details.go
  core/internal/gethwrappers/generated/flags_wrapper/flags_wrapper.go
  core/internal/gethwrappers/generated/flux_aggregator_wrapper/flux_aggregator_wrapper.go
  core/internal/gethwrappers/generated/multiwordconsumer_wrapper/multiwordconsumer_wrapper.go
  core/internal/gethwrappers/generated/operator_wrapper/operator_wrapper.go
  core/internal/gethwrappers/generated/solidity_vrf_consumer_interface/solidity_vrf_consumer_interface.go
  core/internal/gethwrappers/generated/solidity_vrf_coordinator_interface/solidity_vrf_coordinator_interface.go
  core/internal/gethwrappers/generated/solidity_vrf_request_id/solidity_vrf_request_id.go
  core/internal/gethwrappers/generated/solidity_vrf_verifier_wrapper/solidity_vrf_verifier_wrapper.go
  core/internal/gethwrappers/generation/generated-wrapper-dependency-versions-do-not-edit.txt
  evm-contracts/app.config.json
  evm-contracts/src/v0.7/dev/Operator.sol
  evm-contracts/src/v0.7/dev/OperatorForwarder.sol
  evm-contracts/src/v0.7/interfaces/OperatorInterface.sol
  evm-contracts/src/v0.7/tests/OperatorForwarderDeployer.sol
  evm-contracts/test/v0.7/Operator.test.ts
  evm-contracts/test/v0.7/OperatorForwarder.test.ts
Labels: ready for review

#4025 Move GasUpdater into background process, remove gas price update lag on startup
  core/internal/cltest/cltest.go
  core/internal/features_test.go
  core/services/bulletprooftxmanager/eth_confirmer.go
  core/services/chainlink/application.go
  core/services/eth/client.go
  core/services/gas_updater.go
  core/services/gas_updater_test.go
  core/services/gasupdater/gas_updater.go
  core/services/gasupdater/gas_updater_test.go
  core/services/gasupdater/helpers_test.go
  core/services/gasupdater/mocks/config.go
  core/services/log/mocks/broadcast.go
  core/services/log/mocks/orm.go
  core/services/pipeline/mocks/config.go
  core/store/models/eth.go
  core/store/models/eth_test.go
  core/store/orm/config.go
  core/store/orm/schema.go
  core/web/job_specs_controller_test.go
  docs/CHANGELOG.md
  go.mod
Labels: ready for acceptance

#4033 Pull keeper into core
  core/internal/cltest/cltest.go
  core/internal/cltest/contract_mock_receiver.go
  core/internal/cltest/factories.go
  core/internal/cltest/simulated_backend.go
  core/internal/gethwrappers/generated/basic_upkeep_contract/basic_upkeep_contract.go
  core/internal/gethwrappers/generated/keeper_registry_wrapper/keeper_registry_wrapper.go
  core/internal/gethwrappers/generated/mock_v3_aggregator_contract/mock_v3_aggregator_contract.go
  core/services/chainlink/application.go
  core/services/fluxmonitor/flux_monitor_simulated_blockchain_test.go
  core/services/job/job_orm_test.go
  core/services/job/models.go
  core/services/job/orm.go
  core/services/keeper/common.go
  core/services/keeper/delegate.go
  core/services/keeper/helpers_test.go
  core/services/keeper/integration_test.go
  core/services/keeper/models.go
  core/services/keeper/orm.go
  core/services/keeper/orm_test.go
  core/services/keeper/registry_synchronizer.go
  core/services/keeper/registry_synchronizer_test.go
  core/services/keeper/upkeep_executer.go
  core/services/keeper/upkeep_executer_test.go
  core/services/keeper/validate.go
  core/services/keeper/validate_test.go
  core/store/migrations/0014_add_keeper_tables.go
  core/store/orm/config.go
  core/store/orm/schema.go
  core/web/jobs_controller.go
  core/web/jobs_controller_test.go
  core/web/presenters/job.go
  core/web/testdata/keeper-spec.toml
  go.mod
Labels: ready for review

#3938 Price Feed deviation validation against Compound Open Oracle 💲
  evm-contracts/src/v0.7/dev/CompoundPriceFlaggingValidator.sol
  evm-contracts/src/v0.7/dev/StalenessFlaggingValidator.sol
  evm-contracts/src/v0.7/dev/UpkeepBase.sol
  evm-contracts/src/v0.7/dev/UpkeepCompatible.sol
  evm-contracts/src/v0.7/dev/UpkeepInterface.sol
  evm-contracts/src/v0.7/interfaces/UniswapAnchoredView.sol
  evm-contracts/src/v0.7/interfaces/UpkeepInterface.sol
  evm-contracts/src/v0.7/tests/MockCompoundOracle.sol
  evm-contracts/src/v0.7/tests/MockV3Aggregator.sol
  evm-contracts/test/v0.7/CompoundPriceFlaggingValidator.test.ts
  evm-contracts/test/v0.7/StalenessFlaggingValidator.test.ts
Labels: ready for review

#4080 Allow autologin to work without a cookie file
  core/cmd/client.go
  core/cmd/client_test.go
  core/cmd/remote_client.go
  core/internal/fixtures/badcookie/cookie
Labels: ready for acceptance

#4129 Add fulfilled check to randomness adapter
  core/adapters/random.go
  core/adapters/random_test.go
  core/services/vrf/vrf_simulate_blockchain_test.go
  core/store/models/parse_randomness_request.go
  core/utils/utils.go
  docs/CHANGELOG.md
Labels: ready for acceptance, ready for review

#4121 Bugfix/177323594 Metadata in JPV2
  core/internal/cltest/cltest.go
  core/internal/cltest/mocks.go
  core/internal/features_test.go
  core/services/fluxmonitor/fetchers_test.go
  core/services/fluxmonitor/flux_monitor.go
  core/services/fluxmonitor/flux_monitor_test.go
  core/services/fluxmonitorv2/flux_monitor.go
  core/services/fluxmonitorv2/flux_monitor_test.go
  core/services/fluxmonitorv2/integrations_test.go
  core/services/fluxmonitorv2/pipeline.go
  core/services/fluxmonitorv2/pipeline_test.go
  core/services/job/job_pipeline_orm_integration_test.go
  core/services/job/runner_integration_test.go
  core/services/offchainreporting/data_source.go
  core/services/offchainreporting/delegate.go
  core/services/pipeline/common.go
  core/services/pipeline/mocks/runner.go
  core/services/pipeline/orm.go
  core/services/pipeline/runner.go
  core/services/pipeline/runner_test.go
  core/services/pipeline/task.any.go
  core/services/pipeline/task.any_test.go
  core/services/pipeline/task.bridge.go
  core/services/pipeline/task.bridge_test.go
  core/services/pipeline/task.http.go
  core/services/pipeline/task.http_test.go
  core/services/pipeline/task.jsonparse.go
  core/services/pipeline/task.jsonparse_test.go
  core/services/pipeline/task.median.go
  core/services/pipeline/task.median_test.go
  core/services/pipeline/task.multiply.go
  core/services/pipeline/task.multiply_test.go
  core/services/pipeline/task.panic.go
  core/store/models/bridge_type.go
Labels: ready for review
