Repository smartcontractkit/chainlink, pull requests merged in 2021-05, with the labels that each got.

#4284 `Operator` has a single `OperatorForwarder` ☝️
  core/internal/gethwrappers/generated/operator_wrapper/operator_wrapper.go
  core/internal/gethwrappers/generation/generated-wrapper-dependency-versions-do-not-edit.txt
  evm-contracts/src/v0.7/dev/Operator.sol
  evm-contracts/src/v0.7/dev/OperatorForwarder.sol
  evm-contracts/src/v0.7/interfaces/OperatorInterface.sol
  evm-contracts/src/v0.7/tests/OperatorForwarderDeployer.sol
  evm-contracts/test/v0.7/Operator.test.ts
  evm-contracts/test/v0.7/OperatorForwarder.test.ts
Labels: making changes

#4345 Fix `make install` and add hardhat info to readme
  README.md
  evm-contracts/package.json
Labels: ready for review

#4342 bugfix/8256 Multiple subscriptions part 2
  core/services/eth/client.go
  core/services/eth/mocks/client.go
  core/services/job_subscriber.go
  core/services/job_subscriber_test.go
  core/services/subscription.go
  core/services/subscription_internal_test.go
Labels: ready for acceptance

#4271 Move `minConfirmations` handling out of v2 job types, use LogBroadcaster
  core/services/chainlink/application.go
  core/services/cron/cron_test.go
  core/services/directrequest/delegate.go
  core/services/directrequest/delegate_test.go
  core/services/keeper/delegate.go
  core/services/keeper/helpers_test.go
  core/services/keeper/registry_synchronizer_core.go
  core/services/keeper/registry_synchronizer_log_listener.go
  core/services/keeper/registry_synchronizer_process_logs.go
  core/services/keeper/registry_synchronizer_test.go
  core/services/keeper/upkeep_executer_test.go
  core/utils/mailbox.go
Labels: ready for review

#4349 Fix logging in LogBroadcaster
  core/services/log/broadcaster.go
  core/services/log/eth_subscriber.go
Labels: ready for review

#4347 fix head tracker handling of head timeouts
  core/services/head_tracker.go
Labels: ready for review

#4368 mailbox nil protection
  core/services/bulletprooftxmanager/eth_confirmer.go
  core/services/directrequest/delegate.go
  core/services/gasupdater/gas_updater.go
  core/services/head_broadcaster.go
  core/services/head_tracker.go
  core/services/keeper/registry_synchronizer_process_logs.go
  core/services/keeper/upkeep_executer.go
  core/services/log/broadcaster.go
  core/services/offchainreporting/contract_tracker.go
  core/utils/mailbox.go
  core/utils/mailbox_test.go
Labels: ready for review

#4315 Mailbox - log on over capacity
  core/services/head_broadcaster.go
  core/services/keeper/registry_synchronizer_log_listener.go
  core/services/log/broadcaster.go
  core/services/offchainreporting/contract_tracker.go
Labels: ready for review

#4382 Disable job specs v1 pipeline on Optimism
  core/services/chainlink/application.go
  core/services/job_subscriber.go
  core/services/run_executor.go
  core/services/run_manager.go
  core/services/run_queue.go
  core/store/orm/config.go
  core/store/orm/schema.go
  core/store/presenters/presenters.go
  core/web/job_specs_controller.go
  docs/CHANGELOG.md
  go.sum
Labels: ready for review

#4334 Generate random libp2p port if unset
  core/logger/default.go
  core/store/orm/config.go
  core/store/presenters/presenters.go
Labels: ready for review

#4389 Prune old eth_txes
  core/cmd/local_client_test.go
  core/internal/cltest/cltest.go
  core/internal/cltest/factories.go
  core/services/bulletprooftxmanager/eth_confirmer.go
  core/services/bulletprooftxmanager/mocks/reaper_config.go
  core/services/bulletprooftxmanager/reaper.go
  core/services/bulletprooftxmanager/reaper_test.go
  core/services/cron/cron_test.go
  core/services/eth/null_client.go
  core/store/orm/config.go
  core/store/orm/config_reader.go
  core/store/orm/orm.go
  core/store/orm/orm_test.go
  core/store/orm/schema.go
  core/web/config_controller_test.go
  docs/CHANGELOG.md
Labels: ready for review

#4374 Operator: Transfer, Accept and Deploy Forwarder📞
  core/internal/gethwrappers/generated/operator_wrapper/operator_wrapper.go
  core/internal/gethwrappers/generation/generated-wrapper-dependency-versions-do-not-edit.txt
  evm-contracts/src/v0.7/dev/Operator.sol
  evm-contracts/src/v0.7/dev/OperatorForwarder.sol
  evm-contracts/src/v0.7/interfaces/OperatorInterface.sol
  evm-contracts/test/v0.7/Operator.test.ts
Labels: ready for review

#4384 HeadTracker sampled heads
  core/services/bulletprooftxmanager/eth_confirmer.go
  core/services/chainlink/application.go
  core/services/fluxmonitor/flux_monitor_simulated_blockchain_test.go
  core/services/gasupdater/gas_updater.go
  core/services/head_tracker.go
  core/services/head_tracker_test.go
  core/services/log/broadcaster.go
  core/services/prom_reporter.go
  core/services/prom_reporter_test.go
  core/store/orm/config.go
  core/store/orm/schema.go
  docs/CHANGELOG.md
  integration/cypress/integration/createAndRunJob.spec.ts
Labels: performance, ready for review

#4379 Tests for empty receives depending on capacity.
  core/utils/mailbox_test.go
Labels: ready for review

#4308 Backfill logs in batches
  core/services/log/broadcaster.go
  core/services/log/broadcaster_test.go
  core/services/log/eth_subscriber.go
  core/services/log/helpers_test.go
Labels: ready for review

#4421 xDai default values + add EthMinGasPriceDefault option (more xDai compat)
  core/internal/cltest/cltest.go
  core/services/gasupdater/chain_specific.go
  core/services/gasupdater/gas_updater.go
  core/services/gasupdater/gas_updater_test.go
  core/services/gasupdater/mocks/config.go
  core/store/orm/config.go
  core/store/orm/config_internal_test.go
  core/store/orm/config_test.go
  core/store/orm/schema.go
  docs/CHANGELOG.md
Labels: ready for review

#4423 Allow offchain reporting jobs that have 'latest round requested' to be deleted
  core/services/offchainreporting/database_test.go
  core/store/migrations/0027_cascade_ocr_latest_round_request.go
  docs/CHANGELOG.md
Labels: ready for review

#4407 Feature/ch7200 VRF backoff confirmations upon repeat requests
  core/internal/features_test.go
  core/logger/default.go
  core/services/run_manager.go
  core/testdata/testspecs/v1_specs.go
Labels: ready for review

#4397 FM bugfix: Always initialize idle timer
  core/services/fluxmonitor/flux_monitor.go
  core/services/fluxmonitor/flux_monitor_test.go
  core/services/fluxmonitorv2/poll_manager.go
  core/services/fluxmonitorv2/poll_manager_test.go
Labels: ready for review

#4422 Feature/ch7211: VRF jpv2 crud
  core/adapters/random.go
  core/adapters/random_test.go
  core/cmd/jobs_commands.go
  core/cmd/jobs_commands_test.go
  core/cmd/local_client_vrf.go
  core/cmd/local_client_vrf_test.go
  core/internal/cltest/vrf.go
  core/internal/cltest/vrf/vrf.go
  core/services/chainlink/application.go
  core/services/job/models.go
  core/services/job/orm.go
  core/services/pipeline/common.go
  core/services/pipeline/task.vrf.go
  core/services/signatures/secp256k1/public_key.go
  core/services/vrf/delegate.go
  core/services/vrf/doc.go
  core/services/vrf/models.go
  core/services/vrf/orm.go
  core/services/vrf/private_key.go
  core/services/vrf/private_key_test.go
  core/services/vrf/public_key_test.go
  core/services/vrf/seed.go
  core/services/vrf/serialization_test.go
  core/services/vrf/validate.go
  core/services/vrf/validate_test.go
  core/services/vrf/vrf_key_store.go
  core/services/vrf/vrf_key_store_db.go
  core/services/vrf/vrf_key_store_test.go
  core/services/vrf/vrf_simulate_blockchain_test.go
  core/store/migrations/0028_vrf_v2.go
  core/store/models/vrf_coordinator_interface_test.go
  core/store/models/vrfkey/serialization.go
  core/store/orm/orm.go
  core/store/store.go
  core/testdata/testspecs/v2_specs.go
  core/web/jobs_controller.go
  core/web/jobs_controller_test.go
  core/web/presenters/job.go
  core/web/presenters/job_test.go
Labels: ready for review

#4438 cli: Add chainlink node db migrate
  core/cmd/app.go
  core/cmd/local_client.go
  core/store/migrations/migrate.go
  docs/CHANGELOG.md
Labels: ready for review

#4301 ValidatorProxy extra additions
  .prettierignore
  evm-contracts/src/v0.8/dev/ValidatorProxy.sol
  evm-contracts/src/v0.8/interfaces/TypeAndVersionInterface.sol
  evm-contracts/src/v0.8/tests/MockAggregatorValidator.sol
  evm-contracts/test/v0.8/ValidatorProxy.test.js
Labels: ready for review

#4435 Database backup directory should be configurable
  core/services/periodicbackup/backup.go
  core/services/periodicbackup/backup_test.go
  core/store/orm/config.go
  core/store/orm/schema.go
  docs/CHANGELOG.md
Labels: ready for review

#4447 Refactor KeyStore, encapsulate all key handling logic inside
  core/adapters/eth_tx.go
  core/cmd/eth_keys_commands.go
  core/cmd/eth_keys_commands_test.go
  core/cmd/key_store_authenticator.go
  core/cmd/key_store_authenticator_test.go
  core/cmd/local_client.go
  core/cmd/local_client_test.go
  core/cmd/remote_client_test.go
  core/internal/cltest/cltest.go
  core/internal/cltest/factories.go
  core/internal/features_test.go
  core/internal/mocks/flags.go
  core/internal/mocks/flux_aggregator.go
  core/internal/mocks/key_store_interface.go
  core/services/balance_monitor.go
  core/services/bulletprooftxmanager/bulletprooftxmanager.go
  core/services/bulletprooftxmanager/eth_broadcaster.go
  core/services/bulletprooftxmanager/eth_broadcaster_test.go
  core/services/bulletprooftxmanager/eth_confirmer.go
  core/services/bulletprooftxmanager/eth_confirmer_test.go
  core/services/bulletprooftxmanager/nonce_syncer.go
  core/services/bulletprooftxmanager/nonce_syncer_test.go
  core/services/chainlink/application.go
  core/services/fluxmonitor/flux_monitor.go
  core/services/fluxmonitor/flux_monitor_simulated_blockchain_test.go
  core/services/fluxmonitorv2/contract_submitter.go
  core/services/fluxmonitorv2/delegate.go
  core/services/fluxmonitorv2/flux_monitor.go
  core/services/fluxmonitorv2/flux_monitor_test.go
  core/services/fluxmonitorv2/integrations_test.go
  core/services/fluxmonitorv2/key_store.go
  core/services/fluxmonitorv2/key_store_test.go
  core/services/fluxmonitorv2/mocks/key_store_interface.go
  core/services/keeper/integration_test.go
  core/services/postgres/transaction.go
  core/services/run_manager_test.go
  core/services/validators.go
  core/services/validators_test.go
  core/services/vrf/vrf_coordinator_solidity_crosscheck_test.go
  core/store/key_store.go
  core/store/key_store_test.go
  core/store/migrations/0030_drop_keys_last_used.go
  core/store/models/address.go
  core/store/models/eth_test.go
  core/store/models/key.go
  core/store/orm/config.go
  core/store/orm/config_reader.go
  core/store/orm/orm.go
  core/store/orm/orm_test.go
  core/store/store.go
  core/store/store_test.go
  core/web/eth_keys_controller.go
  core/web/eth_keys_controller_test.go
  core/web/migrate_controller.go
  core/web/presenters/eth_key.go
  core/web/presenters/eth_key_test.go
  docs/CHANGELOG.md
Labels: ready for review

#4471 FMv2 - retry timer stopping change and logs improvements
  core/services/fluxmonitorv2/flux_monitor.go
  core/services/fluxmonitorv2/flux_monitor_test.go
  core/services/fluxmonitorv2/poll_manager.go
  core/utils/backoff_ticker.go
Labels: ready for review

#4473 Chore: contracts/ directory housekeeping
  .github/workflows/continuous-integration-workflow.yml
  CODEOWNERS
  GNUmakefile
  README.md
  contracts/hardhat.config.js
  contracts/scripts/native_solc8_compile
  contracts/src/v0.8/dev/Chainlink.sol
  contracts/src/v0.8/dev/ChainlinkClient.sol
  contracts/src/v0.8/dev/ConfirmedOwner.sol
  contracts/src/v0.8/dev/VRFConsumerBase.sol
  contracts/src/v0.8/dev/VRFRequestIDBase.sol
  contracts/src/v0.8/dev/ValidatorProxy.sol
  contracts/src/v0.8/interfaces/AggregatorInterface.sol
  contracts/src/v0.8/interfaces/AggregatorV2V3Interface.sol
  contracts/src/v0.8/interfaces/AggregatorV3Interface.sol
  contracts/src/v0.8/interfaces/AggregatorValidatorInterface.sol
  contracts/src/v0.8/interfaces/ChainlinkRequestInterface.sol
  contracts/src/v0.8/interfaces/ENSInterface.sol
  contracts/src/v0.8/interfaces/LinkTokenInterface.sol
  contracts/src/v0.8/interfaces/OperatorInterface.sol
  contracts/src/v0.8/interfaces/OracleInterface.sol
  contracts/src/v0.8/interfaces/PointerInterface.sol
  contracts/src/v0.8/interfaces/TypeAndVersionInterface.sol
  contracts/src/v0.8/tests/MockAggregatorValidator.sol
  contracts/src/v0.8/tests/VRFConsumer.sol
  contracts/src/v0.8/tests/VRFRequestIDBaseTestHelper.sol
  contracts/src/v0.8/vendor/BufferChainlink.sol
  contracts/src/v0.8/vendor/CBORChainlink.sol
  contracts/src/v0.8/vendor/ENSResolver.sol
  contracts/test/v0.8/helpers.js
  core/internal/gethwrappers/generation/compile_contracts.sh
  evm-contracts/hardhat.config.js
  evm-contracts/package.json
  evm-contracts/scripts/native_solc8_compile
  evm-contracts/scripts/native_solc_compile_all
  tools/ci/check_solc_hashes
  yarn.lock
Labels: ready for review
