Repository smartcontractkit/chainlink, pull requests merged in 2021-04, with the labels that each got.

#4133 Add mock oracle contract
  docs/CHANGELOG.md
  evm-contracts/src/v0.6/tests/MockOracle.sol
Labels: ready for review

#4153 Correct logging when setting oracle address in Flux Monitor
  core/services/fluxmonitor/flux_monitor.go
  core/services/fluxmonitorv2/flux_monitor.go
Labels: ready for review

#4152 Fixes jobs without a DAG not appearing in jobs list CLI command
  core/cmd/presenters.go
  core/cmd/presenters_test.go
  core/cmd/renderer.go
Labels: ready for review

#4156 Remove code splitting in operator ui
  operator_ui/package.json
  operator_ui/src/Layout.tsx
  operator_ui/src/Private.tsx
  operator_ui/src/pages/Dashboards/Index.tsx
  operator_ui/src/pages/Jobs/Show.tsx
  yarn.lock
Labels: ready for review

#4167 Render the keeper specs on jobs page and the definition in show
  core/cmd/presenters.go
  core/web/presenters/job.go
  operator_ui/@types/core/store/models.d.ts
  operator_ui/src/pages/Jobs/RegionalNav.tsx
  operator_ui/src/pages/Jobs/Show.tsx
  operator_ui/src/pages/Jobs/generateJobSpecDefinition.test.ts
  operator_ui/src/pages/Jobs/generateJobSpecDefinition.ts
  operator_ui/src/pages/Jobs/sharedTypes.ts
  operator_ui/src/pages/JobsIndex/JobV2Row.tsx
  operator_ui/src/pages/JobsIndex/JobsIndex.test.tsx
  operator_ui/src/pages/JobsIndex/JobsIndex.tsx
  operator_ui/support/factories/jobSpecV2.ts
  operator_ui/support/factories/jsonApiJobs.ts
Labels: ready for review

#4086 Move EthKey presenter to web and refactor
  core/cmd/remote_client.go
  core/cmd/remote_client_test.go
  core/cmd/renderer.go
  core/store/models/key.go
  core/store/presenters/presenters.go
  core/web/eth_keys_controller.go
  core/web/eth_keys_controller_test.go
  core/web/presenters/eth_key.go
  core/web/presenters/eth_key_test.go
  core/web/presenters/jsonapi.go
Labels: ready for review

#4131 Solidity 0.7 VRF Consumer Contracts 7️⃣
  evm-contracts/src/v0.7/dev/VRFConsumerBase.sol
  evm-contracts/src/v0.7/dev/VRFRequestIDBase.sol
Labels: ready for review

#4181 Publish new @chainlink/contracts version
  evm-contracts/README.md
  evm-contracts/package.json
Labels: ready for review

#4174 display missing VRF attributes in frontend
  core/store/presenters/presenters.go
Labels: ready for review

#4173 Min confirmations required in VRF job specs
  core/internal/testdata/randomness_job.json
  core/services/testdata/randomness_job.json
  core/services/validators.go
  core/services/validators_test.go
  core/services/vrf/vrf_coordinator_solidity_crosscheck_test.go
  core/services/vrf/vrf_simulate_blockchain_test.go
Labels: ready for review

#4117 Retry polling when an idle timer fails
  core/services/fluxmonitorv2/flux_monitor.go
  core/services/fluxmonitorv2/flux_monitor_test.go
  core/services/fluxmonitorv2/helpers_test.go
  core/services/fluxmonitorv2/poll_manager.go
  core/services/fluxmonitorv2/poll_manager_test.go
  core/utils/backoff_ticker.go
  core/utils/backoff_ticker_test.go
Labels: 0.10.5, ready for review

#4191 Trim whitespace from search term before filtering in UI Jobs
  operator_ui/src/pages/JobsIndex/JobsIndex.test.tsx
  operator_ui/src/pages/JobsIndex/JobsIndex.tsx
Labels: ready for review

#4189 Fix Invalid JSON misleading frontend error
  operator_ui/src/pages/Bridges/Show.tsx
  operator_ui/src/pages/Jobs/New.tsx
  operator_ui/src/pages/Keys/AccountAddresses.tsx
  operator_ui/src/pages/Keys/OcrKeys.tsx
  operator_ui/src/pages/Keys/P2PKeys.tsx
  operator_ui/src/theme.ts
Labels: ready for review

#4203 Refactor PollManager to determine whether an initial poll should be made
  core/services/fluxmonitorv2/flux_monitor.go
  core/services/fluxmonitorv2/flux_monitor_test.go
  core/services/fluxmonitorv2/helpers_test.go
  core/services/fluxmonitorv2/poll_manager.go
  core/services/fluxmonitorv2/poll_manager_test.go
Labels: ready for review

#4184 Improve re-org logging
  core/internal/cltest/cltest.go
  core/internal/features_test.go
  core/services/bulletprooftxmanager/eth_confirmer.go
  core/services/head_tracker_test.go
  core/store/models/eth.go
Labels: 0.10.5

#4213 Bridges now use a presenter in the API
  core/cmd/bridge_commands.go
  core/cmd/bridge_commands_test.go
  core/cmd/remote_client.go
  core/cmd/remote_client_test.go
  core/cmd/renderer.go
  core/cmd/renderer_test.go
  core/internal/cltest/cltest.go
  core/internal/features_test.go
  core/store/models/bridge_type.go
  core/web/bridge_types_controller.go
  core/web/bridge_types_controller_test.go
  core/web/presenters/bridges.go
  core/web/presenters/bridges_test.go
Labels: ready for review

#4143 Add rate limiting to gui assets endpoint
  core/web/gui_assets_test.go
  core/web/router.go
  operator_ui/webpack.config.js
Labels: ready for review

#4190 Compress GUI assets
  operator_ui/@types/react-time-ago.d.ts
  operator_ui/package.json
  operator_ui/src/components/Jobs/RecentlyCreated.test.js
  operator_ui/src/components/TimeAgo.tsx
  operator_ui/src/pages/Jobs/Show.test.tsx
  operator_ui/webpack.config.js
  operator_ui/webpack.dev.js
  operator_ui/webpack.prod.js
  yarn.lock
Labels: ready for review

#4221 P2P keys now use a presenter in the API
  core/cmd/p2p_keys_commands.go
  core/cmd/p2p_keys_commands_test.go
  core/cmd/renderer.go
  core/store/models/p2pkey/p2p_key.go
  core/web/p2p_keys_controller.go
  core/web/p2p_keys_controller_test.go
  core/web/presenters/p2p_key.go
  core/web/presenters/p2p_key_test.go
Labels: ready for review

#4238 Do not panic when adding a job if ETH_DISABLED=true
  core/internal/fixtures/web/ethlog_noop_job.json
  core/internal/gethwrappers/go_generate_test.go
  core/services/job_subscriber.go
  core/web/job_specs_controller_test.go
  core/web/jobs_controller_test.go
Labels: ready for acceptance

#4234 OCR keys now use a presenter in the API
  core/cmd/ocr_keys_commands.go
  core/cmd/ocr_keys_commands_test.go
  core/cmd/renderer.go
  core/store/models/ocrkey/key_bundle.go
  core/web/ocr_keys_controller.go
  core/web/ocr_keys_controller_test.go
  core/web/presenters/ocr_keys.go
  core/web/presenters/ocr_keys_test.go
Labels: ready for review

#4108 Log broadcaster re-architecture and variable number of confirmations
  core/cmd/testscript/wsconnect/main.go
  core/internal/cltest/cltest.go
  core/internal/cltest/factories.go
  core/internal/cltest/fixtures.go
  core/internal/cltest/simulated_backend.go
  core/internal/features_test.go
  core/internal/gethwrappers/utils.go
  core/services/chainlink/application.go
  core/services/directrequest/delegate.go
  core/services/directrequest/delegate_test.go
  core/services/fluxmonitor/flux_monitor.go
  core/services/fluxmonitor/flux_monitor_test.go
  core/services/fluxmonitorv2/flux_monitor.go
  core/services/fluxmonitorv2/flux_monitor_test.go
  core/services/fluxmonitorv2/integrations_test.go
  core/services/head_tracker.go
  core/services/job_subscriber_test.go
  core/services/keeper/orm.go
  core/services/keeper/orm_test.go
  core/services/keeper/registry_synchronizer_core.go
  core/services/keeper/registry_synchronizer_process_logs.go
  core/services/keeper/registry_synchronizer_sync.go
  core/services/keeper/registry_synchronizer_test.go
  core/services/log/broadcast.go
  core/services/log/broadcaster.go
  core/services/log/broadcaster_test.go
  core/services/log/eth_subscriber.go
  core/services/log/helpers_test.go
  core/services/log/mocks/broadcast.go
  core/services/log/mocks/broadcaster.go
  core/services/log/mocks/listener.go
  core/services/log/mocks/orm.go
  core/services/log/orm.go
  core/services/log/pool.go
  core/services/log/registrations.go
  core/services/offchainreporting/contract_tracker.go
  core/services/offchainreporting/contract_tracker_test.go
  core/services/subscription.go
  core/services/subscription_test.go
  core/store/models/eth.go
  core/store/models/log_events.go
  core/store/models/log_events_test.go
  core/store/models/parse_randomness_request.go
  core/store/models/vrf_coordinator_interface.go
  core/store/models/vrf_coordinator_interface_test.go
Labels: ready for acceptance

#4227 Optimize the ETH Confirmer Receipt Checking
  core/internal/cltest/cltest.go
  core/internal/cltest/factories.go
  core/internal/cltest/simulated_backend.go
  core/internal/features_test.go
  core/internal/mocks/client.go
  core/internal/mocks/geth_client.go
  core/services/bulletprooftxmanager/eth_confirmer.go
  core/services/bulletprooftxmanager/eth_confirmer_test.go
  core/services/bulletprooftxmanager/eth_resender_test.go
  core/services/eth/client.go
  core/services/eth/null_client.go
  core/store/models/eth.go
Labels: ready for review

#4211 Disable Auto Associations across the entire core project
  core/adapters/eth_tx.go
  core/adapters/eth_tx_internal_test.go
  core/adapters/multiply.go
  core/internal/cltest/factories.go
  core/services/bulletprooftxmanager/bulletprooftxmanager.go
  core/services/bulletprooftxmanager/eth_broadcaster.go
  core/services/bulletprooftxmanager/eth_confirmer.go
  core/services/directrequest/delegate.go
  core/services/directrequest/delegate_test.go
  core/services/fluxmonitorv2/pipeline.go
  core/services/job/orm.go
  core/services/job/runner_integration_test.go
  core/services/job/spawner_test.go
  core/services/keeper/orm_test.go
  core/services/offchainreporting/data_source.go
  core/services/pipeline/orm.go
  core/store/orm/orm.go
  core/store/orm/orm_test.go
  core/utils/utils.go
  core/web/service_agreements_controller_test.go
Labels: ready for acceptance

#4265 `ValidatorProxy` contract 🔀 (& Hardhat support for v0.8 contracts 👷‍♂️👀)
  .eslintignore
  .github/workflows/continuous-integration-workflow.yml
  belt/package.json
  belt/src/services/utils.ts
  evm-contracts/.gitignore
  evm-contracts/app.config.json
  evm-contracts/hardhat.config.js
  evm-contracts/package.json
  evm-contracts/src/v0.8/dev/ConfirmedOwner.sol
  evm-contracts/src/v0.8/dev/ValidatorProxy.sol
  evm-contracts/src/v0.8/interfaces/AggregatorValidatorInterface.sol
  evm-contracts/src/v0.8/tests/MockAggregatorValidator.sol
  evm-contracts/test/v0.8/ValidatorProxy.test.js
  evm-contracts/test/v0.8/helpers.js
  evm-contracts/tsconfig.test.json
  integration-scripts/package.json
  integration/apocalypse/package-lock.json
  tools/ci/solidity_test_hardhat
  yarn.lock
Labels: ready for review

#4270 Log broadcaster backfill from latest head from DB
  core/services/log/broadcaster.go
  core/services/log/broadcaster_test.go
  core/services/log/eth_subscriber.go
  core/services/log/helpers_test.go
Labels: ready for review

#4260 Make UpkeepExecuter more robust against missed heads
  core/services/fluxmonitor/flux_monitor_test.go
  core/services/keeper/delegate.go
  core/services/keeper/orm.go
  core/services/keeper/orm_test.go
  core/services/keeper/upkeep_executer.go
  core/services/keeper/upkeep_executer_test.go
Labels: ready for review

#4263 Add support for HTTP primary eth node
  core/cmd/client.go
  core/cmd/client_test.go
  core/cmd/eth_keys_commands_test.go
  core/cmd/local_client_test.go
  core/cmd/remote_client_test.go
  core/cmd/renderer_test.go
  core/cmd/testscript/wsconnect/main.go
  core/internal/cltest/cltest.go
  core/internal/features_test.go
  core/internal/mocks/geth_client.go
  core/internal/mocks/rpc_client.go
  core/services/chainlink/application.go
  core/services/chainlink/application_test.go
  core/services/directrequest/delegate_test.go
  core/services/eth/client.go
  core/services/eth/client_test.go
  core/services/eth/errors.go
  core/services/eth/errors_test.go
  core/services/eth/node.go
  core/services/eth/secondary_node.go
  core/services/job/runner_integration_test.go
  core/services/job/spawner_test.go
  core/services/job_subscriber_test.go
  core/services/run_manager_test.go
  core/services/subscription_test.go
  core/store/models/log_events_test.go
  core/store/orm/config.go
  core/store/orm/schema.go
  core/store/store_test.go
  core/web/config_controller_test.go
  core/web/cors_test.go
  core/web/eth_keys_controller_test.go
  core/web/external_initiators_controller_test.go
  core/web/gui_assets_test.go
  core/web/job_runs_controller_test.go
  core/web/job_spec_errors_controller_test.go
  core/web/job_specs_controller_test.go
  core/web/jobs_controller_test.go
  core/web/log_controller_test.go
  core/web/ocr_keys_controller_test.go
  core/web/ping_controller_test.go
  core/web/pipeline_runs_controller_test.go
  core/web/router_test.go
  core/web/service_agreements_controller_test.go
  core/web/sessions_controller_test.go
  core/web/user_controller_test.go
  docs/CHANGELOG.md
Labels: ready for review

#4294 Make keeper use EthMaxUnconfirmedTransactions
  core/services/keeper/delegate.go
  core/services/keeper/orm.go
  core/services/keeper/orm_test.go
  core/services/keeper/upkeep_executer.go
  core/services/keeper/upkeep_executer_test.go
Labels: ready for review

#4287 Added evm-contracts codeowners🧹
  CODEOWNERS
Labels: ready for review

#4259 Clean up cmd to use the TableRenderer interface
  core/cmd/bridge_commands.go
  core/cmd/bridge_commands_test.go
  core/cmd/eth_keys_commands.go
  core/cmd/eth_keys_commands_test.go
  core/cmd/jobs_commands.go
  core/cmd/jobs_commands_test.go
  core/cmd/local_client_vrf.go
  core/cmd/local_client_vrf_test.go
  core/cmd/p2p_keys_commands.go
  core/cmd/p2p_keys_commands_test.go
  core/cmd/remote_client.go
  core/cmd/remote_client_test.go
  core/cmd/renderer.go
  core/cmd/renderer_test.go
  core/cmd/transaction_commands.go
  core/cmd/transaction_commands_test.go
  core/web/presenters/eth_key.go
  core/web/presenters/eth_key_test.go
Labels: ready for review

#4261 Serve gzipped static assets when Content-Encoding is provided and matches
  core/internal/fixtures/operator_ui/dist/main.js.gz
  core/web/box.go
  core/web/box_test.go
  core/web/gui_assets_test.go
  core/web/middleware.go
  core/web/router.go
Labels: ready for review

#4288 Upgrade gethwrapper solc from `0.8.3` to `0.8.4`🧗‍♂️
  evm-contracts/scripts/check_solc_hashes
  evm-contracts/scripts/native_solc8_compile
  evm-contracts/scripts/native_solc_compile_all
Labels: ready for review

#4313 TypeAndVersionInterface Contract
  evm-contracts/src/v0.7/interfaces/TypeAndVersionInterface.sol
Labels: ready for review

#4248 Cron & Web V2 Support Added to Operator UI
  operator_ui/@types/core/store/models.d.ts
  operator_ui/src/actionCreators.ts
  operator_ui/src/api/v2/jobs.ts
  operator_ui/src/pages/Jobs/RegionalNav.tsx
  operator_ui/src/pages/Jobs/Runs/Show.tsx
  operator_ui/src/pages/Jobs/Show.tsx
  operator_ui/src/pages/Jobs/generateJobSpecDefinition.test.ts
  operator_ui/src/pages/Jobs/generateJobSpecDefinition.ts
  operator_ui/src/pages/Jobs/sharedTypes.ts
  operator_ui/src/pages/Jobs/utils.ts
  operator_ui/src/pages/JobsIndex/JobV2Row.tsx
  operator_ui/src/pages/JobsIndex/JobsIndex.test.tsx
  operator_ui/src/pages/JobsIndex/JobsIndex.tsx
  operator_ui/support/factories/jobSpecV2.ts
  operator_ui/support/factories/jsonApiJobs.ts
Labels: do-not-merge-yet, making changes

#4244 Log Broadcaster filtering by topic
  core/internal/cltest/factories.go
  core/services/directrequest/delegate.go
  core/services/log/broadcaster.go
  core/services/log/broadcaster_test.go
  core/services/log/helpers_test.go
  core/services/log/registrations.go
Labels: ready for review

#4102 Configurable ackage-specific log levels
  core/cmd/app.go
  core/cmd/remote_client.go
  core/cmd/remote_client_test.go
  core/cmd/renderer.go
  core/internal/cltest/cltest.go
  core/internal/mocks/application.go
  core/logger/logger.go
  core/logger/model.go
  core/logger/orm.go
  core/services/chainlink/application.go
  core/services/fluxmonitor/flux_monitor.go
  core/services/head_broadcaster_test.go
  core/services/head_tracker.go
  core/services/head_tracker_test.go
  core/store/migrations/0025_create_log_config_table.go
  core/store/migrations/migrate_test.go
  core/web/log_controller.go
  core/web/log_controller_test.go
  core/web/presenters/log.go
Labels: ready for acceptance
