Repository smartcontractkit/chainlink, pull requests merged in 2021-11, with the labels that each got.

#5322 core/cmd: help text typos
  core/cmd/app.go
  core/main_test.go
Labels: ready for review

#5323 Add UpdateFeedsManager GQL mutation
  core/web/resolver/feeds_manager.go
  core/web/resolver/feeds_manager_test.go
  core/web/resolver/mutation.go
  core/web/resolver/query.go
  core/web/schema/schema.graphql
  core/web/schema/type/feeds_manager.graphql
Labels: ready for review

#5346 Authenticate GQL requests at the resolver level
  core/web/auth/auth.go
  core/web/auth/gql.go
  core/web/auth/gql_test.go
  core/web/resolver/auth.go
  core/web/resolver/bridge_test.go
  core/web/resolver/chain_test.go
  core/web/resolver/feeds_manager_test.go
  core/web/resolver/mutation.go
  core/web/resolver/query.go
  core/web/resolver/resolver_test.go
  core/web/router.go
Labels: ready for review

#5319 Fixed LOG_LEVEL behavior
  core/chains/evm/config/mocks/chain_scoped_config.go
  core/config/general_config.go
  core/config/orm_test.go
  core/internal/mocks/application.go
  core/internal/testutils/configtest/general_config.go
  core/services/chainlink/application.go
  core/web/log_controller.go
  core/web/log_controller_test.go
  core/web/presenters/log.go
  docs/CHANGELOG.md
  operator_ui/@types/core/store/models.d.ts
  operator_ui/src/pages/Configuration/LoggingCard.test.tsx
  operator_ui/src/pages/Configuration/LoggingCard.tsx
  operator_ui/support/factories/jsonApiLogConfig.ts
Labels: ready for review

#5347 Fixes edit job spec button not displaying for a pending proposal
  operator_ui/src/pages/JobProposal/JobProposalScreen.tsx
Labels: ready for review

#5296 Duplicated Jobs should not persist variables from the environment
  core/cmd/jobs_commands_test.go
  core/cmd/p2p_keys_commands_test.go
  core/cmd/remote_client_test.go
  core/internal/cltest/cltest.go
  core/internal/cltest/factories.go
  core/internal/features_test.go
  core/internal/testutils/configtest/general_config.go
  core/services/chainlink/application.go
  core/services/directrequest/delegate.go
  core/services/feeds/service.go
  core/services/feeds/service_test.go
  core/services/job/helpers_test.go
  core/services/job/job_orm_test.go
  core/services/job/job_pipeline_orm_integration_test.go
  core/services/job/models.go
  core/services/job/orm.go
  core/services/job/runner_integration_test.go
  core/services/job/spawner.go
  core/services/job/spawner_test.go
  core/services/keystore/keys/p2pkey/peer_id.go
  core/services/keystore/master.go
  core/services/keystore/mocks/master.go
  core/services/keystore/mocks/p2p.go
  core/services/keystore/p2p.go
  core/services/keystore/p2p_test.go
  core/services/offchainreporting/common.go
  core/services/offchainreporting/delegate.go
  core/services/offchainreporting/peer_wrapper.go
  core/services/offchainreporting/peer_wrapper_test.go
  core/services/offchainreporting/peerstore_test.go
  core/services/offchainreporting/validate.go
  core/services/versioning/orm.go
  core/services/vrf/listener_v1.go
  core/services/vrf/listener_v2.go
  core/sessions/webauthn.go
  core/testdata/testspecs/v2_specs.go
  core/testdata/tomlspecs/ocr-spec-local-test.toml
  core/web/job_proposals_controller.go
  core/web/job_proposals_controller_test.go
  core/web/jobs_controller.go
  core/web/jobs_controller_test.go
  core/web/p2p_keys_controller.go
  core/web/p2p_keys_controller_test.go
  core/web/pipeline_runs_controller_test.go
  core/web/presenters/job.go
  core/web/presenters/job_test.go
  docs/CHANGELOG.md
Labels: S-waiting-on-author

#5352 Running `make install` produces changes on `develop` branch
  GNUmakefile
Labels: ready for review

#5354 core/chains/evm/config: fix races for chainScopedConfig.persistedCfg
  core/chains/evm/config/config.go
  core/chains/evm/config/config_test.go
  core/chains/evm/config/helpers_test.go
Labels: ready for review

#5339 Implements `features` GQL endpoint
  core/config/general_config.go
  core/config/mocks/general_config.go
  core/web/resolver/features.go
  core/web/resolver/features_test.go
  core/web/resolver/query.go
  core/web/resolver/resolver_test.go
  core/web/schema/schema.graphql
  core/web/schema/type/features.graphql
Labels: ready for review, S-waiting-on-author

#5326 Display extra job spec section for values set from env vars
  operator_ui/@types/core/store/models.d.ts
  operator_ui/src/pages/Jobs/JobDefinition.tsx
  operator_ui/src/pages/Jobs/Show.tsx
  operator_ui/src/pages/Jobs/generateJobSpecDefinition.test.ts
  operator_ui/src/pages/Jobs/generateJobSpecDefinition.ts
  operator_ui/src/pages/Jobs/sharedTypes.ts
Labels: ready for review

#5363 Propagating evmChainID in job specs
  core/services/directrequest/validate.go
  core/services/fluxmonitorv2/validate.go
  core/services/job/models.go
  core/web/presenters/job.go
  core/web/presenters/job_test.go
  docs/CHANGELOG.md
  operator_ui/@types/core/store/models.d.ts
  operator_ui/src/pages/Jobs/Show.tsx
  operator_ui/src/pages/Jobs/generateJobSpecDefinition.test.ts
  operator_ui/src/pages/Jobs/generateJobSpecDefinition.ts
  operator_ui/src/pages/Jobs/sharedTypes.ts
Labels: ready for review

#5341 LB should replay unconsumed logs
  core/internal/cltest/cltest.go
  core/services/log/broadcaster.go
  core/services/log/broadcaster_internal_test.go
  core/services/log/broadcaster_test.go
  core/services/log/helpers_internal_test.go
  core/services/log/helpers_test.go
  core/services/log/mocks/orm.go
  core/services/log/orm.go
  core/services/log/orm_test.go
  core/services/log/pool.go
  core/services/log/registrations.go
  core/store/migrate/migrations/0081_unconsumed_log_broadcasts.sql
Labels: ready for review, S-waiting-on-author

#5365 Introduce new locking mode: 'lease'
  core/chains/evm/config/mocks/chain_scoped_config.go
  core/cmd/client.go
  core/cmd/local_client.go
  core/cmd/local_client_test.go
  core/config/general_config.go
  core/config/mocks/general_config.go
  core/config/presenters.go
  core/config/schema.go
  core/config/schema_test.go
  core/gracefulpanic/channel.go
  core/internal/cltest/cltest.go
  core/internal/cltest/mocks.go
  core/internal/cltest/simulated_backend.go
  core/internal/gethwrappers/generated/vrf_coordinator_v2/vrf_coordinator_v2.go
  core/internal/gethwrappers/generation/generated-wrapper-dependency-versions-do-not-edit.txt
  core/internal/mocks/application.go
  core/internal/testutils/configtest/general_config.go
  core/services/bulletprooftxmanager/eth_broadcaster_test.go
  core/services/chainlink/application.go
  core/services/feeds/connection_manager.go
  core/services/fluxmonitorv2/flux_monitor.go
  core/services/offchainreporting/peerstore.go
  core/services/offchainreporting/run_saver.go
  core/services/postgres/advisory_lock.go
  core/services/postgres/event_broadcaster.go
  core/services/postgres/event_broadcaster_test.go
  core/services/postgres/lease_lock.go
  core/services/postgres/lease_lock_test.go
  core/services/postgres/sqlx.go
  core/services/postgres/transaction.go
  core/services/postgres/utils.go
  core/services/vrf/listener_v1.go
  core/services/vrf/listener_v2.go
  core/shutdown/channel.go
  core/shutdown/recover.go
  core/static/static.go
  core/store/migrate/migrations/0082_lease_lock.sql
  docs/CHANGELOG.md
Labels: S-waiting-on-author

#5366 Removes deprecated config ORM struct
  core/chains/evm/config/mocks/chain_scoped_config.go
  core/cmd/client.go
  core/config/general_config.go
  core/config/mocks/general_config.go
  core/config/orm.go
  core/config/orm_test.go
  core/internal/cltest/cltest.go
  core/services/fluxmonitorv2/orm_test.go
  core/services/headtracker/head_broadcaster_test.go
  core/services/job/job_orm_test.go
  core/services/job/job_pipeline_orm_integration_test.go
  core/services/job/runner_integration_test.go
  core/services/job/spawner_test.go
  core/services/keeper/orm_test.go
  core/services/keeper/registry_synchronizer_test.go
  core/services/keeper/upkeep_executer_test.go
Labels: ready for review

#5360 Dependabot cascade
  .github/workflows/codeql-analysis.yml
  go.mod
  go.sum
  operator_ui/package.json
  yarn.lock
Labels: S-waiting-on-review, merged-by-homu

#5369 bump golangci-lint to 1.43.0
  .github/workflows/golangci-lint.yml
  core/internal/cltest/simulated_backend.go
  core/services/bulletprooftxmanager/eth_confirmer.go
  core/services/offchainreporting/peerstore.go
Labels: ready for review

#5355 Refactor ui tests to use @testing-library
  operator_ui/jest.config.js
  operator_ui/jest.setup.js
  operator_ui/package.json
  operator_ui/src/PrivateRoute.test.js
  operator_ui/src/components/BaseLink.test.tsx
  operator_ui/src/components/Cards/TokenBalance.test.tsx
  operator_ui/src/components/Dashboards/Activity.test.tsx
  operator_ui/src/components/Jobs/RecentlyCreated.test.js
  operator_ui/src/hooks/useErrorHandler.test.tsx
  operator_ui/src/hooks/useLoadingPlaceholder.test.tsx
  operator_ui/src/pages/Bridges/Index.test.js
  operator_ui/src/pages/Bridges/Show.test.tsx
  operator_ui/src/pages/Configuration/Index.test.tsx
  operator_ui/src/pages/Configuration/LoggingCard.test.tsx
  operator_ui/src/pages/Configuration/LoggingCard.tsx
  operator_ui/src/pages/Dashboards/Index.test.js
  operator_ui/src/pages/Jobs/Errors.test.tsx
  operator_ui/src/pages/Jobs/JobDefinition.test.tsx
  operator_ui/src/pages/Jobs/JobDefinition.tsx
  operator_ui/src/pages/Jobs/New.test.tsx
  operator_ui/src/pages/Jobs/New.tsx
  operator_ui/src/pages/Jobs/RecentRuns.test.tsx
  operator_ui/src/pages/Jobs/Runs.test.tsx
  operator_ui/src/pages/Jobs/Runs/Overview/PipelineJobRunOverview.test.tsx
  operator_ui/src/pages/Jobs/Runs/RegionalNav.test.tsx
  operator_ui/src/pages/Jobs/Runs/Show.test.tsx
  operator_ui/src/pages/Jobs/Runs/StatusCard.test.tsx
  operator_ui/src/pages/Jobs/Show.test.tsx
  operator_ui/src/pages/JobsIndex/JobsIndex.test.tsx
  operator_ui/src/pages/Keys/AccountAddresses.test.tsx
  operator_ui/src/pages/Keys/CSAKeys.test.tsx
  operator_ui/src/pages/Keys/CSAKeys.tsx
  operator_ui/src/pages/Keys/Delete.test.tsx
  operator_ui/src/pages/Keys/Index.test.tsx
  operator_ui/src/pages/Keys/KeyBundle.test.tsx
  operator_ui/src/pages/Keys/OcrKeys.test.tsx
  operator_ui/src/pages/Keys/P2PKeys.test.tsx
  operator_ui/src/pages/Notifications.test.js
  operator_ui/src/pages/SignIn.test.js
  operator_ui/support/test-helpers/StoreAndMemoryRouter.tsx
  operator_ui/support/test-helpers/clickFirstPage.js
  operator_ui/support/test-helpers/clickLastPage.js
  operator_ui/support/test-helpers/clickNextPage.js
  operator_ui/support/test-helpers/clickPreviousPage.js
  operator_ui/support/test-helpers/fillIn.js
  operator_ui/support/test-helpers/formikFillIn.js
  operator_ui/support/test-helpers/mountWithTheme.js
  operator_ui/support/test-helpers/mountWithinRouter.tsx
  operator_ui/support/test-helpers/mountWithinStoreAndRouter.tsx
  operator_ui/support/test-helpers/renderWithinRouter.tsx
  operator_ui/support/test-helpers/syncFetch.js
  operator_ui/support/test-utils.tsx
  package.json
  yarn.lock
Labels: ready for review, S-waiting-on-author

#5358 Implements GQL endpoints for CSA Keys
  core/web/resolver/csa_keys.go
  core/web/resolver/csa_keys_test.go
  core/web/resolver/mutation.go
  core/web/resolver/query.go
  core/web/resolver/resolver_test.go
  core/web/schema/schema.graphql
  core/web/schema/type/csa_keys.graphql
Labels: ready for review

#5380 Adds GQL queries to fetch a page of jobs and a single job by id
  core/web/resolver/job.go
  core/web/resolver/job_error.go
  core/web/resolver/job_error_test.go
  core/web/resolver/job_test.go
  core/web/resolver/query.go
  core/web/resolver/resolver_test.go
  core/web/resolver/spec.go
  core/web/resolver/spec_test.go
  core/web/router.go
  core/web/schema/schema.graphql
  core/web/schema/type/job.graphql
  core/web/schema/type/job_error.graphql
  core/web/schema/type/pagination.graphql
  core/web/schema/type/spec.graphql
Labels: ready for review

#5390 core/logger: PrettyConsole pass through non-numeric timestamps
  core/logger/default.go
  core/logger/logger.go
  core/logger/prettyconsole.go
  go.mod
  go.sum
Labels: ready for review

#5395 WrapRecover: move to inside of loop in FluxMonitor, PeerStore, and VRF listeners; let pipeline panic
  core/services/fluxmonitorv2/flux_monitor.go
  core/services/offchainreporting/peerstore.go
  core/services/offchainreporting/run_saver.go
  core/services/pipeline/runner.go
  core/services/pipeline/runner_test.go
  core/services/postgres/sqlx.go
  core/services/postgres/transaction.go
  core/services/postgres/transaction_manager.go
  core/services/vrf/listener_v1.go
  core/services/vrf/listener_v2.go
  core/store/config/evm_config.go
  core/store/config/general_config.go
Labels: ready for review, S-waiting-on-review

#5406 Fix query args for upsert
  core/chains/evm/legacy.go
Labels: merged-by-homu

#5410 Remove gorm from offchainreporting and eventbroadcaster
  core/services/chainlink/application.go
  core/services/job/runner_integration_test.go
  core/services/offchainreporting/contract_tracker.go
  core/services/offchainreporting/contract_tracker_test.go
  core/services/offchainreporting/delegate.go
  core/services/offchainreporting/peer_wrapper.go
  core/services/offchainreporting/peer_wrapper_test.go
  core/services/offchainreporting/peerstore.go
  core/services/offchainreporting/peerstore_test.go
  core/services/offchainreporting/transmitter.go
  core/services/offchainreporting/transmitter_test.go
  core/services/postgres/event_broadcaster.go
  core/services/postgres/mocks/event_broadcaster.go
Labels: merged-by-homu

#5409 Add test for ClobberNodesFromENV
  core/chains/evm/legacy_test.go
Labels: merged-by-homu

#5411 Remove gorm from keeper, directrequest
  core/internal/cltest/factories.go
  core/services/chainlink/application.go
  core/services/directrequest/delegate.go
  core/services/directrequest/delegate_test.go
  core/services/fluxmonitorv2/flux_monitor.go
  core/services/fluxmonitorv2/flux_monitor_test.go
  core/services/job/job_orm_test.go
  core/services/job/mocks/orm.go
  core/services/job/orm.go
  core/services/job/spawner.go
  core/services/keeper/delegate.go
  core/services/keeper/models.go
  core/services/keeper/orm.go
  core/services/keeper/orm_test.go
  core/services/keeper/registry_synchronizer_process_logs.go
  core/services/keeper/registry_synchronizer_sync.go
  core/services/keeper/registry_synchronizer_test.go
  core/services/keeper/upkeep_executer.go
  core/services/keeper/upkeep_executer_test.go
  core/services/offchainreporting/delegate.go
  core/web/pipeline_job_spec_errors_controller_test.go
Labels: merged-by-homu

#5376 Implement p2p key querying and mutation
  core/services/keystore/ocr.go
  core/services/keystore/p2p.go
  core/services/keystore/vrf.go
  core/web/jobs_controller.go
  core/web/jobs_controller_test.go
  core/web/resolver/mutation.go
  core/web/resolver/ocr_test.go
  core/web/resolver/p2p.go
  core/web/resolver/p2p_test.go
  core/web/resolver/query.go
  core/web/resolver/resolver_test.go
  core/web/schema/schema.graphql
  core/web/schema/type/p2p.graphql
Labels: merged-by-homu

#5412 Unify timeout usage in tests
  core/internal/cltest/cltest.go
  core/internal/features_test.go
  core/services/balance_monitor_test.go
  core/services/bulletprooftxmanager/eth_broadcaster_test.go
  core/services/chainlink/application_test.go
  core/services/eth/client_test.go
  core/services/fluxmonitorv2/flux_monitor_test.go
  core/services/fluxmonitorv2/integrations_test.go
  core/services/headtracker/head_broadcaster_test.go
  core/services/headtracker/head_tracker_test.go
  core/services/job/spawner_test.go
  core/services/keeper/integration_test.go
  core/services/keeper/orm_test.go
  core/services/keeper/registry_synchronizer_test.go
  core/services/keeper/upkeep_executer_test.go
  core/services/log/broadcaster_test.go
  core/services/offchainreporting/config_overrider_test.go
  core/services/postgres/event_broadcaster_test.go
  core/services/synchronization/explorer_client_test.go
  core/services/synchronization/telemetry_ingress_client_test.go
  core/services/vrf/integration_test.go
  core/services/vrf/integration_v2_test.go
  core/sessions/reaper_test.go
  core/utils/sleeper_task_test.go
  core/web/sessions_controller_test.go
Labels: merged-by-homu

#5391 Implement VRF keys GQL queries and mutations
  core/services/keystore/mocks/vrf.go
  core/services/keystore/vrf.go
  core/services/signatures/secp256k1/public_key.go
  core/web/resolver/mutation.go
  core/web/resolver/query.go
  core/web/resolver/resolver_test.go
  core/web/resolver/vrf.go
  core/web/resolver/vrf_test.go
  core/web/schema/schema.graphql
  core/web/schema/type/vrf.graphql
Labels: ready for review, merged-by-homu

#5415 Remove gorm from feeds
  core/services/chainlink/application.go
  core/services/feeds/mocks/orm.go
  core/services/feeds/orm.go
  core/services/feeds/orm_test.go
  core/services/feeds/service.go
  core/services/feeds/service_test.go
  core/services/postgres/mocks/queryer.go
  core/services/postgres/sqlx.go
Labels: merged-by-homu

#5408 Wrap Chains GQL queries on payloads
  core/web/resolver/chain.go
  core/web/resolver/chain_test.go
  core/web/resolver/query.go
  core/web/schema/schema.graphql
  core/web/schema/type/chain.graphql
Labels: merged-by-homu

#5418 CFM-11.5 - Fix typo in core node
  core/services/feeds/service.go
Labels: merged-by-homu

#5416 Remove gorm from cltest/job_factories
  core/internal/cltest/job_factories.go
  core/services/job/job_orm_test.go
  core/services/job/mocks/orm.go
  core/services/job/orm.go
  core/services/webhook/authorizer_test.go
  core/services/webhook/external_initiator_manager_test.go
Labels: merged-by-homu

#5420 chore: remove gorm from transaction controller
  core/services/bulletprooftxmanager/orm.go
  core/web/transactions_controller.go
  core/web/transactions_controller_test.go
Labels: merged-by-homu

#5414 services/vrf: removing gorm
  core/services/chainlink/application.go
  core/services/vrf/delegate.go
  core/services/vrf/delegate_test.go
  core/services/vrf/integration_v2_test.go
  core/services/vrf/listener_v1.go
  core/services/vrf/listener_v2.go
  core/services/vrf/listener_v2_test.go
Labels: merged-by-homu

#5427 chore: remove gorm from pipeline/orm_test
  core/services/pipeline/mocks/orm.go
  core/services/pipeline/orm.go
  core/services/pipeline/orm_test.go
Labels: merged-by-homu

#5428 removing gorm in services/job
  core/internal/cltest/factories.go
  core/services/job/job_orm_test.go
  core/services/job/job_pipeline_orm_integration_test.go
  core/services/job/mocks/orm.go
  core/services/webhook/authorizer_test.go
  core/services/webhook/external_initiator_manager_test.go
  core/web/external_initiators_controller_test.go
Labels: merged-by-homu

#5422 Logger Injection pt. 6
  core/chains/evm/chain.go
  core/cmd/remote_client_test.go
  core/config/general_config.go
  core/internal/cltest/cltest.go
  core/logger/default.go
  core/logger/orm.go
  core/services/chainlink/application.go
  core/services/directrequest/delegate.go
  core/services/gas/block_history_estimator.go
  core/services/gas/block_history_estimator_test.go
  core/services/gas/fixed_price_estimator.go
  core/services/gas/fixed_price_estimator_test.go
  core/services/gas/gas_test.go
  core/services/gas/models.go
  core/services/log/broadcaster.go
  core/services/log/eth_subscriber.go
  core/services/log/registrations.go
  core/services/pipeline/common_http.go
  core/services/pipeline/scheduler.go
  core/services/pipeline/task.bridge.go
  core/services/pipeline/task.http.go
  core/services/pipeline/task_object_params.go
  core/services/postgres/lease_lock.go
  core/services/synchronization/helpers_test.go
  core/services/synchronization/telemetry_ingress_client.go
  core/services/synchronization/telemetry_ingress_client_test.go
  core/utils/http.go
  core/utils/utils.go
  core/web/log_controller.go
  core/web/router.go
Labels: ready for review, merged-by-homu

#5431 Removing gorm from service/job tests
  core/services/job/job_orm_test.go
  core/services/job/runner_integration_test.go
  core/services/job/spawner_test.go
Labels: merged-by-homu

#5429 Remove gorm from a lot of tests
  core/cmd/local_client_test.go
  core/cmd/transaction_commands_test.go
  core/internal/cltest/cltest.go
  core/internal/cltest/factories.go
  core/internal/testutils/pgtest/pgtest.go
  core/services/bulletprooftxmanager/bulletprooftxmanager_test.go
  core/services/bulletprooftxmanager/eth_broadcaster.go
  core/services/bulletprooftxmanager/eth_broadcaster_test.go
  core/services/bulletprooftxmanager/eth_confirmer.go
  core/services/bulletprooftxmanager/eth_confirmer_test.go
  core/services/bulletprooftxmanager/eth_resender_test.go
  core/services/bulletprooftxmanager/nonce_syncer_test.go
  core/services/bulletprooftxmanager/orm.go
  core/services/bulletprooftxmanager/orm_test.go
  core/services/bulletprooftxmanager/reaper_test.go
  core/services/bulletprooftxmanager/strategies_test.go
  core/services/chainlink/application.go
  core/services/pipeline/task.eth_tx.go
  core/services/prom_reporter_test.go
  core/web/transactions_controller_test.go
  core/web/tx_attempts_controller_test.go
Labels: ready for review, merged-by-homu

#5397 Implement Job Proposals GQL queries (when do we get Generics in Go?)
  core/services/feeds/mocks/orm.go
  core/services/feeds/mocks/service.go
  core/services/feeds/orm.go
  core/services/feeds/orm_test.go
  core/services/feeds/service.go
  core/web/loader/feeds_manager.go
  core/web/loader/getters.go
  core/web/loader/loader.go
  core/web/resolver/bridge_test.go
  core/web/resolver/errors.go
  core/web/resolver/job_proposal.go
  core/web/resolver/job_proposal_test.go
  core/web/resolver/mutation.go
  core/web/resolver/query.go
  core/web/schema/schema.graphql
  core/web/schema/type/job_proposal.graphql
Labels: merged-by-homu

#5432 chore: remove gorm from webhook/external_initiator_manager
  core/cmd/client.go
  core/internal/cltest/cltest.go
  core/services/job/job_orm_test.go
  core/services/webhook/external_initiator_manager.go
  core/services/webhook/external_initiator_manager_test.go
Labels: merged-by-homu

#5423 Add owner to examples and tests
  contracts/scripts/native_solc_compile_all
  contracts/src/v0.8/tests/VRFExternalSubOwnerExample.sol
  contracts/src/v0.8/tests/VRFSingleConsumerExample.sol
  core/internal/gethwrappers/generated/vrf_external_sub_owner_example/vrf_external_sub_owner_example.go
  core/internal/gethwrappers/generated/vrf_single_consumer_example/vrf_single_consumer_example.go
  core/internal/gethwrappers/generation/generated-wrapper-dependency-versions-do-not-edit.txt
  core/internal/gethwrappers/go_generate.go
  core/scripts/vrfv2/kovan/main.go
  core/services/vrf/integration_v2_test.go
Labels: merged-by-homu

#5438 Backport 1.1/ci fix
  .github/workflows/continuous-integration-workflow.yml
Labels: ready for review, merged-by-homu

#5439 Remove gorm.io/datatypes dependency
  core/services/bulletprooftxmanager/eth_broadcaster_test.go
  core/services/bulletprooftxmanager/models.go
  core/services/keystore/keys/ethkey/key.go
  core/services/postgres/datatypes/json.go
  core/services/vrf/delegate_test.go
  go.mod
  go.sum
Labels: merged-by-homu

#5386 Fix all of the test flakes 🚀
  CODEOWNERS
  core/internal/testutils/pgtest/pgtest.go
  core/internal/testutils/pgtest/txdb.go
  core/services/headtracker/head_tracker_test.go
Labels: ready for review, merged-by-homu

#5442 Re-enable job claim test
  core/web/jobs_controller_test.go
Labels: merged-by-homu

#5443 remove flakey test: TestMailbox_EmptyReceivesWhenCapacityIsOne
  core/utils/mailbox.go
  core/utils/mailbox_test.go
Labels: merged-by-homu

#5440 Logger Injection pt. 7
  core/cmd/client.go
  core/cmd/client_test.go
  core/cmd/local_client.go
  core/cmd/remote_client_test.go
  core/internal/cltest/cltest.go
  core/logger/default.go
  core/logger/logger.go
  core/main.go
  core/services/balance_monitor.go
  core/services/chainlink/application.go
  core/services/gas/models.go
  core/services/offchainreporting/database.go
  core/services/offchainreporting/database_test.go
  core/services/offchainreporting/delegate.go
  core/services/offchainreporting/helpers_internal_test.go
  core/services/pipeline/runner.go
  core/services/postgres/event_broadcaster.go
  core/services/synchronization/explorer_client.go
  core/services/synchronization/explorer_client_test.go
  core/sessions/reaper.go
  core/sessions/reaper_test.go
  core/utils/files.go
  core/utils/http_allowed_ips.go
  core/utils/json_normalization.go
  core/utils/sleeper_task.go
  core/utils/sleeper_task_test.go
  core/web/middleware.go
  core/web/router.go
Labels: ready for review, merged-by-homu

#5441 Signing address rendered as check-summed address
  core/services/keystore/keys/ocrkey/on_chain_signing_address.go
  core/services/keystore/keys/ocrkey/on_chain_signing_address_test.go
Labels: merged-by-homu

#5413 Implement `UpdateUserPassword` mutation
  core/web/auth/gql.go
  core/web/auth/gql_test.go
  core/web/resolver/auth.go
  core/web/resolver/mutation.go
  core/web/resolver/resolver_test.go
  core/web/resolver/user.go
  core/web/resolver/user_test.go
  core/web/schema/schema.graphql
  core/web/schema/type/user.graphql
Labels: merged-by-homu

#5447 FIX: `increaseTime5Minutes` to increase by 5 instead of 50
  contracts/test/test-helpers/helpers.ts
Labels: ready for review, merged-by-homu

#5449 Fixes a bug causing proposals to be rejected
  core/services/feeds/orm_test.go
  core/services/feeds/service.go
  core/services/feeds/service_test.go
Labels: ready for review, merged-by-homu

#5450 Add lock around txdb stmt close
  core/internal/testutils/pgtest/txdb.go
Labels: merged-by-homu

#5444 Implement job runs as relationship for jobs
  core/services/job/job_orm_test.go
  core/services/job/mocks/orm.go
  core/services/job/orm.go
  core/services/pipeline/models.go
  core/web/loader/getters.go
  core/web/loader/job_run.go
  core/web/loader/loader.go
  core/web/presenters/pipeline_run.go
  core/web/resolver/job.go
  core/web/resolver/job_run.go
  core/web/resolver/job_test.go
  core/web/resolver/task_run.go
  core/web/schema/type/job.graphql
  core/web/schema/type/job_run.graphql
  core/web/schema/type/task_run.go.graphql
Labels: merged-by-homu

#5417 Nurse
  core/chains/evm/config/mocks/chain_scoped_config.go
  core/config/general_config.go
  core/config/mocks/general_config.go
  core/config/parsers.go
  core/config/schema.go
  core/config/schema_test.go
  core/logger/fields.go
  core/services/chainlink/application.go
  core/services/health/nurse.go
  core/utils/files.go
  docs/CHANGELOG.md
  go.mod
  go.sum
Labels: S-waiting-on-review

#5433 Implements `setServicesLogLevels` mutation
  core/web/resolver/log.go
  core/web/resolver/log_test.go
  core/web/resolver/mutation.go
  core/web/schema/schema.graphql
  core/web/schema/type/log.graphql
Labels: S-waiting-on-author

#5377 Setup GQL in Operator UI
  core/chainlink.Dockerfile
  operator_ui/.gitignore
  operator_ui/@types/core/store/models.d.ts
  operator_ui/codegen.yml
  operator_ui/jest.config.js
  operator_ui/package.json
  operator_ui/src/Private.tsx
  operator_ui/src/actionCreators.ts
  operator_ui/src/api/v2/feedsManagers.ts
  operator_ui/src/api/v2/index.ts
  operator_ui/src/apollo.ts
  operator_ui/src/components/ErrorHandler/GraphqlErrorHandler.test.tsx
  operator_ui/src/components/ErrorHandler/GraphqlErrorHandler.tsx
  operator_ui/src/components/Feedback/Loading.test.tsx
  operator_ui/src/components/Feedback/Loading.tsx
  operator_ui/src/components/Form/FeedsManagerForm.test.tsx
  operator_ui/src/components/Form/FeedsManagerForm.tsx
  operator_ui/src/hooks/useFeedsManagersQuery.ts
  operator_ui/src/hooks/useMutationErrorHandler.test.tsx
  operator_ui/src/hooks/useMutationErrorHandler.tsx
  operator_ui/src/index.js
  operator_ui/src/pages/FeedsManager/EditFeedsManagerView.tsx
  operator_ui/src/pages/FeedsManager/FeedsManagerScreen.tsx
  operator_ui/src/pages/feeds_manager/index.tsx
  operator_ui/src/screens/EditFeedsManager/EditFeedsManagerScreen.test.tsx
  operator_ui/src/screens/EditFeedsManager/EditFeedsManagerScreen.tsx
  operator_ui/src/screens/EditFeedsManager/EditFeedsManagerView.test.tsx
  operator_ui/src/screens/EditFeedsManager/EditFeedsManagerView.tsx
  operator_ui/src/screens/FeedsManager/FeedsManagerCard.test.tsx
  operator_ui/src/screens/FeedsManager/FeedsManagerCard.tsx
  operator_ui/src/screens/FeedsManager/FeedsManagerScreen.test.tsx
  operator_ui/src/screens/FeedsManager/FeedsManagerScreen.tsx
  operator_ui/src/screens/FeedsManager/FeedsManagerView.test.tsx
  operator_ui/src/screens/FeedsManager/FeedsManagerView.tsx
  operator_ui/src/screens/FeedsManager/JobProposalsCard.tsx
  operator_ui/src/screens/NewFeedsManager/NewFeedsManagerScreen.test.tsx
  operator_ui/src/screens/NewFeedsManager/NewFeedsManagerScreen.tsx
  operator_ui/src/screens/NewFeedsManager/NewFeedsManagerView.test.tsx
  operator_ui/src/screens/NewFeedsManager/NewFeedsManagerView.tsx
  operator_ui/src/utils/inputErrors.ts
  operator_ui/support/factories/feedsManager.ts
  package.json
  yarn.lock
Labels: ready for review, S-waiting-on-author

#5465 Fix the typecheck caused by an API update
  operator_ui/src/screens/EditFeedsManager/EditFeedsManagerView.tsx
  operator_ui/src/screens/FeedsManager/FeedsManagerView.tsx
  operator_ui/support/factories/feedsManager.ts
Labels: ready for review

#5463 Fixes the return of dataloaded proposals in a feeds manager
  core/web/loader/job_proposal.go
  core/web/resolver/feeds_manager_test.go
Labels: blocked

#5458 backport panic handling
  core/recovery/recovery.go
  core/services/feeds/connection_manager.go
  core/services/fluxmonitorv2/flux_monitor.go
  core/services/offchainreporting/peerstore.go
  core/services/offchainreporting/run_saver.go
  core/services/pipeline/runner.go
  core/services/vrf/listener_v1.go
  core/services/vrf/listener_v2.go
  core/shutdown/channel.go
  core/shutdown/recover.go
Labels: ready for review

#5467 TestIntegration_OCR Failure
  core/internal/features_test.go
Labels: ready for review

#5464 Use GQL to display job proposals in Operator UI
  operator_ui/src/api/v2/jobProposals.ts
  operator_ui/src/screens/EditFeedsManager/EditFeedsManagerScreen.test.tsx
  operator_ui/src/screens/EditFeedsManager/EditFeedsManagerView.test.tsx
  operator_ui/src/screens/EditFeedsManager/EditFeedsManagerView.tsx
  operator_ui/src/screens/FeedsManager/FeedsManagerCard.test.tsx
  operator_ui/src/screens/FeedsManager/FeedsManagerCard.tsx
  operator_ui/src/screens/FeedsManager/FeedsManagerScreen.test.tsx
  operator_ui/src/screens/FeedsManager/FeedsManagerScreen.tsx
  operator_ui/src/screens/FeedsManager/FeedsManagerView.test.tsx
  operator_ui/src/screens/FeedsManager/FeedsManagerView.tsx
  operator_ui/src/screens/FeedsManager/JobProposalsCard.test.tsx
  operator_ui/src/screens/FeedsManager/JobProposalsCard.tsx
  operator_ui/src/screens/FeedsManager/types.ts
  operator_ui/src/screens/NewFeedsManager/NewFeedsManagerScreen.test.tsx
  operator_ui/support/factories/gql/fetchFeedsManagers.ts
  operator_ui/support/factories/gql/fetchFeedsManagersWithProposals.ts
Labels: ready for review, S-waiting-on-author

#5454 SQL Logging Mutation
  core/web/resolver/log.go
  core/web/resolver/log_test.go
  core/web/resolver/mutation.go
  core/web/schema/schema.graphql
  core/web/schema/type/log.graphql
Labels: S-waiting-on-author

#5469 Flakey TestPipelineJobSpecErrorsController_Delete_2
  core/services/fluxmonitorv2/flux_monitor.go
  core/services/fluxmonitorv2/flux_monitor_test.go
  core/services/job/job_orm_test.go
  core/services/job/mocks/orm.go
  core/services/job/mocks/spawner.go
  core/services/job/orm.go
  core/services/job/spawner.go
  core/services/keeper/registry_synchronizer_sync.go
  core/services/offchainreporting/delegate.go
  core/web/pipeline_job_spec_errors_controller_test.go
Labels: ready for review

#5476 RunSaver missing log value
  core/services/offchainreporting/run_saver.go
Labels: ready for review

#5478 Minor bugfix in BPTXM when another wallet has used a nonce
  core/services/bulletprooftxmanager/eth_confirmer.go
  core/services/bulletprooftxmanager/eth_confirmer_test.go
Labels: ready for review

#5448 Support Avalanche "nonce too low" errors
  core/services/eth/errors.go
  core/services/eth/errors_test.go
  docs/CHANGELOG.md
Labels: ready for review

#5456 POC Sentry support
  core/logger/logger.go
  core/main.go
  core/recovery/recover.go
  core/services/pg/transaction.go
  core/static/static.go
  docs/CHANGELOG.md
  go.mod
  go.sum
  tools/bin/ldflags
Labels: ready for review

#5474 Make balance reporting on dashboard consistent
  core/services/keystore/eth.go
  core/services/keystore/eth_test.go
  core/web/eth_keys_controller.go
  yarn.lock
Labels: ready for review

#5487 OCR dataSource race
  core/services/offchainreporting/data_source.go
Labels: ready for review

#5392 Fix race for eth.Head.EVMChainID
  core/internal/cltest/cltest.go
  core/internal/cltest/factories.go
  core/internal/cltest/mocks.go
  core/internal/cltest/simulated_backend.go
  core/services/balance_monitor.go
  core/services/balance_monitor_test.go
  core/services/bulletprooftxmanager/bulletprooftxmanager.go
  core/services/bulletprooftxmanager/bulletprooftxmanager_test.go
  core/services/bulletprooftxmanager/eth_confirmer.go
  core/services/bulletprooftxmanager/eth_confirmer_test.go
  core/services/bulletprooftxmanager/mocks/tx_manager.go
  core/services/directrequest/delegate.go
  core/services/eth/chain_id_sub.go
  core/services/eth/client.go
  core/services/eth/client_test.go
  core/services/eth/erroring_node.go
  core/services/eth/helpers_test.go
  core/services/eth/mocks/node.go
  core/services/eth/mocks/send_only_node.go
  core/services/eth/models.go
  core/services/eth/node.go
  core/services/eth/pool.go
  core/services/eth/pool_test.go
  core/services/eth/send_only_node.go
  core/services/gas/block_history_estimator.go
  core/services/gas/block_history_estimator_test.go
  core/services/gas/fixed_price_estimator.go
  core/services/gas/mocks/estimator.go
  core/services/gas/models.go
  core/services/gas/optimism_estimator.go
  core/services/headtracker/head_broadcaster.go
  core/services/headtracker/head_broadcaster_test.go
  core/services/headtracker/head_listener.go
  core/services/headtracker/head_saver.go
  core/services/headtracker/head_tracker.go
  core/services/headtracker/head_tracker_test.go
  core/services/headtracker/helpers_test.go
  core/services/headtracker/mocks/head_broadcaster.go
  core/services/headtracker/mocks/head_trackable.go
  core/services/headtracker/orm.go
  core/services/headtracker/orm_test.go
  core/services/headtracker/types/types.go
  core/services/keeper/upkeep_executer.go
  core/services/keeper/upkeep_executer_test.go
  core/services/log/broadcaster.go
  core/services/log/broadcaster_test.go
  core/services/log/mocks/broadcaster.go
  core/services/offchainreporting/block_translator.go
  core/services/offchainreporting/contract_tracker.go
  core/services/offchainreporting/contract_tracker_test.go
  core/services/prom_reporter.go
  core/services/prom_reporter_test.go
  core/services/vrf/delegate_test.go
  core/services/vrf/listener_v1.go
Labels: ready for review, S-waiting-on-author

#5490 Flakey SimulatedBackendClient subscription handling
  core/internal/cltest/simulated_backend.go
Labels: ready for review

#5496 Job Proposals in the Operator UI now use the GQL API
  operator_ui/@types/core/store/models.d.ts
  operator_ui/src/Private.tsx
  operator_ui/src/api/v2/index.ts
  operator_ui/src/api/v2/jobProposals.ts
  operator_ui/src/components/Dialogs/ConfirmationDialog.tsx
  operator_ui/src/pages/JobProposal/JobProposalScreen.tsx
  operator_ui/src/pages/NotFound.js
  operator_ui/src/pages/job_proposals/index.tsx
  operator_ui/src/screens/JobProposal/EditJobSpecDialog.test.tsx
  operator_ui/src/screens/JobProposal/EditJobSpecDialog.tsx
  operator_ui/src/screens/JobProposal/JobProposalScreen.test.tsx
  operator_ui/src/screens/JobProposal/JobProposalScreen.tsx
  operator_ui/src/screens/JobProposal/JobProposalView.test.tsx
  operator_ui/src/screens/JobProposal/JobProposalView.tsx
  operator_ui/support/factories/gql/fetchJobProposal.ts
Labels: ready for review

#5481 Implement `API Tokens` mutations
  core/sessions/mocks/orm.go
  core/sessions/orm.go
  core/sessions/orm_test.go
  core/web/resolver/api_token.go
  core/web/resolver/api_token_test.go
  core/web/resolver/mutation.go
  core/web/schema/schema.graphql
  core/web/schema/type/api_token.graphql
Labels: S-waiting-on-author

#5502 Use GQL API for the Bridge Details page
  operator_ui/src/Private.tsx
  operator_ui/src/api/v2/bridgeTypes.ts
  operator_ui/src/components/Bridges/Form.tsx
  operator_ui/src/pages/Bridges/Edit.js
  operator_ui/src/pages/Bridges/New.tsx
  operator_ui/src/pages/Bridges/Show.test.tsx
  operator_ui/src/pages/Bridges/Show.tsx
  operator_ui/src/pages/Bridges/index.tsx
  operator_ui/src/screens/Bridge/BridgeScreen.test.tsx
  operator_ui/src/screens/Bridge/BridgeScreen.tsx
  operator_ui/src/screens/Bridge/BridgeView.test.tsx
  operator_ui/src/screens/Bridge/BridgeView.tsx
  operator_ui/src/screens/Bridges/BridgesScreen.tsx
  operator_ui/src/screens/Bridges/BridgesView.tsx
  operator_ui/support/factories/gql/fetchBridge.ts
  operator_ui/support/factories/gql/fetchBridges.ts
Labels: S-waiting-on-author

#5495 Add tests for dataloaders
  core/services/feeds/mocks/orm.go
  core/services/feeds/mocks/service.go
  core/services/feeds/orm.go
  core/services/feeds/orm_test.go
  core/services/feeds/service.go
  core/services/feeds/service_test.go
  core/web/loader/chain.go
  core/web/loader/job_proposal.go
  core/web/loader/job_run.go
  core/web/loader/loader_test.go
  core/web/resolver/feeds_manager_test.go
Labels: S-waiting-on-author

#5511 JSON/CBOR Cleanup
  core/cbor/cbor_test.go
  core/store/models/common.go
  core/store/models/common_test.go
Labels: ready for review

#5445 core/logger: add Critical* and Trace*
  core/logger/critical.go
  core/logger/default.go
  core/logger/logger.go
  core/logger/logger_test.go
  core/logger/null_logger.go
  core/logger/ocr_wrapper.go
  core/logger/sentry.go
  core/logger/test_logger_test.go
  core/logger/trace.go
  core/logger/trace_noop.go
  core/logger/trace_noop_test.go
  core/logger/trace_test.go
  core/logger/zap.go
  core/recovery/recover.go
  core/services/pg/q.go
Labels: ready for review, S-waiting-on-author

#5503 OCR2 juelsPerFeeCoin data source
  core/internal/features_ocr2_test.go
  core/services/job/models.go
  core/services/job/orm.go
  core/services/ocrcommon/data_source.go
  core/services/ocrcommon/data_source_test.go
  core/services/offchainreporting2/common_test.go
  core/services/offchainreporting2/data_source.go
  core/services/offchainreporting2/delegate.go
  core/services/offchainreporting2/validate.go
  core/services/offchainreporting2/validate_test.go
  core/store/migrate/migrations/0085_ocr2_tables.sql
Labels: S-waiting-on-author

#5518 core/internal/cltest: rm unused funcs and sjson dependency
  core/internal/cltest/factories.go
  go.mod
  go.sum
Labels: ready for review

#5523 Obtain latest head from head broadcaster
  core/services/vrf/delegate.go
  core/services/vrf/listener_v2.go
Labels: ready for review

#5526 Refactor Jobs Table to use the GQL API
  core/web/resolver/spec.go
  core/web/resolver/spec_test.go
  core/web/schema/type/spec.graphql
  operator_ui/src/Private.tsx
  operator_ui/src/pages/JobsIndex/JobRow.tsx
  operator_ui/src/pages/JobsIndex/JobsIndex.test.tsx
  operator_ui/src/pages/JobsIndex/JobsIndex.tsx
  operator_ui/src/pages/JobsIndex/index.tsx
  operator_ui/src/screens/Bridges/BridgesView.test.tsx
  operator_ui/src/screens/Jobs/JobRow.test.tsx
  operator_ui/src/screens/Jobs/JobRow.tsx
  operator_ui/src/screens/Jobs/JobsScreen.test.tsx
  operator_ui/src/screens/Jobs/JobsScreen.tsx
  operator_ui/src/screens/Jobs/JobsView.test.tsx
  operator_ui/src/screens/Jobs/JobsView.tsx
  operator_ui/src/theme.ts
  operator_ui/support/factories/gql/fetchJobs.ts
Labels: S-waiting-on-author

#5513 Unify timeout usage in tests: use t.Deadline()
  core/internal/cltest/cltest.go
  core/internal/features_test.go
  core/services/eth/client_test.go
  core/services/eth/pool_test.go
  core/services/fluxmonitorv2/flux_monitor_test.go
  core/services/fluxmonitorv2/integrations_test.go
  core/services/job/spawner_test.go
  core/services/keeper/registry_synchronizer_test.go
  core/services/log/broadcaster_test.go
  core/services/log/helpers_test.go
  core/services/vrf/integration_v2_test.go
Labels: ready for review

#5532 Fixes GQL API url when env var is not provided on build
  operator_ui/src/apollo.ts
Labels: ready for review

#5531 Implement `UpdateChain` mutation
  core/web/resolver/chain.go
  core/web/resolver/chain_test.go
  core/web/resolver/mutation.go
  core/web/schema/schema.graphql
  core/web/schema/type/chain.graphql
Labels: S-waiting-on-author

#5537 core: rm unused
  core/config/config_internal_test.go
  core/config/parsers.go
  core/internal/cltest/cltest.go
  core/internal/cltest/fixtures.go
  core/internal/cltest/job_factories.go
  core/internal/cltest/mocks.go
  core/internal/cltest/util.go
  core/internal/testutils/configtest/general_config.go
  core/services/eth/errors.go
  core/services/eth/models.go
  core/services/fluxmonitorv2/promfm/prometheus.go
  core/services/keystore/helpers_test.go
  core/services/keystore/keys/ethkey/export.go
  core/services/keystore/keys/ethkey/key.go
  core/services/keystore/keys/vrfkey/crypto.go
  core/services/pg/channels.go
  core/services/pg/transaction.go
  core/services/pg/utils.go
  core/services/pipeline/common.go
  core/services/pipeline/graph.go
  core/services/signatures/secp256k1/public_key.go
  core/services/vrf/proof/seed.go
  core/services/vrf/vrf_coordinator_abi_values.go
  core/services/webhook/validate.go
  core/testdata/testspecs/v1_specs.go
  core/utils/ethabi.go
  core/utils/reverse_string.go
  core/utils/utils.go
  core/web/api.go
  core/web/presenters/job.go
  core/web/presenters/jsonapi.go
Labels: ready for review

#5519 Logger Injection pt. 8
  core/logger/default.go
  core/services/bulletprooftxmanager/models.go
  core/services/fluxmonitorv2/flux_monitor.go
  core/services/keystore/p2p.go
  core/services/offchainreporting/data_source.go
  core/services/pipeline/common.go
  core/services/pipeline/runner.go
  core/services/pipeline/runner_test.go
  core/services/vrf/listener_v2.go
  core/web/presenters/vrf_key.go
  core/web/router.go
  core/web/vrf_keys_controller.go
Labels: ready for review

#5547 use uber atomic.Bool; drop abool
  core/services/chainlink/application_test.go
  core/services/log/broadcaster.go
  core/services/pipeline/task.bridge_test.go
  core/services/synchronization/telemetry_ingress_client_test.go
  core/utils/utils.go
  go.mod
  go.sum
Labels: ready for review

#5520 docs: add log levels to changelog
  docs/CHANGELOG.md
Labels: ready for review

#5550 core/web: return after failing to find static file; rm packr references
  .dockerignore
  .gitignore
  core/web/router.go
Labels: ready for review

#5488 Do not exit on start if eth node is unreachable
  .nvmrc
  .tool-versions
  core/chains/evm/legacy.go
  core/cmd/client.go
  core/cmd/local_client.go
  core/cmd/remote_client_test.go
  core/internal/cltest/cltest.go
  core/internal/cltest/contract_mock_receiver.go
  core/internal/mocks/client.go
  core/services/eth/client.go
  core/services/eth/client_test.go
  core/services/eth/erroring_node.go
  core/services/eth/helpers_test.go
  core/services/eth/mocks/node.go
  core/services/eth/node.go
  core/services/eth/node_test.go
  core/services/eth/pool.go
  core/services/eth/pool_test.go
  core/services/headtracker/head_listener.go
  core/services/headtracker/head_tracker.go
  core/services/helpers_test.go
  core/services/keeper/registry_synchronizer_test.go
  core/services/keeper/upkeep_executer_test.go
  core/services/log/helpers_test.go
  core/services/offchainreporting/contract_tracker_test.go
  core/web/assets/index.html
  core/web/jobs_controller_test.go
  core/web/middleware.go
Labels: S-waiting-on-author

#5549 Enabled code coverage
  tools/bin/codecov
  tools/bin/go_core_tests
Labels: ready for review

#5568 update log_broadcasts migration with default timestamps
  core/store/migrate/migrations/0081_unconsumed_log_broadcasts.sql
Labels: ready for review
