Repository smartcontractkit/chainlink, pull requests merged in 2021-12, with the labels that each got.

#5539 Support pagination for the nested runs on a job
  core/services/job/job_orm_test.go
  core/services/job/mocks/orm.go
  core/services/job/orm.go
  core/web/loader/getters.go
  core/web/loader/job_run.go
  core/web/loader/loader.go
  core/web/loader/loader_test.go
  core/web/resolver/job.go
  core/web/resolver/job_run.go
  core/web/resolver/job_test.go
  core/web/resolver/mutation.go
  core/web/resolver/query.go
  core/web/schema/type/job.graphql
  core/web/schema/type/job_run.graphql
Labels: ready for review, S-waiting-on-author

#5575 Refactor feature flags to use the GQL API
  operator_ui/@types/core/store/models.d.ts
  operator_ui/package.json
  operator_ui/src/api/v2/features.ts
  operator_ui/src/api/v2/index.ts
  operator_ui/src/hooks/useFeatureFlag.test.tsx
  operator_ui/src/hooks/useFeatureFlag.tsx
  operator_ui/src/pages/Header.tsx
  operator_ui/src/pages/Keys/Index.tsx
  operator_ui/support/factories/jsonApiFeatures.ts
  yarn.lock
Labels: ready for review

#5589 Hotfix/log pool add dupes
  core/services/log/broadcaster_test.go
  core/services/log/pool.go
  core/services/log/pool_test.go
Labels: ready for review

#5592 Fix 1970 jobs.created_at; configurable timeouts on lease lock
  core/chains/evm/config/mocks/chain_scoped_config.go
  core/cmd/client.go
  core/cmd/local_client_test.go
  core/config/general_config.go
  core/config/mocks/general_config.go
  core/config/presenters.go
  core/config/schema.go
  core/config/schema_test.go
  core/services/pg/lease_lock.go
  core/services/pg/transaction.go
  core/store/migrate/migrations/0080_drop_unused_cols.sql
  docs/CHANGELOG.md
Labels: ready for review

#5569 Implements `DismissJobError` GQL mutation
  core/services/job/job_orm_test.go
  core/services/job/mocks/orm.go
  core/services/job/models.go
  core/services/job/orm.go
  core/web/pipeline_job_spec_errors_controller.go
  core/web/resolver/job_error.go
  core/web/resolver/job_error_test.go
  core/web/resolver/mutation.go
  core/web/schema/schema.graphql
  core/web/schema/type/job_error.graphql
Labels: S-waiting-on-author

#5596 Correctly handle signedness of abi type
  core/services/pipeline/common_eth.go
  core/services/pipeline/task.eth_abi_encode_test.go
Labels: ready for review

#5582 Fixes a couple of issues for the GQL API
  core/services/job/job_orm_test.go
  core/services/job/orm.go
  core/web/jobs_controller_test.go
  core/web/router.go
Labels: ready for review

#5602 Add OCR2 spec to the GQL API
  core/web/resolver/spec.go
  core/web/resolver/spec_test.go
  core/web/schema/type/spec.graphql
Labels: ready for review

#5594 Remove dead DATABASE_ env vars
  core/chains/evm/config/mocks/chain_scoped_config.go
  core/cmd/local_client_test.go
  core/config/general_config.go
  core/config/mocks/general_config.go
  core/config/presenters.go
  core/config/schema.go
  core/config/schema_test.go
  core/internal/testutils/configtest/general_config.go
  core/services/job/common.go
  core/services/pg/lease_lock.go
  core/services/pg/lease_lock_test.go
  core/services/pg/transaction.go
  core/services/pg/utils.go
  core/services/pipeline/common.go
  core/services/pipeline/mocks/config.go
  core/web/config_controller_test.go
Labels: S-waiting-on-author

#5579 [OCR2 - Relay Solana] Add smartcontractkit/chainlink-solana module
  core/services/relay/delegate/delegate.go
  core/services/relay/solana/solana.go
  go.mod
  go.sum
Labels: S-waiting-on-author

#5605 Update dashboard recent jobs cards to GQL
  core/services/job/orm.go
  operator_ui/src/api/v2/jobs.ts
  operator_ui/src/components/Jobs/RecentlyCreated.js
  operator_ui/src/components/Jobs/RecentlyCreated.test.js
  operator_ui/src/components/Jobs/TaskList.tsx
  operator_ui/src/components/SimpleListCard.tsx
  operator_ui/src/components/SimpleListCardItem.tsx
  operator_ui/src/components/TableRow/ErrorRow.test.tsx
  operator_ui/src/components/TableRow/ErrorRow.tsx
  operator_ui/src/components/TableRow/LoadingRow.test.tsx
  operator_ui/src/components/TableRow/LoadingRow.tsx
  operator_ui/src/components/TableRow/NoContentRow.test.tsx
  operator_ui/src/components/TableRow/NoContentRow.tsx
  operator_ui/src/pages/Dashboards/Index.test.js
  operator_ui/src/pages/Dashboards/Index.tsx
  operator_ui/src/screens/Dashboard/RecentJobRow.test.tsx
  operator_ui/src/screens/Dashboard/RecentJobRow.tsx
  operator_ui/src/screens/Dashboard/RecentJobs.test.tsx
  operator_ui/src/screens/Dashboard/RecentJobs.tsx
  operator_ui/src/screens/Dashboard/RecentJobsCard.test.tsx
  operator_ui/src/screens/Dashboard/RecentJobsCard.tsx
  operator_ui/src/screens/KeyManagement/CSAKeysCard.tsx
  operator_ui/src/screens/KeyManagement/OCRKeysCard.tsx
  operator_ui/src/screens/KeyManagement/P2PKeysCard.tsx
  operator_ui/src/screens/KeyManagement/Rows.tsx
  operator_ui/support/factories/gql/fetchRecentJobs.ts
Labels: ready for review

#5553 V2 Migration - skip ethbytes32, ethbool
  core/web/migrate_controller.go
  core/web/migrate_controller_test.go
Labels: ready for review

#5612 Update the Activity card on the dashboard to use GQL
  core/web/resolver/job_run_test.go
  core/web/resolver/query.go
  core/web/schema/schema.graphql
  core/web/schema/type/job_run.graphql
  operator_ui/src/components/Dashboards/Activity.test.tsx
  operator_ui/src/components/Dashboards/Activity.tsx
  operator_ui/src/components/Icons/Success.tsx
  operator_ui/src/components/StatusIcon.tsx
  operator_ui/src/pages/Dashboards/Index.tsx
  operator_ui/src/screens/Dashboard/Activity.test.tsx
  operator_ui/src/screens/Dashboard/Activity.tsx
  operator_ui/src/screens/Dashboard/ActivityCard.test.tsx
  operator_ui/src/screens/Dashboard/ActivityCard.tsx
  operator_ui/src/screens/Dashboard/ActivityRow.test.tsx
  operator_ui/src/screens/Dashboard/ActivityRow.tsx
  operator_ui/src/screens/Dashboard/RecentJobRow.test.tsx
  operator_ui/src/screens/Dashboard/RecentJobs.tsx
  operator_ui/support/factories/gql/fetchRecentJobRuns.ts
Labels: ready for review

#5603 Added new parameters to OCR job spec
  core/config/mocks/general_config.go
  core/internal/cltest/factories.go
  core/services/job/models.go
  core/services/job/orm.go
  core/services/job/orm_test.go
  core/services/offchainreporting/config.go
  core/services/offchainreporting/validate_test.go
  core/store/migrate/migrations/0089_ocr_new_timeouts.sql
  core/store/models/common.go
  core/store/models/common_test.go
  core/web/presenters/job.go
  core/web/presenters/job_test.go
  core/web/resolver/spec.go
  core/web/resolver/spec_test.go
  core/web/schema/type/spec.graphql
  docs/CHANGELOG.md
  operator_ui/@types/core/store/models.d.ts
Labels: ready for review

#5625 Enabled code coverage upload to CodeCov for Solidity
  .github/codecov.yml
  tools/ci/solidity_coverage
Labels: ready for review

#5629 Refactor job runs page to use GQL API
  operator_ui/src/Private.tsx
  operator_ui/src/api/v2/runs.ts
  operator_ui/src/pages/JobRuns/Index.js
  operator_ui/src/pages/JobRuns/Index.test.js
  operator_ui/src/pages/Jobs/JobRunsList.tsx
  operator_ui/src/pages/job_runs/index.tsx
  operator_ui/src/screens/JobRuns/JobRunsScreen.test.tsx
  operator_ui/src/screens/JobRuns/JobRunsScreen.tsx
  operator_ui/src/screens/JobRuns/JobRunsView.test.tsx
  operator_ui/src/screens/JobRuns/JobRunsView.tsx
  operator_ui/support/factories/gql/fetchJobRuns.ts
Labels: ready for review

#5633 Refactor the dashboard account balances to use GQL API
  operator_ui/src/Private.tsx
  operator_ui/src/actionCreators.ts
  operator_ui/src/api/v2/index.ts
  operator_ui/src/api/v2/user/balances.ts
  operator_ui/src/api/v2/user/index.ts
  operator_ui/src/components/Cards/TokenBalance.test.tsx
  operator_ui/src/components/Cards/TokenBalance.tsx
  operator_ui/src/components/Footer.js
  operator_ui/src/pages/Configuration/Index.tsx
  operator_ui/src/pages/Dashboards/Index.tsx
  operator_ui/src/pages/dashboard/index.tsx
  operator_ui/src/reducers.ts
  operator_ui/src/reducers/accountBalances.test.ts
  operator_ui/src/reducers/accountBalances.ts
  operator_ui/src/reducers/actions.ts
  operator_ui/src/reducers/fetching.test.ts
  operator_ui/src/screens/Dashboard/AccountBalance.test.tsx
  operator_ui/src/screens/Dashboard/AccountBalance.tsx
  operator_ui/src/screens/Dashboard/AccountBalanceCard.test.tsx
  operator_ui/src/screens/Dashboard/AccountBalanceCard.tsx
  operator_ui/src/screens/Dashboard/BuildInfoFooter.test.tsx
  operator_ui/src/screens/Dashboard/BuildInfoFooter.tsx
  operator_ui/src/screens/Dashboard/DashboardScreen.tsx
  operator_ui/src/screens/Dashboard/DashboardView.test.tsx
  operator_ui/src/screens/Dashboard/DashboardView.tsx
  operator_ui/src/utils/extractBuildInfo.js
  operator_ui/src/utils/extractBuildInfo.test.ts
  operator_ui/src/utils/extractBuildInfo.ts
  operator_ui/src/utils/formatWeiAsset.ts
  operator_ui/support/factories/accountBalance.ts
  operator_ui/support/factories/gql/fetchAccountBalances.ts
Labels: ready for review

#5534 Implement query to get Chainlink node's configuration
  core/cmd/local_client.go
  core/config/presenters.go
  core/config/presenters_test.go
  core/internal/testutils/configtest/general_config.go
  core/web/config_controller.go
  core/web/resolver/config.go
  core/web/resolver/config_test.go
  core/web/resolver/query.go
  core/web/schema/schema.graphql
  core/web/schema/type/config.graphql
Labels: S-waiting-on-author

#5643 Refactor configuration to use the GQL API
  core/web/resolver/config.go
  core/web/resolver/config_test.go
  core/web/schema/type/config.graphql
  operator_ui/@types/core/store/presenters.d.ts
  operator_ui/src/Private.tsx
  operator_ui/src/actionCreators.ts
  operator_ui/src/api/v2/config.ts
  operator_ui/src/api/v2/index.ts
  operator_ui/src/components/Cards/KeyValueListCard.test.tsx
  operator_ui/src/components/Cards/KeyValueListCard.tsx
  operator_ui/src/pages/Configuration/Index.test.tsx
  operator_ui/src/pages/Configuration/Index.tsx
  operator_ui/src/pages/Configuration/JobRuns.tsx
  operator_ui/src/pages/Configuration/NodeInformation.tsx
  operator_ui/src/pages/config/index.tsx
  operator_ui/src/reducers.ts
  operator_ui/src/reducers/configuration.test.ts
  operator_ui/src/reducers/configuration.ts
  operator_ui/src/screens/Configuration/ConfigurationCard/ConfigurationCard.test.tsx
  operator_ui/src/screens/Configuration/ConfigurationCard/ConfigurationCard.tsx
  operator_ui/src/screens/Configuration/ConfigurationScreen.tsx
  operator_ui/src/screens/Configuration/ConfigurationView.test.tsx
  operator_ui/src/screens/Configuration/ConfigurationView.tsx
  operator_ui/src/screens/Configuration/NodeInfoCard/NodeInfoCard.test.tsx
  operator_ui/src/screens/Configuration/NodeInfoCard/NodeInfoCard.tsx
  operator_ui/src/selectors/accountBalance.js
  operator_ui/src/selectors/configuration.test.ts
  operator_ui/src/selectors/configuration.ts
  operator_ui/support/factories/configuration.js
  operator_ui/support/factories/gql/fetchConfig.ts
Labels: ready for review, S-waiting-on-author

#5644 UI now requires confirmation when deleting a job
  operator_ui/src/screens/Job/JobCard.test.tsx
  operator_ui/src/screens/Job/JobCard.tsx
  operator_ui/src/screens/Job/JobScreen.test.tsx
  operator_ui/src/screens/Job/JobView.test.tsx
  operator_ui/src/screens/Job/JobView.tsx
Labels: ready for review

#5650 Remove unused operator ui deps
  operator_ui/jest.setup.js
  operator_ui/package.json
  operator_ui/src/index.js
  operator_ui/support/test-helpers/generateUuid.ts
  yarn.lock
Labels: ready for review

#5653 Use the job status in GQL API instead of infering it from fields
  operator_ui/@types/core/store/models.d.ts
  operator_ui/src/components/Cards/TaskListCard.test.tsx
  operator_ui/src/components/Cards/TaskListCard.tsx
  operator_ui/src/components/Icons/TaskRunStatusIcon.test.tsx
  operator_ui/src/components/Icons/TaskRunStatusIcon.tsx
  operator_ui/src/components/Icons/TaskStatus.tsx
  operator_ui/src/components/StatusIcon.tsx
  operator_ui/src/components/Table/JobRunsTable.test.tsx
  operator_ui/src/components/Table/JobRunsTable.tsx
  operator_ui/src/pages/Jobs/TaskListDag.tsx
  operator_ui/src/pages/Jobs/utils.ts
  operator_ui/src/screens/Configuration/NodeInfoCard/NodeInfoCard.test.tsx
  operator_ui/src/screens/Dashboard/ActivityCard.tsx
  operator_ui/src/screens/Dashboard/ActivityRow.test.tsx
  operator_ui/src/screens/Dashboard/ActivityRow.tsx
  operator_ui/src/screens/Job/JobView.tsx
  operator_ui/src/screens/Job/TabOverview.test.tsx
  operator_ui/src/screens/Job/TabOverview.tsx
  operator_ui/src/screens/Job/TabRuns.tsx
  operator_ui/src/screens/JobRun/JobRunView.tsx
  operator_ui/src/screens/JobRun/TaskRunItem.test.tsx
  operator_ui/src/screens/JobRun/TaskRunItem.tsx
  operator_ui/src/screens/JobRuns/JobRunsView.tsx
  operator_ui/src/utils/taskRunStatus.ts
  operator_ui/support/factories/gql/fetchJob.ts
  operator_ui/support/factories/gql/fetchJobRuns.ts
  operator_ui/support/factories/gql/fetchRecentJobRuns.ts
Labels: ready for review

#5659 Add LOG_FILE_DIR to control logging output directory
  core/chains/evm/config/mocks/chain_scoped_config.go
  core/cmd/local_client_test.go
  core/config/general_config.go
  core/config/mocks/general_config.go
  core/config/presenters.go
  core/config/schema.go
  core/config/schema_test.go
  core/internal/cltest/cltest.go
  core/internal/testutils/configtest/general_config.go
  core/logger/default.go
  core/logger/logger.go
  core/logger/prettyconsole.go
  core/web/resolver/config_test.go
  docs/CHANGELOG.md
Labels: ready for review

#5649 OCR2 & Solana Key Updates
  core/cmd/ocr2_keys_commands.go
  core/cmd/ocr2_keys_commands_test.go
  core/cmd/solana_keys_commands_test.go
  core/internal/features_ocr2_test.go
  core/services/keystore/keys/ocr2key/evm_key_bundle.go
  core/services/keystore/keys/ocr2key/evm_keyring.go
  core/services/keystore/keys/ocr2key/export.go
  core/services/keystore/keys/ocr2key/key_bundle.go
  core/services/keystore/keys/ocr2key/key_bundle_test.go
  core/services/keystore/keys/ocr2key/solana_key_bundle.go
  core/services/keystore/keys/ocr2key/solana_keyring.go
  core/services/keystore/keys/solkey/key.go
  core/web/presenters/ocr_keys.go
  core/web/presenters/solana_key.go
  core/web/solana_keys_controller_test.go
  go.mod
  go.sum
Labels: S-waiting-on-author

#5635 ETH Transactions GQL
  core/services/bulletprooftxmanager/mocks/orm.go
  core/services/bulletprooftxmanager/orm.go
  core/services/bulletprooftxmanager/orm_test.go
  core/web/loader/eth_transaction_attempt.go
  core/web/loader/getters.go
  core/web/loader/loader.go
  core/web/loader/loader_test.go
  core/web/resolver/eth_transaction.go
  core/web/resolver/eth_transaction_attempt.go
  core/web/resolver/eth_transaction_test.go
  core/web/resolver/query.go
  core/web/resolver/resolver_test.go
  core/web/schema/schema.graphql
  core/web/schema/type/eth_transaction.graphql
  core/web/schema/type/eth_transaction_attempt.graphql
Labels: S-waiting-on-author

#5666 Refactor the New Job Form to use the GQL API
  operator_ui/@types/core/store/models.d.ts
  operator_ui/src/Private.tsx
  operator_ui/src/api/v2/jobs.ts
  operator_ui/src/components/Cards/TaskListCard.tsx
  operator_ui/src/components/Cards/TaskListDAG.test.tsx
  operator_ui/src/components/Cards/TaskListDAG.tsx
  operator_ui/src/components/Form/JobForm.test.tsx
  operator_ui/src/components/Form/JobForm.tsx
  operator_ui/src/pages/Jobs/New.test.tsx
  operator_ui/src/pages/Jobs/New.tsx
  operator_ui/src/pages/Jobs/utils.test.tsx
  operator_ui/src/pages/Jobs/utils.ts
  operator_ui/src/pages/JobsIndex/index.tsx
  operator_ui/src/screens/Job/JobScreen.tsx
  operator_ui/src/screens/NewJob/NewJobFormCard/NewJobFormCard.test.tsx
  operator_ui/src/screens/NewJob/NewJobFormCard/NewJobFormCard.tsx
  operator_ui/src/screens/NewJob/NewJobScreen.test.tsx
  operator_ui/src/screens/NewJob/NewJobScreen.tsx
  operator_ui/src/screens/NewJob/NewJobView.test.tsx
  operator_ui/src/screens/NewJob/NewJobView.tsx
  operator_ui/src/screens/NewJob/TaskListPreviewCard/TaskListPreviewCard.test.tsx
  operator_ui/src/screens/NewJob/TaskListPreviewCard/TaskListPreviewCard.tsx
Labels: ready for review

#5668 Add extra testing on headlistener for resubscribes; DefaultQueryCtx applies to all queries
  core/chains/evm/chain.go
  core/internal/cltest/cltest.go
  core/services/bulletprooftxmanager/bulletprooftxmanager.go
  core/services/bulletprooftxmanager/bulletprooftxmanager_test.go
  core/services/bulletprooftxmanager/eth_broadcaster.go
  core/services/bulletprooftxmanager/eth_confirmer.go
  core/services/bulletprooftxmanager/eth_resender.go
  core/services/bulletprooftxmanager/nonce_syncer.go
  core/services/eth/chain_id_sub.go
  core/services/eth/client.go
  core/services/eth/mocks/subscription.go
  core/services/eth/node.go
  core/services/headtracker/head_broadcaster_test.go
  core/services/headtracker/head_listener.go
  core/services/headtracker/head_listener_test.go
  core/services/headtracker/head_tracker.go
  core/services/headtracker/head_tracker_test.go
  core/services/keystore/mocks/ocr2.go
  core/services/log/eth_subscriber.go
  core/services/log/helpers_test.go
  core/services/relay/evm/mocks/ocr_contract_tracker_db.go
Labels: ready for review

#5681 Release/1.1.0 rc1
  core/logger/sentry.go
  core/store/migrate/migrations/0079_vrf_v2_fields.sql
  docs/CHANGELOG.md
Labels: ready for review

#5651 Modify sentry to correctly log structured data
  core/logger/helpers_test.go
  core/logger/sentry.go
  core/logger/sentry_test.go
Labels: ready for review

#5656 Implement docker healthcheck command (closes #3631)
  core/chainlink.Dockerfile
Labels: ready for review

#5672 Implement query to fetch Solana Keys
  core/internal/cltest/cltest.go
  core/internal/testutils/keystest/seedable_rand_reader.go
  core/services/keystore/mocks/solana.go
  core/services/keystore/solana.go
  core/web/resolver/query.go
  core/web/resolver/resolver_test.go
  core/web/resolver/solana_key.go
  core/web/resolver/solana_key_test.go
  core/web/schema/schema.graphql
  core/web/schema/type/solana_key.graphql
Labels: S-waiting-on-author

#5690 core/services/nurse: use gather trace duration
  core/services/nurse.go
Labels: ready for review

#5673 Implement query to get the SQL log level config
  core/web/resolver/log.go
  core/web/resolver/log_test.go
  core/web/resolver/query.go
  core/web/schema/schema.graphql
  core/web/schema/type/log.graphql
Labels: S-waiting-on-author

#5702 Head Saver and ORM refactoring
  core/chains/evm/chain.go
  core/internal/features_test.go
  core/logger/logger.go
  core/services/headtracker/head_broadcaster.go
  core/services/headtracker/head_broadcaster_test.go
  core/services/headtracker/head_listener.go
  core/services/headtracker/head_saver.go
  core/services/headtracker/head_saver_test.go
  core/services/headtracker/head_tracker.go
  core/services/headtracker/head_tracker_test.go
  core/services/headtracker/heads.go
  core/services/headtracker/heads_test.go
  core/services/headtracker/helpers_test.go
  core/services/headtracker/mocks/head_broadcaster.go
  core/services/headtracker/orm.go
  core/services/headtracker/orm_test.go
  core/services/headtracker/types/types.go
  core/services/service.go
Labels: ready for review

#5708 HeadBroadcaster tests
  core/services/headtracker/head_broadcaster.go
  core/services/headtracker/head_broadcaster_test.go
  core/services/headtracker/types/types.go
Labels: ready for review

#5718 core/services/pipeline: expand Test_convertToETHABIType and add more cases
  core/services/pipeline/common_eth_test.go
Labels: ready for review

#5722 Terra keystore
  core/cmd/app.go
  core/cmd/local_client.go
  core/cmd/terra_keys_commands.go
  core/cmd/terra_keys_commands_test.go
  core/internal/cltest/cltest.go
  core/main_test.go
  core/services/keystore/chaintype/chaintype.go
  core/services/keystore/keys/ocr2key/export.go
  core/services/keystore/keys/ocr2key/key_bundle.go
  core/services/keystore/keys/ocr2key/solana_keyring.go
  core/services/keystore/keys/ocr2key/terra_key_bundle.go
  core/services/keystore/keys/ocr2key/terra_keyring.go
  core/services/keystore/keys/solkey/key.go
  core/services/keystore/keys/terrakey/export.go
  core/services/keystore/keys/terrakey/key.go
  core/services/keystore/master.go
  core/services/keystore/mocks/master.go
  core/services/keystore/models.go
  core/services/keystore/ocr2_test.go
  core/services/keystore/terra.go
  core/services/keystore/terra_test.go
  core/web/presenters/terra_key.go
  core/web/router.go
  core/web/terra_keys_controller.go
  core/web/terra_keys_controller_test.go
  go.mod
  go.sum
Labels: S-waiting-on-author

#5566 Logger Injection pt. 9
  core/chains/evm/config/config.go
  core/chains/evm/config/mocks/chain_scoped_config.go
  core/cmd/app.go
  core/cmd/client.go
  core/cmd/local_client.go
  core/cmd/local_client_test.go
  core/cmd/remote_client_test.go
  core/cmd/renderer.go
  core/config/config_internal_test.go
  core/config/envvar/envvar.go
  core/config/envvar/schema.go
  core/config/envvar/schema_test.go
  core/config/general_config.go
  core/config/mocks/general_config.go
  core/config/ocr1_config.go
  core/config/ocr2_config.go
  core/config/p2p_config.go
  core/config/p2p_v1_config.go
  core/config/p2p_v2_config.go
  core/config/parse/parsers.go
  core/config/presenters.go
  core/config/presenters_test.go
  core/internal/cltest/cltest.go
  core/internal/cltest/heavyweight/orm.go
  core/internal/testutils/configtest/general_config.go
  core/logger/default.go
  core/logger/logger.go
  core/logger/null_logger.go
  core/logger/test_logger.go
  core/main.go
  core/services/keystore/keys/ocr2key/offchain_keyring.go
  core/services/log/mocks/config.go
  core/services/ocrcommon/config.go
  core/services/offchainreporting/validate.go
  core/services/pg/utils.go
  core/services/pipeline/common_http.go
  core/services/pipeline/http.go
  core/services/pipeline/http_allowed_ips.go
  core/services/pipeline/http_allowed_ips_test.go
  core/services/pipeline/mocks/config.go
  core/services/pipeline/task.http.go
  core/services/relay/evm/contract_tracker.go
  core/web/log_controller_test.go
  core/web/resolver/config.go
  core/web/resolver/config_test.go
Labels: ready for review, S-waiting-on-author
