Repository smartcontractkit/chainlink, pull requests merged in 2022-11, with the labels that each got.

#7839 core/chains/evm/client: fix node races
  core/chains/evm/client/node.go
  core/chains/evm/client/node_lifecycle_test.go
  core/internal/testutils/testutils.go
Labels: ready for review

#7789 Last good value persistence for price feeds
  core/bridges/mocks/orm.go
  core/bridges/orm.go
  core/bridges/orm_test.go
  core/chains/evm/config/mocks/chain_scoped_config.go
  core/cmd/local_client_test.go
  core/config/envvar/schema.go
  core/config/envvar/schema_test.go
  core/config/general_config.go
  core/config/mocks/general_config.go
  core/config/presenters.go
  core/config/v2/docs/core.toml
  core/config/v2/types.go
  core/internal/cltest/factories.go
  core/internal/testutils/configtest/general_config.go
  core/services/chainlink/config_dump.go
  core/services/chainlink/config_general.go
  core/services/chainlink/config_test.go
  core/services/chainlink/testdata/config-empty-effective.toml
  core/services/chainlink/testdata/config-full.toml
  core/services/chainlink/testdata/config-multi-chain-effective.toml
  core/services/pipeline/common.go
  core/services/pipeline/getters.go
  core/services/pipeline/getters_test.go
  core/services/pipeline/helpers_test.go
  core/services/pipeline/mocks/config.go
  core/services/pipeline/runner.go
  core/services/pipeline/task.bridge.go
  core/services/pipeline/task.bridge_test.go
  core/services/pipeline/task.http_test.go
  core/store/migrate/migrations/0149_bridge_last_good_value.sql
  core/web/resolver/testdata/config-empty-effective.toml
  core/web/resolver/testdata/config-full.toml
  core/web/resolver/testdata/config-multi-chain-effective.toml
  docs/CHANGELOG.md
  docs/CONFIG.md
Labels: ready for review

#7875 core/services/chainlink: fix/improve TOML config errors
  core/chains/evm/chain_set.go
  core/main.go
  core/services/chainlink/config.go
  core/services/chainlink/config_general.go
  core/services/chainlink/config_test.go
Labels: ready for review

#7791 First pass implementation of Mercury ContractTransmitter
  core/chains/evm/chain_set.go
  core/chains/evm/client/send_only_node.go
  core/chains/evm/config/mocks/chain_scoped_config.go
  core/chains/evm/headtracker/head_tracker.go
  core/chains/evm/headtracker/mocks/head_tracker.go
  core/chains/evm/headtracker/types/types.go
  core/chains/evm/logpoller/log_poller.go
  core/chains/evm/txmgr/eth_broadcaster.go
  core/chains/evm/txmgr/eth_confirmer.go
  core/config/general_config.go
  core/config/mocks/general_config.go
  core/config/v2/docs/secrets.toml
  core/config/v2/types.go
  core/gethwrappers/go_generate_test.go
  core/internal/testutils/evmtest/evmtest.go
  core/scripts/mercury/mercury.go
  core/services/chainlink/application.go
  core/services/chainlink/config_general_secrets.go
  core/services/chainlink/config_test.go
  core/services/chainlink/testdata/secrets-full-redacted.toml
  core/services/chainlink/testdata/secrets-full.toml
  core/services/directrequestocr/mocks/orm.go
  core/services/job/spawner.go
  core/services/ocr2/delegate.go
  core/services/pipeline/common.go
  core/services/pipeline/helpers_test.go
  core/services/pipeline/runner.go
  core/services/pipeline/task.eth_get_block.go
  core/services/pipeline/task.eth_get_block_test.go
  core/services/pipeline/task.lookup.go
  core/services/pipeline/task.lookup_test.go
  core/services/pipeline/task.memo.go
  core/services/relay/evm/evm.go
  core/services/relay/evm/median.go
  core/services/relay/evm/mercury/helpers_test.go
  core/services/relay/evm/mercury/report_codec.go
  core/services/relay/evm/mercury/report_codec_test.go
  core/services/relay/evm/mercury/transmitter.go
  core/services/relay/evm/mercury/transmitter_test.go
  core/services/relay/evm/ocr2keeper.go
  core/services/relay/evm/ocr2vrf.go
  core/services/relay/evm/types/types.go
  docs/SECRETS.md
  go.mod
  go.sum
Labels: do not merge

#7938 KeeperOCR: Enable forwarder flow
  core/services/ocr2/plugins/ocr2keeper/integration_test.go
  core/services/ocrcommon/transmitter_pipeline.go
  core/services/ocrcommon/transmitter_pipeline_test.go
Labels: ready for review

#7939 LVP to use timestamptz
  core/bridges/orm.go
  core/services/pipeline/task.bridge_test.go
  core/store/migrate/migrations/0151_bridge_last_good_value_use_tz.sql
Labels: ready for review

#7970 core/chains/evm/client: add SyncThreshold to mark nodes out-of-sync when behind; stick to one active node at a time
  core/chains/evm/client/client_test.go
  core/chains/evm/client/helpers_test.go
  core/chains/evm/client/node.go
  core/chains/evm/client/node_fsm.go
  core/chains/evm/client/node_lifecycle.go
  core/chains/evm/client/node_lifecycle_test.go
  core/chains/evm/client/node_selector_highest_head.go
  core/chains/evm/client/node_selector_highest_head_test.go
  core/chains/evm/client/node_selector_round_robin_test.go
  core/chains/evm/client/node_selector_total_difficulty.go
  core/chains/evm/client/node_selector_total_difficulty_test.go
  core/chains/evm/client/pool.go
  core/chains/evm/client/pool_test.go
  core/chains/evm/config/chain_specific_config.go
  core/chains/evm/config/config.go
  core/chains/evm/config/mocks/chain_scoped_config.go
  core/chains/evm/config/v2/chain_scoped.go
  core/chains/evm/config/v2/config.go
  core/chains/evm/config/v2/defaults/Arbitrum_Goerli.toml
  core/chains/evm/config/v2/defaults/Arbitrum_Mainnet.toml
  core/chains/evm/config/v2/defaults/Arbitrum_Rinkeby.toml
  core/chains/evm/config/v2/defaults/BSC_Mainnet.toml
  core/chains/evm/config/v2/defaults/Heco_Mainnet.toml
  core/chains/evm/config/v2/defaults/Metis_Mainnet.toml
  core/chains/evm/config/v2/defaults/Metis_Rinkeby.toml
  core/chains/evm/config/v2/defaults/Optimism_Alpha.toml
  core/chains/evm/config/v2/defaults/Optimism_Goerli.toml
  core/chains/evm/config/v2/defaults/Optimism_Kovan.toml
  core/chains/evm/config/v2/defaults/Optimism_Mainnet.toml
  core/chains/evm/config/v2/defaults/Polygon_Mainnet.toml
  core/chains/evm/config/v2/defaults/Polygon_Mumbai.toml
  core/chains/evm/config/v2/defaults/fallback.toml
  core/chains/evm/config/v2_helpers_test.go
  core/config/envvar/schema.go
  core/config/envvar/schema_test.go
  core/config/general_config.go
  core/config/mocks/general_config.go
  core/config/v2/docs/chains-evm.toml
  core/internal/testutils/testutils.go
  core/services/chainlink/cfgtest/dump/full-custom.env
  core/services/chainlink/cfgtest/dump/full-custom.toml
  core/services/chainlink/config_dump.go
  core/services/chainlink/config_general_global.go
  core/services/chainlink/config_test.go
  core/services/chainlink/testdata/config-full.toml
  core/services/chainlink/testdata/config-multi-chain-effective.toml
  core/web/resolver/testdata/config-full.toml
  core/web/resolver/testdata/config-multi-chain-effective.toml
  docs/CHANGELOG.md
  docs/CONFIG.md
Labels: ready for review

#7952 Allow same OCR2 contract on different chains
  core/services/job/job_orm_test.go
  core/services/job/orm.go
  core/services/job/util.go
  core/store/migrate/migrations/0152_ocr2_multichain.sql
  core/testdata/testspecs/v2_specs.go
  docs/CHANGELOG.md
Labels: ready for acceptance, ready for review

#7917 core/utils: add MailboxMonitor for Mailbox prometheus metrics
  core/chains/evm/chain.go
  core/chains/evm/chain_set.go
  core/chains/evm/gas/block_history_estimator.go
  core/chains/evm/headtracker/head_broadcaster.go
  core/chains/evm/headtracker/head_broadcaster_test.go
  core/chains/evm/headtracker/head_tracker.go
  core/chains/evm/headtracker/head_tracker_test.go
  core/chains/evm/log/broadcaster.go
  core/chains/evm/log/helpers_internal_test.go
  core/chains/evm/log/helpers_test.go
  core/chains/evm/log/integration_test.go
  core/chains/evm/txmgr/eth_confirmer.go
  core/cmd/client.go
  core/internal/cltest/cltest.go
  core/internal/testutils/evmtest/evmtest.go
  core/services/chainlink/application.go
  core/services/directrequest/delegate.go
  core/services/directrequest/delegate_test.go
  core/services/directrequestocr/drlistener.go
  core/services/directrequestocr/drlistener_test.go
  core/services/job/runner_integration_test.go
  core/services/job/spawner_test.go
  core/services/keeper/delegate.go
  core/services/keeper/registry_synchronizer_core.go
  core/services/keeper/registry_synchronizer_helper_test.go
  core/services/keeper/upkeep_executer.go
  core/services/ocr/contract_tracker.go
  core/services/ocr/contract_tracker_test.go
  core/services/ocr/delegate.go
  core/services/ocr2/delegate.go
  core/services/ocr2/plugins/directrequestocr/plugin.go
  core/services/promreporter/prom_reporter.go
  core/services/srvctest/servicetest.go
  core/services/vrf/delegate.go
  core/services/vrf/delegate_test.go
  core/services/vrf/listener_v1.go
  core/services/vrf/listener_v2.go
  core/utils/mailbox.go
  core/utils/mailbox_prom.go
  core/utils/mailbox_test.go
  docs/CHANGELOG.md
Labels: ready for review
