Repository smartcontractkit/chainlink, pull requests merged in 2022-02, with the labels that each got.

#5896 LockedDB
  core/cmd/local_client.go
  core/internal/testutils/configtest/general_config.go
  core/services/pg/locked_db.go
  core/services/pg/locked_db_test.go
Labels: ready for review

#5943 Estimate LINK needed in VRF V2 listener for possibly underfunded requests
  contracts/scripts/native_solc_compile_all
  core/internal/gethwrappers/generated/aggregator_v2v3_interface/aggregator_v2v3_interface.go
  core/internal/gethwrappers/generation/generated-wrapper-dependency-versions-do-not-edit.txt
  core/internal/gethwrappers/go_generate.go
  core/services/vrf/delegate.go
  core/services/vrf/listener_v2.go
  core/services/vrf/listener_v2_helpers_test.go
Labels: S-waiting-on-author

#5926 Report EVM account addresses with their associated chain id to FMS
  core/services/feeds/proto/feeds_manager.pb.go
  core/services/feeds/service.go
  core/services/feeds/service_test.go
Labels: ready for review

#5952 Fixes spelling mistakes and adds a linter
  .golangci.yml
  core/config/p2p_config.go
  core/services/blockhashstore/feeder.go
  core/sessions/webauthn.go
Labels: ready for review

#5936 core/chains/evm: broadcaster backfill from min pending block on resubscription
  core/services/log/broadcaster.go
Labels: ready for review, S-waiting-on-author

#5955 Send the new chain type to FMS which will enable future support of multi chain.
  core/services/feeds/proto/feeds_manager.pb.go
  core/services/feeds/service.go
  core/services/feeds/service_test.go
Labels: ready for review

#5956 feeds - replace job by address on approval
  core/services/feeds/service.go
  core/services/feeds/service_test.go
  core/services/job/job_orm_test.go
  core/services/job/mocks/orm.go
  core/services/job/orm.go
  operator_ui/src/screens/JobProposal/SpecsView.tsx
Labels: ready for review

#5959 Feeds Manager can be a bootstrap or they provide job types, but not both
  core/services/feeds/service.go
  core/services/feeds/service_test.go
  core/store/migrate/migrations/0098_fm_clear_job_types_from_bootstrap_nodes.sql
  core/web/feeds_manager_controller.go
  core/web/feeds_manager_controller_test.go
  core/web/resolver/feeds_manager.go
  core/web/resolver/feeds_manager_test.go
  core/web/resolver/mutation.go
  core/web/schema/type/feeds_manager.graphql
Labels: ready for review

#5998 Add a force option when approving a job to replace an existing job
  core/services/feeds/mocks/service.go
  core/services/feeds/service.go
  core/services/feeds/service_test.go
  core/web/resolver/job_proposal_spec.go
  core/web/resolver/job_proposal_spec_test.go
  core/web/resolver/mutation.go
  core/web/schema/schema.graphql
  core/web/schema/type/job_proposal_spec.graphql
Labels: ready for review

#6014 Bootstrap job migration & config fix
  core/internal/features_ocr2_test.go
  core/services/job/models.go
  core/services/job/orm.go
  core/services/ocrbootstrap/database.go
  core/services/ocrbootstrap/database_test.go
  core/services/ocrbootstrap/delegate.go
  core/services/offchainreporting2/database_test.go
  core/services/offchainreporting2/delegate.go
  core/services/offchainreporting2/validate.go
  core/services/offchainreporting2/validate_test.go
  core/services/relay/delegate.go
  core/services/relay/delegate_test.go
  core/store/migrate/migrate_test.go
  core/store/migrate/migrations/0100_bootstrap_config.sql
  core/web/presenters/job.go
  core/web/resolver/spec.go
  core/web/resolver/spec_test.go
  core/web/schema/type/spec.graphql
  docs/CHANGELOG.md
  operator_ui/src/screens/Job/JobView.tsx
  operator_ui/src/screens/Job/generateJobDefinition.test.ts
  operator_ui/src/screens/Job/generateJobDefinition.ts
Labels: S-waiting-on-author

#6050 tools/bin: update go_core_race_tests and add to CI matrix
  .github/workflows/continuous-integration-workflow.yml
  .gitignore
  tools/bin/go_core_race_tests
Labels: ready for review

#6057 GNUmakefile: document commands for help list
  GNUmakefile
Labels: ready for review

#6058 core/services/pipeline: scheduler vars copy
  core/services/pipeline/scheduler.go
Labels: ready for review

#6056 go.mod update geth, cbor, pgconn, exchain
  core/chains/evm/bulletprooftxmanager/bulletprooftxmanager.go
  core/internal/gethwrappers/generation/generated-wrapper-dependency-versions-do-not-edit.txt
  go.mod
  go.sum
Labels: ready for review

#5960 core/logger: godoc levels
  core/logger/logger.go
Labels: ready for review

#6052 core/chains/terra/monitor: add Terra BalanceMonitor
  core/chains/evm/chain.go
  core/chains/evm/mocks/chain.go
  core/chains/evm/monitor/balance.go
  core/chains/evm/monitor/balance_test.go
  core/chains/terra/chain.go
  core/chains/terra/denom/denom.go
  core/chains/terra/denom/denom_test.go
  core/chains/terra/monitor/balance.go
  core/chains/terra/monitor/balance_test.go
  core/chains/terra/monitor/prom.go
Labels: ready for review

#6073 `evm/*` services to become `ServiceCtx`
  core/chains/evm/bulletprooftxmanager/bulletprooftxmanager.go
  core/chains/evm/bulletprooftxmanager/bulletprooftxmanager_test.go
  core/chains/evm/bulletprooftxmanager/eth_broadcaster.go
  core/chains/evm/bulletprooftxmanager/eth_broadcaster_test.go
  core/chains/evm/bulletprooftxmanager/mocks/tx_manager.go
  core/chains/evm/chain.go
  core/chains/evm/gas/block_history_estimator.go
  core/chains/evm/gas/block_history_estimator_test.go
  core/chains/evm/gas/fixed_price_estimator.go
  core/chains/evm/gas/mocks/estimator.go
  core/chains/evm/gas/models.go
  core/chains/evm/gas/optimism_estimator.go
  core/chains/evm/gas/optimism_estimator_test.go
  core/chains/evm/headtracker/head_broadcaster.go
  core/chains/evm/headtracker/head_broadcaster_test.go
  core/chains/evm/headtracker/head_tracker_test.go
  core/chains/evm/headtracker/mocks/head_broadcaster.go
  core/chains/evm/headtracker/types/types.go
  core/chains/evm/log/broadcaster.go
  core/chains/evm/log/helpers_test.go
  core/chains/evm/log/mocks/broadcaster.go
  core/chains/evm/mocks/balance_monitor.go
  core/chains/evm/mocks/chain.go
  core/chains/evm/monitor/balance.go
  core/chains/evm/monitor/balance_test.go
  core/services/ocr/mocks/ocr_contract_tracker_db.go
Labels: ready for review

#5941 Logging storage in disk - rotatelogs
  .dockerignore
  .github/workflows/continuous-integration-workflow.yml
  core/chains/evm/config/mocks/chain_scoped_config.go
  core/cmd/client.go
  core/cmd/local_client.go
  core/cmd/local_client_test.go
  core/config/envvar/envvar.go
  core/config/envvar/schema.go
  core/config/envvar/schema_test.go
  core/config/general_config.go
  core/config/mocks/general_config.go
  core/config/presenters.go
  core/internal/cltest/cltest.go
  core/internal/testutils/configtest/general_config.go
  core/logger/logger.go
  core/logger/logger_unix.go
  core/logger/logger_windows.go
  core/logger/model.go
  core/logger/orm.go
  core/logger/test_logger.go
  core/logger/zap.go
  core/logger/zap_disk_logging.go
  core/logger/zap_test.go
  core/main.go
  core/main_test.go
  core/scripts/chaincli/handler/keeper.go
  core/scripts/chaincli/handler/keeper_launch.go
  core/services/chainlink/application.go
  core/utils/disk_stats.go
  core/utils/mocks/disk_stats_provider.go
  core/web/resolver/config_test.go
  docs/CHANGELOG.md
  go.mod
  go.sum
  tools/clroot/.gitignore
Labels: S-waiting-on-author

#6072 Assert feecoin bridges exist in OCR2 on job create
  core/bridges/bridge_type.go
  core/bridges/mocks/orm.go
  core/bridges/orm.go
  core/bridges/orm_test.go
  core/chains/evm/headtracker/orm_test.go
  core/cmd/bridge_commands_test.go
  core/internal/cltest/factories.go
  core/internal/features_ocr2_test.go
  core/internal/features_test.go
  core/services/job/orm.go
  core/services/job/runner_integration_test.go
  core/services/ocr/config.go
  core/services/ocr/validate_test.go
  core/services/ocr2/config.go
  core/services/ocr2/database_test.go
  core/services/ocr2/mocks/config.go
  core/services/ocr2/plugins/median/config/config.go
  core/services/ocr2/plugins/median/plugin.go
  core/services/ocr2/validate_test.go
  core/services/pipeline/orm.go
  core/services/vrf/vrf_hash_to_curve_cost_test.go
  core/web/bridge_types_controller.go
  core/web/bridge_types_controller_test.go
  core/web/health_controller_test.go
  core/web/resolver/bridge_test.go
  core/web/resolver/evm_chain_test.go
  core/web/resolver/helpers.go
  core/web/resolver/mutation.go
  core/web/resolver/query.go
Labels: S-waiting-on-author

#6047 core/chains/evm/log: prioritize replay requests
  core/chains/evm/log/broadcaster.go
  core/chains/evm/log/eth_subscriber.go
Labels: ready for review

#6093 core/logger: add critical color; dedupe
  core/logger/internal/colortest/prettyconsole_test.go
  core/logger/prettyconsole.go
  core/logger/zap.go
Labels: ready for review
