Repository smartcontractkit/chainlink, pull requests merged in 2022-03, with the labels that each got.

#6109 bump sentry-go, pgx, gopsutil, integrations-framework
  go.mod
  go.sum
Labels: ready for review

#6098 dependabot: ignore libp2p
  .github/dependabot.yml
Labels: ready for review

#6121 upgrade ginprom, gorilla/websocket, ginkgo, goose
  go.mod
  go.sum
Labels: ready for review

#6089 LogBroadcaster: force broadcast option
  core/chains/evm/log/broadcaster.go
  core/chains/evm/log/integration_test.go
  core/chains/evm/log/mocks/broadcaster.go
  core/chains/evm/log/mocks/orm.go
  core/chains/evm/log/orm.go
  core/chains/evm/log/orm_test.go
  core/cmd/app.go
  core/cmd/remote_client.go
  core/internal/mocks/application.go
  core/services/chainlink/application.go
  core/store/migrate/migrations/0102_add_log_broadcasts_block_num_chain_idx.sql
  core/web/replay_controller.go
  docs/CHANGELOG.md
Labels: ready for review

#6003 core: add txs terra create
  core/chains/terra/chain.go
  core/chains/terra/chain_set.go
  core/chains/terra/denom/denom.go
  core/chains/terra/mocks/chain.go
  core/chains/terra/mocks/msg_enqueuer.go
  core/chains/terra/mocks/tx_manager.go
  core/chains/terra/terratxm/orm.go
  core/chains/terra/terratxm/orm_test.go
  core/chains/terra/terratxm/txm.go
  core/chains/terra/terratxm/txm_internal_test.go
  core/chains/terra/terratxm/txm_test.go
  core/cmd/app.go
  core/cmd/evm_transaction_commands.go
  core/cmd/evm_transaction_commands_test.go
  core/cmd/terra_chains_commands_test.go
  core/cmd/terra_commands_test.go
  core/cmd/terra_node_commands_test.go
  core/cmd/terra_transaction_commands.go
  core/cmd/terra_transaction_commands_test.go
  core/internal/cltest/cltest.go
  core/internal/mocks/application.go
  core/internal/testutils/configtest/general_config.go
  core/internal/testutils/terratest/terratest.go
  core/main_test.go
  core/services/chainlink/application.go
  core/services/relay/delegate_test.go
  core/store/migrate/migrations/0103_terra_msgs_type_url.sql
  core/store/models/terra/common.go
  core/utils/utils.go
  core/web/evm_transactions_controller.go
  core/web/evm_transactions_controller_test.go
  core/web/evm_transfer_controller.go
  core/web/evm_transfer_controller_test.go
  core/web/evm_tx_attempts_controller.go
  core/web/evm_tx_attempts_controller_test.go
  core/web/presenters/eth_tx.go
  core/web/presenters/eth_tx_test.go
  core/web/presenters/terra_msg.go
  core/web/router.go
  core/web/terra_chains_controller.go
  core/web/terra_chains_controller_test.go
  core/web/terra_nodes_controller.go
  core/web/terra_transfer_controller.go
  go.mod
  go.sum
Labels: ready for review, S-waiting-on-author

#6152 core/services/fluxmonitorv2: FluxMonitor fmt.Formatter hack to resolve mock race
  core/services/fluxmonitorv2/helpers_test.go
  tools/bin/go_core_race_tests
Labels: ready for review

#6146 Fix rare issue where transactions can be underpriced in EIP-1559 mode
  core/chains/evm/bulletprooftxmanager/bulletprooftxmanager_test.go
  core/chains/evm/bulletprooftxmanager/eth_broadcaster.go
  core/chains/evm/bulletprooftxmanager/eth_broadcaster_test.go
  core/chains/evm/config/chain_specific_config.go
  core/chains/evm/config/config.go
  core/chains/evm/gas/block_history_estimator_test.go
  core/internal/testutils/testutils.go
Labels: ready for review

#6161 Update wsrpc to 0.3.9
  go.mod
  go.sum
Labels: ready for review

#6038 Logging improvements; several minor bptxm bugfixes
  core/chains/evm/bulletprooftxmanager/common.go
  core/chains/evm/bulletprooftxmanager/eth_confirmer.go
  core/chains/evm/bulletprooftxmanager/eth_confirmer_test.go
  core/chains/evm/bulletprooftxmanager/eth_resender.go
  core/chains/evm/bulletprooftxmanager/eth_resender_test.go
  core/chains/evm/bulletprooftxmanager/reaper.go
  core/chains/evm/client/client.go
  core/chains/evm/client/node.go
  core/chains/evm/client/null_client.go
  core/chains/evm/client/pool.go
  core/chains/evm/client/pool_test.go
  core/chains/evm/client/simulated_backend.go
  core/chains/evm/gas/block_history_estimator.go
  core/chains/evm/mocks/client.go
  core/services/blockhashstore/delegate.go
  core/services/pipeline/runner.go
Labels: S-waiting-on-author

#6215 contracts: Add VRF load testing contracts
  contracts/scripts/native_solc_compile_all
  contracts/src/v0.8/tests/VRFLoadTestExternalSubOwner.sol
  contracts/src/v0.8/tests/VRFLoadTestOwnerlessConsumer.sol
  core/internal/gethwrappers/generated/vrf_load_test_external_sub_owner/vrf_load_test_external_sub_owner.go
  core/internal/gethwrappers/generated/vrf_load_test_ownerless_consumer/vrf_load_test_ownerless_consumer.go
  core/internal/gethwrappers/generation/generated-wrapper-dependency-versions-do-not-edit.txt
  core/internal/gethwrappers/go_generate.go
  core/scripts/vrfv1/main.go
  core/scripts/vrfv2/testnet/main.go
Labels: S-waiting-on-author

#6223 Added deviation to used gas checks
  contracts/test/v0.8/dev/ArbitrumSequencerUptimeFeed.test.ts
Labels: ready for review

#6277 Add upkeepID logging to each step in job pipeline
  core/chains/evm/txmgr/eth_broadcaster.go
  core/chains/evm/txmgr/models.go
  core/chains/evm/txmgr/transmitchecker_test.go
  core/chains/evm/txmgr/txmgr_test.go
  core/services/keeper/validate.go
  core/services/keeper/validate_test.go
  core/services/vrf/listener_v2.go
  core/services/vrf/listener_v2_test.go
  core/store/migrate/migrations/0108_upgrade_keepers_tx_meta.sql
  core/testdata/testspecs/v2_specs.go
  integration-tests/go.mod
  integration-tests/go.sum
Labels: S-waiting-on-author

#6245 Fix "Request already fulfilled" before the request is actually fulfilled
  core/chains/evm/txmgr/models.go
  core/chains/evm/txmgr/transmitchecker.go
  core/chains/evm/txmgr/transmitchecker_test.go
  core/services/vrf/listener_v2.go
  core/utils/big_math/big_math.go
  core/utils/big_math/big_math_test.go
Labels: S-waiting-on-author

#5759 core/services/pipeline: refactor for fuzzing; add FuzzParseETHABIArgsString
  core/services/pipeline/common_eth_fuzz_test.go
  core/services/pipeline/task.eth_abi_decode_test.go
Labels: S-waiting-on-author
