Repository smartcontractkit/chainlink, pull requests merged in 2022-01, with the labels that each got.

#5704 Remove unused env vars and re-organise to match documentation layout
  core/chains/evm/config/config.go
  core/chains/evm/config/mocks/chain_scoped_config.go
  core/cmd/local_client_test.go
  core/cmd/remote_client_test.go
  core/config/envvar/schema.go
  core/config/envvar/schema_test.go
  core/config/general_config.go
  core/config/mocks/general_config.go
  core/config/presenters.go
  core/internal/testutils/configtest/general_config.go
  core/services/bulletprooftxmanager/bulletprooftxmanager.go
  core/services/chainlink/application.go
  core/services/job/job_pipeline_orm_integration_test.go
  core/services/keystore/mocks/terra.go
  core/services/log/mocks/config.go
  core/services/pipeline/common.go
  core/services/pipeline/mocks/config.go
  core/services/pipeline/runner.go
  core/services/synchronization/explorer_client.go
  core/services/synchronization/explorer_client_test.go
  core/web/pipeline_runs_controller_test.go
  core/web/resolver/config_test.go
  tools/docker/docker-compose.yaml
Labels: ready for review, S-waiting-on-author

#5720 head_tracker refactoring
  core/chains/evm/chain.go
  core/chains/evm/chain_set.go
  core/chains/evm/mocks/chain.go
  core/internal/testutils/evmtest/evmtest.go
  core/services/headtracker/head_broadcaster_test.go
  core/services/headtracker/head_listener.go
  core/services/headtracker/head_saver.go
  core/services/headtracker/head_saver_test.go
  core/services/headtracker/head_tracker.go
  core/services/headtracker/head_tracker_test.go
  core/services/headtracker/mocks/head_listener.go
  core/services/headtracker/mocks/head_tracker.go
  core/services/headtracker/types/types.go
Labels: ready for review

#5426 Automatically add edges between tasks
  core/services/job/job_pipeline_orm_integration_test.go
  core/services/pipeline/common.go
  core/services/pipeline/graph.go
  core/services/pipeline/graph_test.go
  core/services/pipeline/helpers_test.go
  core/services/pipeline/scheduler.go
  core/services/pipeline/task.base.go
  core/services/pipeline/test_helpers_test.go
Labels: S-waiting-on-author

#5776 HT: fixed flacky test
  core/chains/evm/headtracker/head_tracker_test.go
Labels: ready for review

#5783 Implement mutation to create OCR2 key bundles
  core/web/resolver/mutation.go
  core/web/resolver/ocr2_keys_test.go
  core/web/resolver/orc2_keys.go
  core/web/schema/schema.graphql
  core/web/schema/type/orc2_keys.graphql
Labels: S-waiting-on-author

#5707 Prevent "too high" values to be sent via `txs create` CLI command
  core/assets/currencies.go
  core/chains/evm/bulletprooftxmanager/bulletprooftxmanager.go
  core/chains/evm/bulletprooftxmanager/bulletprooftxmanager_test.go
  core/chains/evm/bulletprooftxmanager/mocks/tx_manager.go
  core/chains/evm/bulletprooftxmanager/mocks/tx_strategy.go
  core/cmd/app.go
  core/cmd/remote_client_test.go
  core/cmd/transaction_commands.go
  core/cmd/transaction_commands_test.go
  core/internal/cltest/cltest.go
  core/main_test.go
  core/store/models/common.go
  core/web/resolver/eth_key.go
  core/web/transfer_controller.go
  core/web/transfer_controller_test.go
Labels: S-waiting-on-author

#5779 Terra relay integration bugs
  core/chainlink.Dockerfile
  core/chains/terra/terratxm/txm.go
  core/services/keystore/keys/ocr2key/terra_keyring.go
  core/services/keystore/keys/ocr2key/terra_keyring_test.go
  core/services/keystore/models_test.go
  core/services/keystore/ocr2_test.go
Labels: S-waiting-on-author

#5797 terra ChainSet
  core/chains/terra/orm.go
  core/chains/terra/orm_test.go
  core/chains/terra/terratxm/orm.go
  core/chains/terra/terratxm/txm.go
  core/chains/terra/types/chain.go
  core/chains/terra/types/chain_set.go
  core/chains/terra/types/mocks/chain_set.go
  core/chains/terra/types/types.go
  core/services/chainlink/application.go
  core/services/relay/delegate.go
  core/services/relay/delegate_test.go
  go.mod
  go.sum
Labels: S-waiting-on-author

#5564 Adds Non-Blocking Integration Tests to CI
  .github/workflows/dependency-check.yml
  .github/workflows/integration-tests.yml
  .gitignore
  .nancy-ignore
  CODEOWNERS
  GNUmakefile
  core/README.md
  go.mod
  go.sum
  integration-tests/README.md
  integration-tests/framework.yaml
  integration-tests/networks.yaml
  integration-tests/smoke/cron_test.go
  integration-tests/smoke/flux_test.go
  integration-tests/smoke/keeper_test.go
  integration-tests/smoke/ocr_test.go
  integration-tests/smoke/runlog_test.go
  integration-tests/smoke/suite_test.go
  integration-tests/smoke/vrf_test.go
Labels: github_actions

#5841 core/services/relay: add minimal terra ocr2 spec test
  .github/workflows/golangci-lint.yml
  core/chains/terra/chain.go
  core/chains/terra/mocks/chain.go
  core/chains/terra/mocks/msg_enqueuer.go
  core/chains/terra/mocks/reader.go
  core/chains/terra/types/mocks/chain_set.go
  core/services/relay/delegate_test.go
  core/testdata/testspecs/v2_specs.go
  go.mod
  go.sum
  integration-tests/smoke/ocr_test.go
Labels: ready for review

#5834 Improve terra gas price reliability
  core/chains/terra/chain.go
  core/chains/terra/terratxm/txm.go
  core/chains/terra/terratxm/txm_internal_test.go
  core/chains/terra/terratxm/txm_test.go
  core/web/assets/index.html
  go.mod
  go.sum
Labels: S-waiting-on-author

#5818 Revert "migrate to cosmos sdk for terra keys"
  core/services/keystore/keys/ocr2key/terra_key_bundle.go
  core/services/keystore/keys/ocr2key/terra_keyring.go
  core/services/keystore/keys/ocr2key/terra_keyring_test.go
  core/services/keystore/models_test.go
  go.mod
Labels: do-not-merge-yet, S-waiting-on-author

#5879 Feature flags for Solana/Terra; clean up EVM_DISABLED confusion
  core/chains/evm/chain.go
  core/chains/evm/chain_set.go
  core/chains/evm/config/mocks/chain_scoped_config.go
  core/cmd/client.go
  core/cmd/csa_keys_commands_test.go
  core/cmd/eth_keys_commands_test.go
  core/cmd/evm_chains_commands_test.go
  core/cmd/jobs_commands_test.go
  core/cmd/local_client.go
  core/cmd/local_client_test.go
  core/cmd/ocr_keys_commands_test.go
  core/cmd/p2p_keys_commands_test.go
  core/cmd/remote_client_test.go
  core/cmd/transaction_commands_test.go
  core/config/config_internal_test.go
  core/config/envvar/schema.go
  core/config/envvar/schema_test.go
  core/config/general_config.go
  core/config/mocks/general_config.go
  core/config/presenters.go
  core/internal/cltest/cltest.go
  core/internal/features_test.go
  core/internal/testutils/configtest/general_config.go
  core/services/chainlink/application.go
  core/services/feeds/proto/feeds_manager.pb.go
  core/services/feeds/service_test.go
  core/services/keystore/eth.go
  core/services/keystore/master.go
  core/services/keystore/mocks/eth.go
  core/services/keystore/mocks/master.go
  core/services/offchainreporting/validate_test.go
  core/services/offchainreporting2/validate_test.go
  core/services/relay/delegate.go
  core/services/relay/delegate_test.go
  core/services/relay/types/relay.go
  core/store/migrate/migrations/0056_multichain.go
  core/web/cors_test.go
  core/web/jobs_controller_test.go
  core/web/log_controller_test.go
  core/web/pipeline_runs_controller_test.go
  core/web/resolver/config_test.go
  docs/CHANGELOG.md
Labels: ready for review, S-waiting-on-author

#5827 Graceful shutdown
  core/chains/evm/config/mocks/chain_scoped_config.go
  core/cmd/app.go
  core/cmd/client.go
  core/cmd/local_client.go
  core/cmd/local_client_test.go
  core/config/envvar/schema.go
  core/config/envvar/schema_test.go
  core/config/general_config.go
  core/config/mocks/general_config.go
  core/config/presenters.go
  core/internal/cltest/cltest.go
  core/internal/cltest/mocks.go
  core/internal/testutils/configtest/general_config.go
  core/main_test.go
  core/services/chainlink/application.go
  core/services/chainlink/application_test.go
  core/services/job/orm.go
  core/services/pg/advisory_lock.go
  core/services/pg/advisory_lock_test.go
  core/services/pg/lease_lock.go
  core/services/pg/lease_lock_test.go
  core/shutdown/channel.go
  core/shutdown/shutdown.go
  core/shutdown/shutdown_test.go
  core/web/resolver/config_test.go
  docs/CHANGELOG.md
Labels: ready for review

#5873 Modify EIP-1559 implementation to allow gas bumping
  core/chains/evm/bulletprooftxmanager/eth_broadcaster_test.go
  core/chains/evm/bulletprooftxmanager/eth_confirmer_test.go
  core/chains/evm/bulletprooftxmanager/mocks/config.go
  core/chains/evm/config/chain_specific_config.go
  core/chains/evm/config/config.go
  core/chains/evm/config/mocks/chain_scoped_config.go
  core/chains/evm/gas/block_history_estimator.go
  core/chains/evm/gas/block_history_estimator_test.go
  core/chains/evm/gas/fixed_price_estimator.go
  core/chains/evm/gas/fixed_price_estimator_test.go
  core/chains/evm/gas/gas_test.go
  core/chains/evm/gas/helpers_test.go
  core/chains/evm/gas/mocks/config.go
  core/chains/evm/gas/models.go
  core/chains/evm/types/types.go
  core/config/envvar/schema.go
  core/config/envvar/schema_test.go
  core/config/general_config.go
  core/config/mocks/general_config.go
  core/internal/testutils/configtest/general_config.go
  core/services/vrf/integration_v2_test.go
  docs/CHANGELOG.md
Labels: S-waiting-on-author
