Repository smartcontractkit/chainlink, pull requests merged in 2023-01, with the labels that each got.

#8190 ocr2vrf script improvement for multi chain support
  core/cmd/ocr2vrf_configure_commands.go
  core/scripts/ocr2vrf/setup_dkg.go
  core/scripts/ocr2vrf/setup_ocr2vrf.go
  core/scripts/ocr2vrf/util.go
  core/services/ocr2/delegate.go
Labels: do not merge

#8214 Bugfix/scope findjobidbyaddress network
  core/services/feeds/service.go
  core/services/feeds/service_test.go
  core/services/job/job_orm_test.go
  core/services/job/mocks/orm.go
  core/services/job/orm.go
Labels: draft

#7907 .github: new job to ensure clean go mod tidy & generate
  .github/workflows/ci-core.yml
  core/internal/gethwrappers2/compile.sh
  core/internal/gethwrappers2/generated/accesscontrolledoffchainaggregator/accesscontrolledoffchainaggregator.go
  core/internal/gethwrappers2/generated/accesscontroltesthelper/accesscontroltesthelper.go
  core/internal/gethwrappers2/generated/exposedoffchainaggregator/exposedoffchainaggregator.go
  core/internal/gethwrappers2/generated/ocrtitlerequest/ocrtitlerequest.go
  core/internal/gethwrappers2/generated/testoffchainaggregator/testoffchainaggregator.go
  core/internal/gethwrappers2/generated/testvalidator/testvalidator.go
  core/internal/gethwrappers2/generation/generated-wrapper-dependency-versions-do-not-edit.txt
  core/internal/gethwrappers2/go_generate.go
Labels: ready for review
