Repository smartcontractkit/chainlink, pull requests merged in 2024-01, with the labels that each got.

#11750 Run Argo CD app sync after image is published from PR
  .github/workflows/build-publish-pr.yml
  test.txt
Labels: github_actions, crib

#11771 Re-add network policies back to helm chart and fix node egress
  charts/chainlink-cluster/devspace.yaml
  charts/chainlink-cluster/templates/chainlink-db-networkpolicy.yaml
  charts/chainlink-cluster/templates/chainlink-node-networkpolicy.yaml
  charts/chainlink-cluster/templates/geth-deployment.yaml
  charts/chainlink-cluster/templates/geth-networkpolicy.yaml
  charts/chainlink-cluster/templates/mockserver-networkpolicy.yaml
  charts/chainlink-cluster/templates/networkpolicy-default-deny.yaml
  charts/chainlink-cluster/templates/runner-networkpolicy.yaml
Labels: crib

#11817 Add role label to nodes in chart
  charts/chainlink-cluster/templates/chainlink-node-deployment.yaml
Labels: crib

#11829 Support custom ingress rules on the chart to support external Ingress
  charts/chainlink-cluster/templates/networkpolicy-default-deny.yaml
  charts/chainlink-cluster/templates/networkpolicy-default.yaml
  charts/chainlink-cluster/values.yaml
Labels: crib

#11908 Setup ingress for all paths to load assets to support Operator UI
  charts/chainlink-cluster/templates/ingress.yaml
Labels: crib

#11902 log but not return error when pushing to metrics fails
  core/services/feeds/service.go
Labels: ready for review
