Repository smartcontractkit/chainlink, pull requests merged in 2025-04, with the labels that each got.

#17065 [chore] Fix heartbeat metric
  core/services/workflows/engine.go
  core/services/workflows/monitoring.go
Labels: build-publish

#17026 feat: runs-on rollout part 1 (DX-365)
  .github/actions/setup-go/action.yml
  .github/runs-on.yml
  .github/workflows/ci-core.yml
Labels: runs-on

#17009 feat(capabilities): start gateway connection attempts with random node
  .changeset/chatty-carpets-stare.md
  core/capabilities/compute/compute_test.go
  core/capabilities/webapi/outgoing_connector_handler.go
  core/capabilities/webapi/outgoing_connector_handler_test.go
  core/capabilities/webapi/round_robin_selector.go
  core/capabilities/webapi/round_robin_selector_test.go
  core/capabilities/webapi/target/target_test.go
  core/services/standardcapabilities/delegate.go
  core/services/workflows/engine_test.go
  core/services/workflows/syncer/fetcher.go
  core/services/workflows/syncer/fetcher_test.go
Labels: build-publish

#17105 [CAPPL-685] Add headers to gateway client
  core/capabilities/compute/compute.go
  core/capabilities/compute/compute_test.go
  core/capabilities/integration_tests/por/fetchtrueusd_test.go
  core/scripts/go.mod
  core/scripts/go.sum
  core/services/gateway/network/httpclient.go
  core/services/gateway/network/httpclient_test.go
  deployment/go.mod
  deployment/go.sum
  go.mod
  go.sum
  integration-tests/go.mod
  integration-tests/go.sum
  integration-tests/load/go.mod
  integration-tests/load/go.sum
  system-tests/lib/go.mod
  system-tests/lib/go.sum
  system-tests/tests/go.mod
  system-tests/tests/go.sum
Labels: build-publish

#17074 Patch cre encode nil error + add telemetry logging
  core/services/llo/cre/report_codec.go
  core/services/llo/telem/telemetry.go
Labels: build-publish

#17104 feat: optimize runs-on
  .github/workflows/ci-core.yml
Labels: runs-on

#17157 feat: runs-on 10% allocation
  .github/workflows/ci-core.yml
Labels: runs-on

#17149 Update Solana CCIP contracts [NONEVM-1500]
  core/capabilities/ccip/configs/solana/chain_writer.go
  core/scripts/go.mod
  core/scripts/go.sum
  deployment/ccip/changeset/solana/cs_deploy_chain.go
  deployment/ccip/changeset/solana/cs_token_pool.go
  deployment/ccip/changeset/testhelpers/test_helpers.go
  deployment/go.mod
  deployment/go.sum
  go.mod
  go.sum
  integration-tests/go.mod
  integration-tests/go.sum
  integration-tests/load/ccip/destination_gun.go
  integration-tests/load/go.mod
  integration-tests/load/go.sum
  integration-tests/smoke/ccip/ccip_messaging_test.go
  integration-tests/smoke/ccip/ccip_token_transfer_test.go
  system-tests/lib/go.mod
  system-tests/lib/go.sum
  system-tests/tests/go.mod
  system-tests/tests/go.sum
Labels: runs-on

#17201 0s blocks + custom miner in environment setup
  system-tests/tests/smoke/cre/environment-capabilities-don-ci.toml
  system-tests/tests/smoke/cre/environment-capabilities-don-crib.toml
  system-tests/tests/smoke/cre/environment-capabilities-don.toml
  system-tests/tests/smoke/cre/environment-gateway-don-ci.toml
  system-tests/tests/smoke/cre/environment-gateway-don.toml
  system-tests/tests/smoke/cre/environment-one-don-ci.toml
  system-tests/tests/smoke/cre/environment-one-don.toml
  system-tests/tests/smoke/cre/guidelines.md
  system-tests/tests/smoke/cre/por_test.go
Labels: runs-on-opt-out

#17207 fix: runs-on stability
  .github/workflows/ci-core.yml
Labels: runs-on

#17212 fix: runs-on mount /tmp
  .github/workflows/ci-core.yml
Labels: runs-on

#17184 feat: runs-on 25% allocation
  .github/workflows/ci-core.yml
Labels: runs-on

#17219 core/capabilities/ccip: correct telem type in monitor endpoint
  core/capabilities/ccip/oraclecreator/plugin.go
  core/capabilities/ccip/oraclecreator/plugin_test.go
Labels: runs-on

#17114 [DEVSVCS-1559] CORS support for Testnet Gateways
  .changeset/ripe-mice-drop.md
  core/scripts/gateway/sample_config.toml
  core/scripts/gateway/sample_config_tls.toml
  core/services/gateway/integration_tests/gateway_integration_test.go
  core/services/gateway/network/httpserver.go
  core/services/gateway/network/httpserver_test.go
  core/testdata/testspecs/v2_specs.go
  system-tests/lib/cre/don/jobs/definitions.go
Labels: runs-on

#17222 [DX-464] Check for notification working
  .github/workflows/integration-tests.yml
Labels: runs-on

#17227 feat: runs-on scheduled events
  .github/workflows/ci-core.yml
Labels: runs-on

#17218 fix(operations): introduce util function to convert to generic type
  deployment/operations/report.go
  deployment/operations/report_test.go
Labels: runs-on

#17232 fix: runs-on tmp mount
  .github/workflows/ci-core.yml
Labels: runs-on

#17234 [DX-482] No longer run Integration Tests on PRs
  .github/e2e-tests.yml
  .github/workflows/integration-tests.yml
Labels: runs-on, run-e2e-tests

#17248 chore: optimize go build cache
  .github/actions/setup-go/action.yml
  .github/workflows/ci-core.yml
Labels: runs-on

#17237 Update solana ref to pull in 3 changes needed for 2.23
  .changeset/spotty-donkeys-punch.md
  core/cmd/shell_test.go
  core/config/docs/chains-solana.toml
  core/scripts/go.mod
  core/scripts/go.sum
  core/services/chainlink/config_test.go
  core/services/chainlink/relayer_chain_interoperators_test.go
  core/services/chainlink/testdata/config-full.toml
  core/services/chainlink/testdata/config-multi-chain-effective.toml
  core/web/chains_controller_test.go
  core/web/resolver/testdata/config-full.toml
  core/web/resolver/testdata/config-multi-chain-effective.toml
  deployment/go.mod
  deployment/go.sum
  docs/CONFIG.md
  go.mod
  go.sum
  integration-tests/go.mod
  integration-tests/go.sum
  integration-tests/load/go.mod
  integration-tests/load/go.sum
  system-tests/lib/go.mod
  system-tests/lib/go.sum
  system-tests/tests/go.mod
  system-tests/tests/go.sum
Labels: runs-on

#17233 Log retentions 1.6
  core/capabilities/ccip/configs/evm/contract_reader.go
Labels: runs-on

#17253 chore(datastore): add t.Parallel() to all datastore tests
  deployment/datastore/address_ref_key_test.go
  deployment/datastore/address_ref_test.go
  deployment/datastore/contract_metadata_key_test.go
  deployment/datastore/contract_metadata_test.go
  deployment/datastore/env_metadata_key_test.go
  deployment/datastore/env_metadata_test.go
  deployment/datastore/filters_test.go
  deployment/datastore/label_set_test.go
  deployment/datastore/memory_address_ref_store_test.go
  deployment/datastore/memory_contract_metadata_store_test.go
  deployment/datastore/memory_datastore_test.go
  deployment/datastore/memory_env_metadata_store_test.go
Labels: runs-on

#17241 fix registration of web API capabilities and make DF cache optional w…
  system-tests/lib/cre/contracts/contracts.go
  system-tests/lib/cre/don/jobs/webapi/webapi.go
  system-tests/lib/crecli/settings.go
Labels: runs-on-opt-out

#17226 deployment/ccip/manualexechelpers: performance improvements
  deployment/ccip/manualexechelpers/exec.go
  deployment/ccip/manualexechelpers/exec_test.go
  integration-tests/smoke/ccip/ccip_messaging_test.go
Labels: runs-on

#17179 Add TokenPoolFactory deployment changeset
  deployment/ccip/changeset/cs_prerequisites.go
  deployment/ccip/changeset/cs_prerequisites_test.go
  deployment/ccip/changeset/state.go
  deployment/ccip/changeset/testhelpers/test_environment.go
  deployment/ccip/changeset/token_info.go
  deployment/ccip/changeset/v1_5_1/cs_deploy_token_pool_factory.go
  deployment/ccip/changeset/v1_5_1/cs_deploy_token_pool_factory_test.go
  deployment/ccip/view/v1_5_1/token_pool_factory.go
  deployment/ccip/view/view.go
Labels: runs-on

#17274 do not require cron binary in test config
  system-tests/tests/smoke/cre/por_test.go
Labels: runs-on

#17279 Update CCIP v1.5 release testing toml according to current env status
  integration-tests/ccip-tests/testconfig/tomls/beta-testnet/testnet-beta-workinglane.toml
  integration-tests/ccip-tests/testconfig/tomls/beta-testnet/testnet-beta-workinglane_native.toml
  integration-tests/ccip-tests/testconfig/tomls/prod-testnet/smoke-release-testing_native.toml
  integration-tests/ccip-tests/testconfig/tomls/prod-testnet/smoke-release-testing_token_transfer_native.toml
  integration-tests/ccip-tests/testconfig/tomls/prod-testnet/soak-release-testing_token_transfer_with_native_feetoken.toml
Labels: runs-on

#17272 Bump chainlink-solana with the logpoller fix
  core/scripts/go.mod
  core/scripts/go.sum
  deployment/go.mod
  deployment/go.sum
  go.mod
  go.sum
  integration-tests/go.mod
  integration-tests/go.sum
  integration-tests/load/go.mod
  integration-tests/load/go.sum
  system-tests/lib/go.mod
  system-tests/lib/go.sum
  system-tests/tests/go.mod
  system-tests/tests/go.sum
Labels: runs-on

#17271 feat: runs-on 75% allocation
  .github/workflows/ci-core.yml
Labels: runs-on

#17199 Bump - Limit number of reports and messages in exec plugin GetMessages phase [CCIP-5647]
  core/scripts/go.mod
  core/scripts/go.sum
  deployment/go.mod
  deployment/go.sum
  go.mod
  go.sum
  integration-tests/go.mod
  integration-tests/go.sum
  integration-tests/load/go.mod
  integration-tests/load/go.sum
  system-tests/lib/go.mod
  system-tests/lib/go.sum
  system-tests/tests/go.mod
  system-tests/tests/go.sum
Labels: runs-on

#17281 [DX-454] break up por jobs
  system-tests/lib/cre/don/jobs/compute/compute.go
  system-tests/lib/cre/don/jobs/consensus/consensus.go
  system-tests/lib/cre/don/jobs/cron/cron.go
  system-tests/lib/cre/don/jobs/gateway/gateway.go
  system-tests/lib/cre/don/jobs/por/por.go
  system-tests/lib/cre/environment/environment.go
  system-tests/lib/infra/blockchain.go
  system-tests/tests/smoke/cre/cmd/environment/environment.go
  system-tests/tests/smoke/cre/environment-capabilities-don-ci.toml
  system-tests/tests/smoke/cre/environment-capabilities-don-crib.toml
  system-tests/tests/smoke/cre/environment-capabilities-don.toml
  system-tests/tests/smoke/cre/environment-gateway-don-ci.toml
  system-tests/tests/smoke/cre/environment-gateway-don.toml
  system-tests/tests/smoke/cre/environment-one-don-ci.toml
  system-tests/tests/smoke/cre/environment-one-don.toml
  system-tests/tests/smoke/cre/por_test.go
  system-tests/tests/smoke/cre/workflow_don_load_test.go
Labels: runs-on

#17298 core/services/chainlink: fix NodeStatuses pagination
  core/services/chainlink/relayer_chain_interoperators.go
Labels: runs-on

#17125 CCIP-5564: Update chain id as string
  deployment/environment/crib/helpers.go
  deployment/environment/devenv/don.go
  integration-tests/testsetups/ccip/test_helpers.go
  system-tests/lib/cre/environment/environment.go
Labels: runs-on

#17292 [CLD-150]: fix(operations): migrate Operations API to CLDF
  core/scripts/go.mod
  core/scripts/go.sum
  deployment/changeset.go
  deployment/common/changeset/example/operations/deploy_and_mint_example.go
  deployment/common/changeset/example/operations/operation.go
  deployment/common/changeset/example/operations/retry_config_example.go
  deployment/common/changeset/example/operations/retry_config_example_test.go
  deployment/common/changeset/example/operations/terminal_error_example.go
  deployment/common/changeset/example/operations/terminal_error_example_test.go
  deployment/environment.go
  deployment/go.mod
  deployment/go.sum
  deployment/operations/execute.go
  deployment/operations/execute_test.go
  deployment/operations/hashing.go
  deployment/operations/hashing_test.go
  deployment/operations/operation.go
  deployment/operations/operation_test.go
  deployment/operations/report.go
  deployment/operations/report_test.go
  deployment/operations/sequence.go
  deployment/operations/sequence_test.go
  deployment/operations/validation.go
  deployment/operations/validation_test.go
  go.md
  integration-tests/go.mod
  integration-tests/go.sum
  integration-tests/load/go.mod
  integration-tests/load/go.sum
  system-tests/lib/go.mod
  system-tests/lib/go.sum
  system-tests/tests/go.mod
  system-tests/tests/go.sum
Labels: runs-on

#17217 bumping common
  core/capabilities/integration_tests/por/workflows/fetchtrueusd/main.go
  core/scripts/chaincli/handler/handler.go
  core/scripts/go.mod
  core/scripts/go.sum
  deployment/go.mod
  deployment/go.sum
  go.md
  go.mod
  go.sum
  integration-tests/go.mod
  integration-tests/go.sum
  integration-tests/load/automationv2_1/automationv2_1_test.go
  integration-tests/load/go.mod
  integration-tests/load/go.sum
  system-tests/lib/go.mod
  system-tests/lib/go.sum
  system-tests/tests/go.mod
  system-tests/tests/go.sum
Labels: runs-on

#17198 DPA-1556 Distribute stream jobs
  deployment/ccip/changeset/solana/cs_chain_contracts_test.go
  deployment/ccip/changeset/solana/cs_deploy_chain_test.go
  deployment/ccip/changeset/solana/cs_ops_test.go
  deployment/ccip/changeset/solana/cs_rmn_remote_test.go
  deployment/ccip/changeset/solana/cs_token_pool_test.go
  deployment/ccip/changeset/testhelpers/test_environment.go
  deployment/ccip/changeset/testhelpers/test_helpers.go
  deployment/ccip/changeset/v1_5_1/cs_configure_token_pools_test.go
  deployment/common/changeset/example/solana_transfer_mcm_test.go
  deployment/common/changeset/set_config_mcms_test.go
  deployment/common/changeset/solana/fund_mcm_pdas_test.go
  deployment/common/changeset/solana/transfer_ownership_test.go
  deployment/common/changeset/test_helpers.go
  deployment/data-streams/changeset/jd_distribute_bootstrap_jobs_test.go
  deployment/data-streams/changeset/jd_distribute_llo_jobs.go
  deployment/data-streams/changeset/jd_distribute_llo_jobs_test.go
  deployment/data-streams/changeset/jd_distribute_stream_jobs.go
  deployment/data-streams/changeset/jd_distribute_stream_jobs_test.go
  deployment/data-streams/changeset/sequence/deploy_chain_contracts_test.go
  deployment/data-streams/changeset/testutil/test_helpers.go
  deployment/data-streams/jobs/stream.go
  deployment/data-streams/jobs/stream_test.go
  deployment/data-streams/jobs/streamtype.go
  deployment/data-streams/jobs/templates/osrc_mercury_v1_median.go.tmpl
  deployment/data-streams/jobs/templates/osrc_mercury_v1_quote.go.tmpl
  deployment/environment/memory/environment.go
  deployment/environment/memory/job_service_client_test.go
  deployment/environment/memory/node.go
  deployment/environment/memory/node_service_client.go
  deployment/environment/memory/node_test.go
  deployment/keystone/changeset/test/env_setup.go
Labels: runs-on

#17303 Make delete job idempotent
  deployment/common/changeset/jobspec.go
Labels: runs-on

#17306 bumping common
  core/scripts/go.mod
  core/scripts/go.sum
  core/services/workflows/metering.go
  deployment/go.mod
  deployment/go.sum
  go.mod
  go.sum
  integration-tests/go.mod
  integration-tests/go.sum
  integration-tests/load/go.mod
  integration-tests/load/go.sum
  system-tests/lib/go.mod
  system-tests/lib/go.sum
  system-tests/tests/go.mod
  system-tests/tests/go.sum
Labels: runs-on

#16579 [CRE-332] Standalone Workflow Engine script
  core/capabilities/fakes/consensus.go
  core/capabilities/fakes/streams_trigger.go
  core/capabilities/fakes/utils.go
  core/capabilities/fakes/write_chain.go
  core/scripts/cre/engine/README
  core/scripts/cre/engine/examples/data_feeds/config_100_feeds.json
  core/scripts/cre/engine/examples/data_feeds/config_10_feeds.json
  core/scripts/cre/engine/examples/data_feeds/config_2_feeds.json
  core/scripts/cre/engine/examples/data_feeds/data_feeds_workflow.go
  core/scripts/cre/engine/main.go
  core/scripts/cre/engine/utils.go
  core/services/workflows/engine.go
  core/services/workflows/models.go
Labels: runs-on

#17309 Ccip-5618 Deterministic CCIP Job External ID
  core/capabilities/ccip/validate/validate.go
Labels: runs-on

#17318 Bump solana compute unit limit in SendRequest, fix issue with CR namespace collision
  core/scripts/go.mod
  core/scripts/go.sum
  deployment/ccip/changeset/testhelpers/test_helpers.go
  deployment/go.mod
  deployment/go.sum
  go.mod
  go.sum
  integration-tests/go.mod
  integration-tests/go.sum
  integration-tests/load/go.mod
  integration-tests/load/go.sum
  system-tests/lib/go.mod
  system-tests/lib/go.sum
  system-tests/tests/go.mod
  system-tests/tests/go.sum
Labels: runs-on

#17325 split setocr ixns
  deployment/ccip/changeset/solana/cs_set_ocr3.go
Labels: runs-on

#16994 Send Metering Report to Billing + Beholder
  core/services/workflows/engine.go
  core/services/workflows/engine_test.go
  core/services/workflows/events.go
  core/services/workflows/metering.go
  core/services/workflows/monitoring.go
Labels: runs-on

#17323 chore: deprecates AddressBook
  deployment/changeset.go
  deployment/environment.go
Labels: runs-on

#17316 remove testcontainers-go replaces, bump to CTF that works with v0.36.0 of testcontainers-go
  core/scripts/go.mod
  core/scripts/go.sum
  deployment/environment/devenv/rmn.go
  deployment/environment/memory/aptos_chains.go
  deployment/go.mod
  deployment/go.sum
  integration-tests/docker/cmd/main.go
  integration-tests/docker/test_env/cl_node.go
  integration-tests/go.mod
  integration-tests/go.sum
  integration-tests/load/go.mod
  integration-tests/load/go.sum
  system-tests/lib/go.mod
  system-tests/lib/go.sum
  system-tests/tests/go.mod
  system-tests/tests/go.sum
Labels: runs-on, run-e2e-tests

#17328 rename codeowner `realtime`->`data-tooling
  .github/CODEOWNERS
Labels: runs-on

#17331 upgrade chainlink-ccip
  core/scripts/go.mod
  core/scripts/go.sum
  deployment/go.mod
  deployment/go.sum
  go.mod
  go.sum
  integration-tests/go.mod
  integration-tests/go.sum
  integration-tests/load/go.mod
  integration-tests/load/go.sum
  system-tests/lib/go.mod
  system-tests/lib/go.sum
  system-tests/tests/go.mod
  system-tests/tests/go.sum
Labels: runs-on

#17321 Workflow DON load test fixes
  system-tests/lib/cre/crib/crib.go
  system-tests/lib/cre/environment/environment.go
  system-tests/tests/load/cre/workflow-don-load-test-streams.toml
  system-tests/tests/load/cre/workflow_don_load_test.go
Labels: runs-on

#16925 (refactor): Workflow Registry Syncer reconciliation loop
  .changeset/pink-penguins-pop.md
  core/services/chainlink/application.go
  core/services/relay/evm/capabilities/workflows/syncer/workflow_syncer_test.go
  core/services/workflows/syncer/engine_registry.go
  core/services/workflows/syncer/engine_registry_test.go
  core/services/workflows/syncer/handler.go
  core/services/workflows/syncer/handler_test.go
  core/services/workflows/syncer/workflow_registry.go
  core/services/workflows/syncer/workflow_registry_test.go
Labels: runs-on

#17311 Ccip-5632 proper mcms contract based on MCMS action
  deployment/ccip/changeset/deployer_group.go
  deployment/ccip/changeset/v1_5/cs_rmn.go
  deployment/ccip/changeset/v1_6/config.go
  deployment/ccip/changeset/v1_6/cs_ccip_home.go
  deployment/ccip/changeset/v1_6/cs_chain_contracts.go
  deployment/ccip/changeset/v1_6/cs_home_chain.go
  deployment/ccip/changeset/v1_6/cs_update_rmn_config.go
  deployment/common/changeset/set_config_mcms.go
  deployment/common/proposalutils/propose.go
Labels: runs-on

#17330 [CAPPL-731] Detect NoDAG WASM when creating Engine
  core/capabilities/compute/cache.go
  core/capabilities/compute/compute.go
  core/scripts/go.mod
  core/scripts/go.sum
  core/services/workflows/syncer/handler.go
  core/services/workflows/v2/engine.go
  deployment/go.mod
  deployment/go.sum
  go.mod
  go.sum
  integration-tests/go.mod
  integration-tests/go.sum
  integration-tests/load/go.mod
  integration-tests/load/go.sum
  system-tests/lib/go.mod
  system-tests/lib/go.sum
  system-tests/tests/go.mod
  system-tests/tests/go.sum
Labels: runs-on

#17238 beholder: wire up config options for chip-ingress
  .changeset/thin-jeans-rule.md
  core/cmd/shell.go
  core/config/docs/core.toml
  core/config/telemetry_config.go
  core/config/toml/types.go
  core/services/chainlink/config_telemetry.go
  core/services/chainlink/config_telemetry_test.go
  core/services/chainlink/config_test.go
  core/services/chainlink/testdata/config-empty-effective.toml
  core/services/chainlink/testdata/config-full.toml
  core/services/chainlink/testdata/config-multi-chain-effective.toml
  core/web/resolver/testdata/config-empty-effective.toml
  core/web/resolver/testdata/config-full.toml
  core/web/resolver/testdata/config-multi-chain-effective.toml
  docs/CONFIG.md
  plugins/loop_registry.go
  plugins/loop_registry_test.go
  testdata/scripts/config/merge_raw_configs.txtar
  testdata/scripts/node/validate/default.txtar
  testdata/scripts/node/validate/defaults-override.txtar
  testdata/scripts/node/validate/disk-based-logging-disabled.txtar
  testdata/scripts/node/validate/disk-based-logging-no-dir.txtar
  testdata/scripts/node/validate/disk-based-logging.txtar
  testdata/scripts/node/validate/fallback-override.txtar
  testdata/scripts/node/validate/invalid-ocr-p2p.txtar
  testdata/scripts/node/validate/invalid.txtar
  testdata/scripts/node/validate/valid.txtar
  testdata/scripts/node/validate/warnings.txtar
Labels: build-publish, runs-on

#17307 rm gogo/protobuf replaces
  core/scripts/go.mod
  core/scripts/go.sum
  deployment/go.mod
  deployment/go.sum
  go.md
  go.mod
  go.sum
  integration-tests/go.mod
  integration-tests/go.sum
  integration-tests/load/go.mod
  integration-tests/load/go.sum
  plugins/plugins.public.yaml
  system-tests/lib/go.mod
  system-tests/lib/go.sum
  system-tests/tests/go.mod
  system-tests/tests/go.sum
Labels: runs-on

#17299 bump chain selectors to v1.0.52
  core/scripts/go.mod
  core/scripts/go.sum
  deployment/go.mod
  deployment/go.sum
  go.mod
  go.sum
  integration-tests/go.mod
  integration-tests/go.sum
  integration-tests/load/go.mod
  integration-tests/load/go.sum
  system-tests/lib/go.mod
  system-tests/lib/go.sum
  system-tests/tests/go.mod
  system-tests/tests/go.sum
Labels: runs-on, run-e2e-tests

#17352 [DX-550] Support using imported secrets in CRE SDK
  system-tests/lib/conversions/ints.go
  system-tests/lib/cre/don/don.go
  system-tests/lib/cre/don/secrets/secrets.go
  system-tests/lib/cre/environment/environment.go
  system-tests/lib/cre/types/keystone.go
  system-tests/lib/crypto/evm.go
  system-tests/lib/crypto/p2p.go
  system-tests/lib/types/crypto.go
  system-tests/tests/load/cre/workflow_don_load_test.go
  system-tests/tests/smoke/cre/cmd/configs/single-don.toml
  system-tests/tests/smoke/cre/cmd/configs/workflow-capabilities-don.toml
  system-tests/tests/smoke/cre/environment-capabilities-don-ci.toml
  system-tests/tests/smoke/cre/environment-capabilities-don-crib.toml
  system-tests/tests/smoke/cre/environment-capabilities-don.toml
  system-tests/tests/smoke/cre/environment-gateway-don-ci.toml
  system-tests/tests/smoke/cre/environment-gateway-don.toml
  system-tests/tests/smoke/cre/environment-one-don-ci.toml
  system-tests/tests/smoke/cre/environment-one-don.toml
  system-tests/tests/smoke/cre/guidelines.md
Labels: run-e2e-tests

#17096 CCIP 1.5 - Tron
  .changeset/dirty-jeans-compete.md
  core/chains/evm/tron/txm.go
  core/chains/legacyevm/chain.go
  core/scripts/ccip/manual-execution/go.mod
  core/scripts/ccip/manual-execution/go.sum
  core/scripts/go.mod
  core/scripts/go.sum
  core/services/ocr2/plugins/ccip/ccipexec/batching.go
  core/services/relay/evm/commit_provider.go
  core/services/relay/evm/evm.go
  core/services/relay/evm/exec_provider.go
  core/services/relay/evm/tron_transmitter.go
  deployment/go.mod
  deployment/go.sum
  go.md
  go.mod
  go.sum
  integration-tests/go.mod
  integration-tests/go.sum
  integration-tests/load/go.mod
  integration-tests/load/go.sum
  system-tests/lib/go.mod
  system-tests/lib/go.sum
  system-tests/tests/go.mod
  system-tests/tests/go.sum
Labels: build-publish

#17315 [DX-81] add secret to PoR workflow
  system-tests/lib/cre/environment/environment.go
  system-tests/lib/cre/types/keystone.go
  system-tests/lib/cre/workflow/workflow.go
  system-tests/lib/crecli/commands.go
  system-tests/lib/crecli/por/por.go
  system-tests/lib/crecli/secrets.go
  system-tests/lib/crecli/settings.go
  system-tests/tests/smoke/cre/environment-capabilities-don-ci.toml
  system-tests/tests/smoke/cre/environment-gateway-don-ci.toml
  system-tests/tests/smoke/cre/environment-one-don-ci.toml
  system-tests/tests/smoke/cre/por_price_provider.go
  system-tests/tests/smoke/cre/por_test.go
Labels: runs-on, runs-on-e2e, run-e2e-tests

#17177 added statemachine to Parallel Executor to fix race on the waitgroup
  core/capabilities/remote/executable/parallel_executor.go
  core/capabilities/remote/executable/parallel_executor_test.go
  core/capabilities/remote/executable/server.go
Labels: runs-on

#17322 [CCIP-5728] core/capabilities/ccip/ccipevm: fix SVM extraArg decoding
  core/capabilities/ccip/ccipevm/extradatadecoder.go
  core/capabilities/ccip/ccipevm/extradatadecoder_test.go
  core/capabilities/ccip/ccipevm/helpers.go
  core/scripts/go.mod
  core/scripts/go.sum
  deployment/go.mod
  deployment/go.sum
  go.mod
  go.sum
  integration-tests/go.mod
  integration-tests/go.sum
  integration-tests/load/go.mod
  integration-tests/load/go.sum
  system-tests/lib/go.mod
  system-tests/lib/go.sum
  system-tests/tests/go.mod
  system-tests/tests/go.sum
Labels: runs-on

#17442 bump chainlink-evm for added Rootstock chaintype
  .changeset/yummy-maps-bathe.md
  core/scripts/go.mod
  core/scripts/go.sum
  core/services/chainlink/config_test.go
  core/services/ocr/contract_tracker.go
  core/services/ocrcommon/block_translator.go
  deployment/go.mod
  deployment/go.sum
  go.mod
  go.sum
  integration-tests/go.mod
  integration-tests/go.sum
  integration-tests/load/go.mod
  integration-tests/load/go.sum
  system-tests/lib/go.mod
  system-tests/lib/go.sum
  system-tests/tests/go.mod
  system-tests/tests/go.sum
Labels: build-publish

#17450 fix: e2e cron test config
  .github/e2e-tests.yml
Labels: run-e2e-tests

#17475 Cappl 720 implement backoff
  core/services/relay/evm/capabilities/workflows/syncer/workflow_syncer_test.go
  core/services/workflows/syncer/engine_registry.go
  core/services/workflows/syncer/engine_registry_test.go
  core/services/workflows/syncer/handler.go
  core/services/workflows/syncer/handler_test.go
  core/services/workflows/syncer/workflow_registry.go
  core/services/workflows/syncer/workflow_registry_test.go
Labels: build-publish

#17171 [chore] Add duration count for registry syncer
  core/capabilities/remote/executable/request/server_request.go
  core/capabilities/webapi/outgoing_connector_handler.go
  core/services/gateway/handlers/capabilities/handler.go
  core/services/workflows/syncer/workflow_registry.go
Labels: runs-on

#17481 [DX-632, DX-633] break up functions
  system-tests/lib/cre/capabilities/chainreader/chainreader.go
  system-tests/lib/cre/capabilities/chainwriter/chainwriter.go
  system-tests/lib/cre/capabilities/compute/compute.go
  system-tests/lib/cre/capabilities/consensus/consensus.go
  system-tests/lib/cre/capabilities/cron/cron.go
  system-tests/lib/cre/capabilities/webapi/webapi.go
  system-tests/lib/cre/contracts/contracts.go
  system-tests/lib/cre/contracts/workflow_registry.go
  system-tests/lib/cre/don/config/config.go
  system-tests/lib/cre/don/config/gateway/gateway.go
  system-tests/lib/cre/don/config/por/por.go
  system-tests/lib/cre/environment/environment.go
  system-tests/lib/cre/types/keystone.go
  system-tests/lib/cre/workflow/workflow.go
  system-tests/tests/smoke/cre/cmd/environment/environment.go
  system-tests/tests/smoke/cre/environment-gateway-don-ci.toml
  system-tests/tests/smoke/cre/por_test.go
Labels: run-e2e-tests

#17242 pipeline/bridge: add error debug log
  core/services/pipeline/task.bridge.go
Labels: build-test-image

#17498 [DX-638] forwarder's F should depend on worker node count, ocr3 config should …
  system-tests/lib/conversions/ints.go
  system-tests/lib/cre/contracts/contracts.go
  system-tests/lib/cre/environment/environment.go
  system-tests/lib/cre/types/keystone.go
  system-tests/tests/smoke/cre/por_price_provider.go
Labels: run-e2e-tests

#17287 Data Streams: Fix the TOML serialisation of the LLO job spec.
  deployment/data-feeds/changeset/jd_register_nodes.go
  deployment/data-feeds/offchain/jd.go
  deployment/data-streams/changeset/common.go
  deployment/data-streams/changeset/deploy_channel_config_store.go
  deployment/data-streams/changeset/deploy_channel_config_store_test.go
  deployment/data-streams/changeset/jd_distribute_bootstrap_jobs.go
  deployment/data-streams/changeset/jd_distribute_bootstrap_jobs_test.go
  deployment/data-streams/changeset/jd_distribute_llo_jobs.go
  deployment/data-streams/changeset/jd_distribute_llo_jobs_test.go
  deployment/data-streams/changeset/jd_distribute_stream_jobs.go
  deployment/data-streams/changeset/jd_distribute_stream_jobs_test.go
  deployment/data-streams/changeset/jd_register_nodes.go
  deployment/data-streams/changeset/testutil/test_helpers.go
  deployment/data-streams/jd/jd.go
  deployment/data-streams/jd/nodetype.go
  deployment/data-streams/jobs/bootstrap.go
  deployment/data-streams/jobs/llo.go
  deployment/data-streams/jobs/llo_test.go
  deployment/data-streams/utils/identifiers.go
  deployment/environment/devenv/don.go
  deployment/environment/memory/environment.go
  deployment/environment/memory/node.go
  deployment/environment/memory/node_service_client.go
  deployment/environment/memory/offchain_client.go
  deployment/environment/test/job_service_client.go
Labels: runs-on
