Repository smartcontractkit/chainlink, pull requests merged in 2025-02, with the labels that each got.

#16155 Update GoReleaser config to avoid adding duplicate images in manifests
  .goreleaser.develop.yaml
  .goreleaser.devspace.yaml
  .goreleaser.production.yaml
Labels: build-publish

#16029 [TT-1952] Write application logs for in-memory tests to file and safe in artifacts
  .github/integration-in-memory-tests.yml
  deployment/environment/memory/node.go
  deployment/logger/single_file_logger.go
Labels: do not merge

#16366 fix(services/feeds): only check for standard cap spec by ext job id
  .changeset/pink-singers-greet.md
  core/services/feeds/service.go
Labels: build-publish

#16551 chore: goreleaser workflow maintanence
  .github/actions/goreleaser-build-sign-publish/action.yml
  .github/workflows/build-publish-develop-pr.yml
Labels: build-publish

#16597 fix: full clone on goreleaser 'nightly' releases
  .github/workflows/build-publish-develop-pr.yml
Labels: build-publish

#16598 fix: update deprecated fields for goreleaser configs
  .goreleaser.develop.yaml
  .goreleaser.devspace.yaml
  .goreleaser.production.yaml
Labels: build-publish

#16628 rm liq man offchain
  .mockery.yaml
  contracts/.changeset/brave-goats-occur.md
  contracts/package.json
  contracts/release/ccip/package.json
  contracts/src/v0.8/ccip/pools/LockReleaseTokenPool.sol
  core/gethwrappers/liquiditymanager/generated/abstract_arbitrum_token_gateway/abstract_arbitrum_token_gateway.go
  core/gethwrappers/liquiditymanager/generated/arb_node_interface/arb_node_interface.go
  core/gethwrappers/liquiditymanager/generated/arbitrum_gateway_router/arbitrum_gateway_router.go
  core/gethwrappers/liquiditymanager/generated/arbitrum_inbox/arbitrum_inbox.go
  core/gethwrappers/liquiditymanager/generated/arbitrum_l1_bridge_adapter/arbitrum_l1_bridge_adapter.go
  core/gethwrappers/liquiditymanager/generated/arbitrum_l1_gateway_router/arbitrum_l1_gateway_router.go
  core/gethwrappers/liquiditymanager/generated/arbitrum_l2_bridge_adapter/arbitrum_l2_bridge_adapter.go
  core/gethwrappers/liquiditymanager/generated/arbitrum_rollup_core/arbitrum_rollup_core.go
  core/gethwrappers/liquiditymanager/generated/arbitrum_token_gateway/arbitrum_token_gateway.go
  core/gethwrappers/liquiditymanager/generated/arbsys/arbsys.go
  core/gethwrappers/liquiditymanager/generated/l2_arbitrum_gateway/l2_arbitrum_gateway.go
  core/gethwrappers/liquiditymanager/generated/l2_arbitrum_messenger/l2_arbitrum_messenger.go
  core/gethwrappers/liquiditymanager/generated/liquiditymanager/liquiditymanager.go
  core/gethwrappers/liquiditymanager/generated/mock_l1_bridge_adapter/mock_l1_bridge_adapter.go
  core/gethwrappers/liquiditymanager/generated/mock_l2_bridge_adapter/mock_l2_bridge_adapter.go
  core/gethwrappers/liquiditymanager/generated/no_op_ocr3/no_op_ocr3.go
  core/gethwrappers/liquiditymanager/generated/optimism_cross_domain_messenger/optimism_cross_domain_messenger.go
  core/gethwrappers/liquiditymanager/generated/optimism_dispute_game_factory/optimism_dispute_game_factory.go
  core/gethwrappers/liquiditymanager/generated/optimism_l1_bridge_adapter/optimism_l1_bridge_adapter.go
  core/gethwrappers/liquiditymanager/generated/optimism_l1_bridge_adapter_encoder/optimism_l1_bridge_adapter_encoder.go
  core/gethwrappers/liquiditymanager/generated/optimism_l1_standard_bridge/optimism_l1_standard_bridge.go
  core/gethwrappers/liquiditymanager/generated/optimism_l2_bridge_adapter/optimism_l2_bridge_adapter.go
  core/gethwrappers/liquiditymanager/generated/optimism_l2_output_oracle/optimism_l2_output_oracle.go
  core/gethwrappers/liquiditymanager/generated/optimism_l2_to_l1_message_passer/optimism_l2_to_l1_message_passer.go
  core/gethwrappers/liquiditymanager/generated/optimism_portal/optimism_portal.go
  core/gethwrappers/liquiditymanager/generated/optimism_portal_2/optimism_portal_2.go
  core/gethwrappers/liquiditymanager/generated/optimism_standard_bridge/optimism_standard_bridge.go
  core/gethwrappers/liquiditymanager/generated/report_encoder/report_encoder.go
  core/gethwrappers/liquiditymanager/generation/generated-wrapper-dependency-versions-do-not-edit.txt
  core/gethwrappers/liquiditymanager/mocks/mock_arbitrum_gateway_router/arbitrum_gateway_router_interface.go
  core/gethwrappers/liquiditymanager/mocks/mock_arbitrum_inbox/arbitrum_inbox_interface.go
  core/gethwrappers/liquiditymanager/mocks/mock_arbitrum_l1_bridge_adapter/arbitrum_l1_bridge_adapter_interface.go
  core/gethwrappers/liquiditymanager/mocks/mock_arbitrum_l2_bridge_adapter/arbitrum_l2_bridge_adapter_interface.go
  core/gethwrappers/liquiditymanager/mocks/mock_arbitrum_rollup_core/arb_rollup_core_interface.go
  core/gethwrappers/liquiditymanager/mocks/mock_arbsys/arb_sys_interface.go
  core/gethwrappers/liquiditymanager/mocks/mock_l2_arbitrum_gateway/l2_arbitrum_gateway_interface.go
  core/gethwrappers/liquiditymanager/mocks/mock_l2_arbitrum_messenger/l2_arbitrum_messenger_interface.go
  core/gethwrappers/liquiditymanager/mocks/mock_node_interface/node_interface_interface.go
  core/gethwrappers/liquiditymanager/mocks/mock_optimism_dispute_game_factory/optimism_dispute_game_factory_interface.go
  core/gethwrappers/liquiditymanager/mocks/mock_optimism_l2_output_oracle/optimism_l2_output_oracle_interface.go
  core/gethwrappers/liquiditymanager/mocks/mock_optimism_portal/optimism_portal_interface.go
  core/gethwrappers/liquiditymanager/mocks/mock_optimism_portal_2/optimism_portal2_interface.go
  integration-tests/ccip-tests/contracts/lm_contracts.go
Labels: allow-lint-issues
